/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.gtfs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StopTime service. Represents a row in the &quot;gtfs_StopTime&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.gtfs.model.impl.StopTimeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.gtfs.model.impl.StopTimeImpl</code>.
 * </p>
 *
 * @author Cedric Henry
 * @see StopTime
 * @generated
 */
@ProviderType
public interface StopTimeModel extends BaseModel<StopTime> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stop time model instance should use the {@link StopTime} interface instead.
	 */

	/**
	 * Returns the primary key of this stop time.
	 *
	 * @return the primary key of this stop time
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stop time.
	 *
	 * @param primaryKey the primary key of this stop time
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this stop time.
	 *
	 * @return the uuid of this stop time
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this stop time.
	 *
	 * @param uuid the uuid of this stop time
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this stop time.
	 *
	 * @return the ID of this stop time
	 */
	public long getId();

	/**
	 * Sets the ID of this stop time.
	 *
	 * @param id the ID of this stop time
	 */
	public void setId(long id);

	/**
	 * Returns the trip_id of this stop time.
	 *
	 * @return the trip_id of this stop time
	 */
	@AutoEscape
	public String getTrip_id();

	/**
	 * Sets the trip_id of this stop time.
	 *
	 * @param trip_id the trip_id of this stop time
	 */
	public void setTrip_id(String trip_id);

	/**
	 * Returns the arrival_time of this stop time.
	 *
	 * @return the arrival_time of this stop time
	 */
	public Date getArrival_time();

	/**
	 * Sets the arrival_time of this stop time.
	 *
	 * @param arrival_time the arrival_time of this stop time
	 */
	public void setArrival_time(Date arrival_time);

	/**
	 * Returns the departure_time of this stop time.
	 *
	 * @return the departure_time of this stop time
	 */
	public Date getDeparture_time();

	/**
	 * Sets the departure_time of this stop time.
	 *
	 * @param departure_time the departure_time of this stop time
	 */
	public void setDeparture_time(Date departure_time);

	/**
	 * Returns the stop_id of this stop time.
	 *
	 * @return the stop_id of this stop time
	 */
	@AutoEscape
	public String getStop_id();

	/**
	 * Sets the stop_id of this stop time.
	 *
	 * @param stop_id the stop_id of this stop time
	 */
	public void setStop_id(String stop_id);

	/**
	 * Returns the stop_sequence of this stop time.
	 *
	 * @return the stop_sequence of this stop time
	 */
	public int getStop_sequence();

	/**
	 * Sets the stop_sequence of this stop time.
	 *
	 * @param stop_sequence the stop_sequence of this stop time
	 */
	public void setStop_sequence(int stop_sequence);

	/**
	 * Returns the pickup_type of this stop time.
	 *
	 * @return the pickup_type of this stop time
	 */
	@AutoEscape
	public String getPickup_type();

	/**
	 * Sets the pickup_type of this stop time.
	 *
	 * @param pickup_type the pickup_type of this stop time
	 */
	public void setPickup_type(String pickup_type);

	/**
	 * Returns the drop_off_type of this stop time.
	 *
	 * @return the drop_off_type of this stop time
	 */
	@AutoEscape
	public String getDrop_off_type();

	/**
	 * Sets the drop_off_type of this stop time.
	 *
	 * @param drop_off_type the drop_off_type of this stop time
	 */
	public void setDrop_off_type(String drop_off_type);

	@Override
	public StopTime cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}