/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.place.model.impl;

import eu.strasbourg.service.place.model.GoogleMyBusinessHistoric;
import eu.strasbourg.service.place.service.GoogleMyBusinessHistoricLocalServiceUtil;

/**
 * The extended model base implementation for the GoogleMyBusinessHistoric service. Represents a row in the &quot;place_GoogleMyBusinessHistoric&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GoogleMyBusinessHistoricImpl}.
 * </p>
 *
 * @author Angelique Zunino Champougny
 * @see GoogleMyBusinessHistoricImpl
 * @see GoogleMyBusinessHistoric
 * @generated
 */
public abstract class GoogleMyBusinessHistoricBaseImpl
	extends GoogleMyBusinessHistoricModelImpl
	implements GoogleMyBusinessHistoric {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a google my business historic model instance should use the <code>GoogleMyBusinessHistoric</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GoogleMyBusinessHistoricLocalServiceUtil.
				addGoogleMyBusinessHistoric(this);
		}
		else {
			GoogleMyBusinessHistoricLocalServiceUtil.
				updateGoogleMyBusinessHistoric(this);
		}
	}

}