/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.place.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import eu.strasbourg.service.place.model.Slot;
import eu.strasbourg.service.place.model.SlotModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Slot service. Represents a row in the &quot;place_Slot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SlotModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SlotImpl}.
 * </p>
 *
 * @author Angelique Zunino Champougny
 * @see SlotImpl
 * @generated
 */
public class SlotModelImpl extends BaseModelImpl<Slot> implements SlotModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a slot model instance should use the <code>Slot</code> interface instead.
	 */
	public static final String TABLE_NAME = "place_Slot";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"slotId", Types.BIGINT},
		{"dayOfWeek", Types.BIGINT}, {"startHour", Types.VARCHAR},
		{"endHour", Types.VARCHAR}, {"comment_", Types.VARCHAR},
		{"periodId", Types.BIGINT}, {"subPlaceId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("slotId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dayOfWeek", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startHour", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endHour", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("comment_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("periodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subPlaceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table place_Slot (uuid_ VARCHAR(75) null,slotId LONG not null primary key,dayOfWeek LONG,startHour VARCHAR(75) null,endHour VARCHAR(75) null,comment_ STRING null,periodId LONG,subPlaceId LONG)";

	public static final String TABLE_SQL_DROP = "drop table place_Slot";

	public static final String ORDER_BY_JPQL = " ORDER BY slot.slotId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY place_Slot.slotId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERIODID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBPLACEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SLOTID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.place.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.place.model.Slot"));

	public SlotModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _slotId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSlotId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _slotId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Slot.class;
	}

	@Override
	public String getModelClassName() {
		return Slot.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Slot, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Slot, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Slot, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Slot)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Slot, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Slot, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Slot)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Slot, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Slot, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Slot, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Slot, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Slot, Object>>();

			attributeGetterFunctions.put("uuid", Slot::getUuid);
			attributeGetterFunctions.put("slotId", Slot::getSlotId);
			attributeGetterFunctions.put("dayOfWeek", Slot::getDayOfWeek);
			attributeGetterFunctions.put("startHour", Slot::getStartHour);
			attributeGetterFunctions.put("endHour", Slot::getEndHour);
			attributeGetterFunctions.put("comment", Slot::getComment);
			attributeGetterFunctions.put("periodId", Slot::getPeriodId);
			attributeGetterFunctions.put("subPlaceId", Slot::getSubPlaceId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Slot, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Slot, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Slot, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Slot, String>)Slot::setUuid);
			attributeSetterBiConsumers.put(
				"slotId", (BiConsumer<Slot, Long>)Slot::setSlotId);
			attributeSetterBiConsumers.put(
				"dayOfWeek", (BiConsumer<Slot, Long>)Slot::setDayOfWeek);
			attributeSetterBiConsumers.put(
				"startHour", (BiConsumer<Slot, String>)Slot::setStartHour);
			attributeSetterBiConsumers.put(
				"endHour", (BiConsumer<Slot, String>)Slot::setEndHour);
			attributeSetterBiConsumers.put(
				"comment", (BiConsumer<Slot, String>)Slot::setComment);
			attributeSetterBiConsumers.put(
				"periodId", (BiConsumer<Slot, Long>)Slot::setPeriodId);
			attributeSetterBiConsumers.put(
				"subPlaceId", (BiConsumer<Slot, Long>)Slot::setSubPlaceId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getSlotId() {
		return _slotId;
	}

	@Override
	public void setSlotId(long slotId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_slotId = slotId;
	}

	@Override
	public long getDayOfWeek() {
		return _dayOfWeek;
	}

	@Override
	public void setDayOfWeek(long dayOfWeek) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dayOfWeek = dayOfWeek;
	}

	@Override
	public String getStartHour() {
		if (_startHour == null) {
			return "";
		}
		else {
			return _startHour;
		}
	}

	@Override
	public void setStartHour(String startHour) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startHour = startHour;
	}

	@Override
	public String getEndHour() {
		if (_endHour == null) {
			return "";
		}
		else {
			return _endHour;
		}
	}

	@Override
	public void setEndHour(String endHour) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endHour = endHour;
	}

	@Override
	public String getComment() {
		if (_comment == null) {
			return "";
		}
		else {
			return _comment;
		}
	}

	@Override
	public String getComment(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getComment(languageId);
	}

	@Override
	public String getComment(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getComment(languageId, useDefault);
	}

	@Override
	public String getComment(String languageId) {
		return LocalizationUtil.getLocalization(getComment(), languageId);
	}

	@Override
	public String getComment(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getComment(), languageId, useDefault);
	}

	@Override
	public String getCommentCurrentLanguageId() {
		return _commentCurrentLanguageId;
	}

	@JSON
	@Override
	public String getCommentCurrentValue() {
		Locale locale = getLocale(_commentCurrentLanguageId);

		return getComment(locale);
	}

	@Override
	public Map<Locale, String> getCommentMap() {
		return LocalizationUtil.getLocalizationMap(getComment());
	}

	@Override
	public void setComment(String comment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comment = comment;
	}

	@Override
	public void setComment(String comment, Locale locale) {
		setComment(comment, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setComment(
		String comment, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(comment)) {
			setComment(
				LocalizationUtil.updateLocalization(
					getComment(), "Comment", comment, languageId,
					defaultLanguageId));
		}
		else {
			setComment(
				LocalizationUtil.removeLocalization(
					getComment(), "Comment", languageId));
		}
	}

	@Override
	public void setCommentCurrentLanguageId(String languageId) {
		_commentCurrentLanguageId = languageId;
	}

	@Override
	public void setCommentMap(Map<Locale, String> commentMap) {
		setCommentMap(commentMap, LocaleUtil.getDefault());
	}

	@Override
	public void setCommentMap(
		Map<Locale, String> commentMap, Locale defaultLocale) {

		if (commentMap == null) {
			return;
		}

		setComment(
			LocalizationUtil.updateLocalization(
				commentMap, getComment(), "Comment",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public long getPeriodId() {
		return _periodId;
	}

	@Override
	public void setPeriodId(long periodId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_periodId = periodId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPeriodId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("periodId"));
	}

	@Override
	public long getSubPlaceId() {
		return _subPlaceId;
	}

	@Override
	public void setSubPlaceId(long subPlaceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subPlaceId = subPlaceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSubPlaceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("subPlaceId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Slot.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> commentMap = getCommentMap();

		for (Map.Entry<Locale, String> entry : commentMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getComment();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Slot.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String comment = getComment(defaultLocale);

		if (Validator.isNull(comment)) {
			setComment(getComment(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setComment(getComment(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Slot toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Slot>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SlotImpl slotImpl = new SlotImpl();

		slotImpl.setUuid(getUuid());
		slotImpl.setSlotId(getSlotId());
		slotImpl.setDayOfWeek(getDayOfWeek());
		slotImpl.setStartHour(getStartHour());
		slotImpl.setEndHour(getEndHour());
		slotImpl.setComment(getComment());
		slotImpl.setPeriodId(getPeriodId());
		slotImpl.setSubPlaceId(getSubPlaceId());

		slotImpl.resetOriginalValues();

		return slotImpl;
	}

	@Override
	public Slot cloneWithOriginalValues() {
		SlotImpl slotImpl = new SlotImpl();

		slotImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		slotImpl.setSlotId(this.<Long>getColumnOriginalValue("slotId"));
		slotImpl.setDayOfWeek(this.<Long>getColumnOriginalValue("dayOfWeek"));
		slotImpl.setStartHour(this.<String>getColumnOriginalValue("startHour"));
		slotImpl.setEndHour(this.<String>getColumnOriginalValue("endHour"));
		slotImpl.setComment(this.<String>getColumnOriginalValue("comment_"));
		slotImpl.setPeriodId(this.<Long>getColumnOriginalValue("periodId"));
		slotImpl.setSubPlaceId(this.<Long>getColumnOriginalValue("subPlaceId"));

		return slotImpl;
	}

	@Override
	public int compareTo(Slot slot) {
		long primaryKey = slot.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Slot)) {
			return false;
		}

		Slot slot = (Slot)object;

		long primaryKey = slot.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Slot> toCacheModel() {
		SlotCacheModel slotCacheModel = new SlotCacheModel();

		slotCacheModel.uuid = getUuid();

		String uuid = slotCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			slotCacheModel.uuid = null;
		}

		slotCacheModel.slotId = getSlotId();

		slotCacheModel.dayOfWeek = getDayOfWeek();

		slotCacheModel.startHour = getStartHour();

		String startHour = slotCacheModel.startHour;

		if ((startHour != null) && (startHour.length() == 0)) {
			slotCacheModel.startHour = null;
		}

		slotCacheModel.endHour = getEndHour();

		String endHour = slotCacheModel.endHour;

		if ((endHour != null) && (endHour.length() == 0)) {
			slotCacheModel.endHour = null;
		}

		slotCacheModel.comment = getComment();

		String comment = slotCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			slotCacheModel.comment = null;
		}

		slotCacheModel.periodId = getPeriodId();

		slotCacheModel.subPlaceId = getSubPlaceId();

		return slotCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Slot, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Slot, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Slot, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Slot)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Slot>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Slot.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _slotId;
	private long _dayOfWeek;
	private String _startHour;
	private String _endHour;
	private String _comment;
	private String _commentCurrentLanguageId;
	private long _periodId;
	private long _subPlaceId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Slot, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Slot)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("slotId", _slotId);
		_columnOriginalValues.put("dayOfWeek", _dayOfWeek);
		_columnOriginalValues.put("startHour", _startHour);
		_columnOriginalValues.put("endHour", _endHour);
		_columnOriginalValues.put("comment_", _comment);
		_columnOriginalValues.put("periodId", _periodId);
		_columnOriginalValues.put("subPlaceId", _subPlaceId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("comment_", "comment");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("slotId", 2L);

		columnBitmasks.put("dayOfWeek", 4L);

		columnBitmasks.put("startHour", 8L);

		columnBitmasks.put("endHour", 16L);

		columnBitmasks.put("comment_", 32L);

		columnBitmasks.put("periodId", 64L);

		columnBitmasks.put("subPlaceId", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Slot _escapedModel;

}