/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.place.model.impl;

import eu.strasbourg.service.place.model.SubPlace;
import eu.strasbourg.service.place.service.SubPlaceLocalServiceUtil;

/**
 * The extended model base implementation for the SubPlace service. Represents a row in the &quot;place_SubPlace&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubPlaceImpl}.
 * </p>
 *
 * @author Angelique Zunino Champougny
 * @see SubPlaceImpl
 * @see SubPlace
 * @generated
 */
public abstract class SubPlaceBaseImpl
	extends SubPlaceModelImpl implements SubPlace {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sub place model instance should use the <code>SubPlace</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubPlaceLocalServiceUtil.addSubPlace(this);
		}
		else {
			SubPlaceLocalServiceUtil.updateSubPlace(this);
		}
	}

}