/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.strasbourg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Strasbourg service. Represents a row in the &quot;strasbourg_Strasbourg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.strasbourg.model.impl.StrasbourgModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.strasbourg.model.impl.StrasbourgImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Strasbourg
 * @generated
 */
@ProviderType
public interface StrasbourgModel extends BaseModel<Strasbourg> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a strasbourg model instance should use the {@link Strasbourg} interface instead.
	 */

	/**
	 * Returns the primary key of this strasbourg.
	 *
	 * @return the primary key of this strasbourg
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this strasbourg.
	 *
	 * @param primaryKey the primary key of this strasbourg
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this strasbourg.
	 *
	 * @return the uuid of this strasbourg
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this strasbourg.
	 *
	 * @param uuid the uuid of this strasbourg
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this strasbourg.
	 *
	 * @return the ID of this strasbourg
	 */
	public long getId();

	/**
	 * Sets the ID of this strasbourg.
	 *
	 * @param id the ID of this strasbourg
	 */
	public void setId(long id);

	@Override
	public Strasbourg cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}