/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.notification.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import eu.strasbourg.service.notification.model.UserNotificationChannel;
import eu.strasbourg.service.notification.model.UserNotificationChannelModel;
import eu.strasbourg.service.notification.service.persistence.UserNotificationChannelPK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserNotificationChannel service. Represents a row in the &quot;notification_UserNotificationChannel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserNotificationChannelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserNotificationChannelImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see UserNotificationChannelImpl
 * @generated
 */
public class UserNotificationChannelModelImpl
	extends BaseModelImpl<UserNotificationChannel>
	implements UserNotificationChannelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user notification channel model instance should use the <code>UserNotificationChannel</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"notification_UserNotificationChannel";

	public static final Object[][] TABLE_COLUMNS = {
		{"publikUserId", Types.VARCHAR}, {"channelId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table notification_UserNotificationChannel (publikUserId VARCHAR(75) not null,channelId LONG not null,primary key (publikUserId, channelId))";

	public static final String TABLE_SQL_DROP =
		"drop table notification_UserNotificationChannel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userNotificationChannel.id.publikUserId ASC, userNotificationChannel.id.channelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY notification_UserNotificationChannel.publikUserId ASC, notification_UserNotificationChannel.channelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.notification.service.util.ServiceProps.get(
			"lock.expiration.time.eu.strasbourg.service.notification.model.UserNotificationChannel"));

	public UserNotificationChannelModelImpl() {
	}

	@Override
	public UserNotificationChannelPK getPrimaryKey() {
		return new UserNotificationChannelPK(_publikUserId, _channelId);
	}

	@Override
	public void setPrimaryKey(UserNotificationChannelPK primaryKey) {
		setPublikUserId(primaryKey.publikUserId);
		setChannelId(primaryKey.channelId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new UserNotificationChannelPK(_publikUserId, _channelId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((UserNotificationChannelPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UserNotificationChannel.class;
	}

	@Override
	public String getModelClassName() {
		return UserNotificationChannel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserNotificationChannel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserNotificationChannel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserNotificationChannel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserNotificationChannel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserNotificationChannel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserNotificationChannel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserNotificationChannel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserNotificationChannel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserNotificationChannel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<UserNotificationChannel, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<UserNotificationChannel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<UserNotificationChannel, Object>>();

			attributeGetterFunctions.put(
				"publikUserId", UserNotificationChannel::getPublikUserId);
			attributeGetterFunctions.put(
				"channelId", UserNotificationChannel::getChannelId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<UserNotificationChannel, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UserNotificationChannel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<UserNotificationChannel, ?>>();

			attributeSetterBiConsumers.put(
				"publikUserId",
				(BiConsumer<UserNotificationChannel, String>)
					UserNotificationChannel::setPublikUserId);
			attributeSetterBiConsumers.put(
				"channelId",
				(BiConsumer<UserNotificationChannel, Long>)
					UserNotificationChannel::setChannelId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channelId = channelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChannelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("channelId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public UserNotificationChannel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserNotificationChannel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserNotificationChannelImpl userNotificationChannelImpl =
			new UserNotificationChannelImpl();

		userNotificationChannelImpl.setPublikUserId(getPublikUserId());
		userNotificationChannelImpl.setChannelId(getChannelId());

		userNotificationChannelImpl.resetOriginalValues();

		return userNotificationChannelImpl;
	}

	@Override
	public UserNotificationChannel cloneWithOriginalValues() {
		UserNotificationChannelImpl userNotificationChannelImpl =
			new UserNotificationChannelImpl();

		userNotificationChannelImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		userNotificationChannelImpl.setChannelId(
			this.<Long>getColumnOriginalValue("channelId"));

		return userNotificationChannelImpl;
	}

	@Override
	public int compareTo(UserNotificationChannel userNotificationChannel) {
		UserNotificationChannelPK primaryKey =
			userNotificationChannel.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserNotificationChannel)) {
			return false;
		}

		UserNotificationChannel userNotificationChannel =
			(UserNotificationChannel)object;

		UserNotificationChannelPK primaryKey =
			userNotificationChannel.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserNotificationChannel> toCacheModel() {
		UserNotificationChannelCacheModel userNotificationChannelCacheModel =
			new UserNotificationChannelCacheModel();

		userNotificationChannelCacheModel.userNotificationChannelPK =
			getPrimaryKey();

		userNotificationChannelCacheModel.publikUserId = getPublikUserId();

		String publikUserId = userNotificationChannelCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			userNotificationChannelCacheModel.publikUserId = null;
		}

		userNotificationChannelCacheModel.channelId = getChannelId();

		return userNotificationChannelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserNotificationChannel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserNotificationChannel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserNotificationChannel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UserNotificationChannel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, UserNotificationChannel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						UserNotificationChannel.class, ModelWrapper.class);

	}

	private String _publikUserId;
	private long _channelId;

	public <T> T getColumnValue(String columnName) {
		Function<UserNotificationChannel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserNotificationChannel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put("channelId", _channelId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("publikUserId", 1L);

		columnBitmasks.put("channelId", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserNotificationChannel _escapedModel;

}