/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.BudgetSupport;
import eu.strasbourg.service.project.model.BudgetSupportModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BudgetSupport service. Represents a row in the &quot;project_BudgetSupport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BudgetSupportModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BudgetSupportImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see BudgetSupportImpl
 * @generated
 */
@JSON(strict = true)
public class BudgetSupportModelImpl
	extends BaseModelImpl<BudgetSupport> implements BudgetSupportModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a budget support model instance should use the <code>BudgetSupport</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_BudgetSupport";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"budgetSupportId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"citoyenLastName", Types.VARCHAR}, {"citoyenFirstname", Types.VARCHAR},
		{"citoyenBirthday", Types.TIMESTAMP}, {"citoyenAddress", Types.VARCHAR},
		{"citoyenMail", Types.VARCHAR}, {"citoyenPostalCode", Types.BIGINT},
		{"citoyenMobilePhone", Types.VARCHAR}, {"citoyenPhone", Types.VARCHAR},
		{"citoyenCity", Types.VARCHAR}, {"publikUserId", Types.VARCHAR},
		{"budgetParticipatifId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budgetSupportId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("citoyenLastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenFirstname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenBirthday", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("citoyenAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenMail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenPostalCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("citoyenMobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budgetParticipatifId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_BudgetSupport (uuid_ VARCHAR(75) null,budgetSupportId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,citoyenLastName VARCHAR(75) null,citoyenFirstname VARCHAR(75) null,citoyenBirthday DATE null,citoyenAddress VARCHAR(75) null,citoyenMail VARCHAR(75) null,citoyenPostalCode LONG,citoyenMobilePhone VARCHAR(75) null,citoyenPhone VARCHAR(75) null,citoyenCity VARCHAR(75) null,publikUserId VARCHAR(75) null,budgetParticipatifId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table project_BudgetSupport";

	public static final String ORDER_BY_JPQL =
		" ORDER BY budgetSupport.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_BudgetSupport.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BUDGETPARTICIPATIFID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.BudgetSupport"));

	public BudgetSupportModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _budgetSupportId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBudgetSupportId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _budgetSupportId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BudgetSupport.class;
	}

	@Override
	public String getModelClassName() {
		return BudgetSupport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BudgetSupport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BudgetSupport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BudgetSupport, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BudgetSupport)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BudgetSupport, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BudgetSupport, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BudgetSupport)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BudgetSupport, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BudgetSupport, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BudgetSupport, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BudgetSupport, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BudgetSupport, Object>>();

			attributeGetterFunctions.put("uuid", BudgetSupport::getUuid);
			attributeGetterFunctions.put(
				"budgetSupportId", BudgetSupport::getBudgetSupportId);
			attributeGetterFunctions.put("groupId", BudgetSupport::getGroupId);
			attributeGetterFunctions.put(
				"companyId", BudgetSupport::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", BudgetSupport::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BudgetSupport::getModifiedDate);
			attributeGetterFunctions.put("status", BudgetSupport::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", BudgetSupport::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", BudgetSupport::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", BudgetSupport::getStatusDate);
			attributeGetterFunctions.put(
				"citoyenLastName", BudgetSupport::getCitoyenLastName);
			attributeGetterFunctions.put(
				"citoyenFirstname", BudgetSupport::getCitoyenFirstname);
			attributeGetterFunctions.put(
				"citoyenBirthday", BudgetSupport::getCitoyenBirthday);
			attributeGetterFunctions.put(
				"citoyenAddress", BudgetSupport::getCitoyenAddress);
			attributeGetterFunctions.put(
				"citoyenMail", BudgetSupport::getCitoyenMail);
			attributeGetterFunctions.put(
				"citoyenPostalCode", BudgetSupport::getCitoyenPostalCode);
			attributeGetterFunctions.put(
				"citoyenMobilePhone", BudgetSupport::getCitoyenMobilePhone);
			attributeGetterFunctions.put(
				"citoyenPhone", BudgetSupport::getCitoyenPhone);
			attributeGetterFunctions.put(
				"citoyenCity", BudgetSupport::getCitoyenCity);
			attributeGetterFunctions.put(
				"publikUserId", BudgetSupport::getPublikUserId);
			attributeGetterFunctions.put(
				"budgetParticipatifId", BudgetSupport::getBudgetParticipatifId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BudgetSupport, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BudgetSupport, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BudgetSupport, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BudgetSupport, String>)BudgetSupport::setUuid);
			attributeSetterBiConsumers.put(
				"budgetSupportId",
				(BiConsumer<BudgetSupport, Long>)
					BudgetSupport::setBudgetSupportId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<BudgetSupport, Long>)BudgetSupport::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BudgetSupport, Long>)BudgetSupport::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BudgetSupport, Date>)BudgetSupport::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BudgetSupport, Date>)
					BudgetSupport::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<BudgetSupport, Integer>)BudgetSupport::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<BudgetSupport, Long>)
					BudgetSupport::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<BudgetSupport, Date>)BudgetSupport::setStatusDate);
			attributeSetterBiConsumers.put(
				"citoyenLastName",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenLastName);
			attributeSetterBiConsumers.put(
				"citoyenFirstname",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenFirstname);
			attributeSetterBiConsumers.put(
				"citoyenBirthday",
				(BiConsumer<BudgetSupport, Date>)
					BudgetSupport::setCitoyenBirthday);
			attributeSetterBiConsumers.put(
				"citoyenAddress",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenAddress);
			attributeSetterBiConsumers.put(
				"citoyenMail",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenMail);
			attributeSetterBiConsumers.put(
				"citoyenPostalCode",
				(BiConsumer<BudgetSupport, Long>)
					BudgetSupport::setCitoyenPostalCode);
			attributeSetterBiConsumers.put(
				"citoyenMobilePhone",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenMobilePhone);
			attributeSetterBiConsumers.put(
				"citoyenPhone",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenPhone);
			attributeSetterBiConsumers.put(
				"citoyenCity",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setCitoyenCity);
			attributeSetterBiConsumers.put(
				"publikUserId",
				(BiConsumer<BudgetSupport, String>)
					BudgetSupport::setPublikUserId);
			attributeSetterBiConsumers.put(
				"budgetParticipatifId",
				(BiConsumer<BudgetSupport, Long>)
					BudgetSupport::setBudgetParticipatifId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBudgetSupportId() {
		return _budgetSupportId;
	}

	@Override
	public void setBudgetSupportId(long budgetSupportId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_budgetSupportId = budgetSupportId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getCitoyenLastName() {
		if (_citoyenLastName == null) {
			return "";
		}
		else {
			return _citoyenLastName;
		}
	}

	@Override
	public void setCitoyenLastName(String citoyenLastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenLastName = citoyenLastName;
	}

	@JSON
	@Override
	public String getCitoyenFirstname() {
		if (_citoyenFirstname == null) {
			return "";
		}
		else {
			return _citoyenFirstname;
		}
	}

	@Override
	public void setCitoyenFirstname(String citoyenFirstname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenFirstname = citoyenFirstname;
	}

	@JSON
	@Override
	public Date getCitoyenBirthday() {
		return _citoyenBirthday;
	}

	@Override
	public void setCitoyenBirthday(Date citoyenBirthday) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenBirthday = citoyenBirthday;
	}

	@JSON
	@Override
	public String getCitoyenAddress() {
		if (_citoyenAddress == null) {
			return "";
		}
		else {
			return _citoyenAddress;
		}
	}

	@Override
	public void setCitoyenAddress(String citoyenAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenAddress = citoyenAddress;
	}

	@JSON
	@Override
	public String getCitoyenMail() {
		if (_citoyenMail == null) {
			return "";
		}
		else {
			return _citoyenMail;
		}
	}

	@Override
	public void setCitoyenMail(String citoyenMail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenMail = citoyenMail;
	}

	@JSON
	@Override
	public long getCitoyenPostalCode() {
		return _citoyenPostalCode;
	}

	@Override
	public void setCitoyenPostalCode(long citoyenPostalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenPostalCode = citoyenPostalCode;
	}

	@JSON
	@Override
	public String getCitoyenMobilePhone() {
		if (_citoyenMobilePhone == null) {
			return "";
		}
		else {
			return _citoyenMobilePhone;
		}
	}

	@Override
	public void setCitoyenMobilePhone(String citoyenMobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenMobilePhone = citoyenMobilePhone;
	}

	@JSON
	@Override
	public String getCitoyenPhone() {
		if (_citoyenPhone == null) {
			return "";
		}
		else {
			return _citoyenPhone;
		}
	}

	@Override
	public void setCitoyenPhone(String citoyenPhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenPhone = citoyenPhone;
	}

	@JSON
	@Override
	public String getCitoyenCity() {
		if (_citoyenCity == null) {
			return "";
		}
		else {
			return _citoyenCity;
		}
	}

	@Override
	public void setCitoyenCity(String citoyenCity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_citoyenCity = citoyenCity;
	}

	@JSON
	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@JSON
	@Override
	public long getBudgetParticipatifId() {
		return _budgetParticipatifId;
	}

	@Override
	public void setBudgetParticipatifId(long budgetParticipatifId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_budgetParticipatifId = budgetParticipatifId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBudgetParticipatifId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("budgetParticipatifId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BudgetSupport.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BudgetSupport.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BudgetSupport toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BudgetSupport>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BudgetSupportImpl budgetSupportImpl = new BudgetSupportImpl();

		budgetSupportImpl.setUuid(getUuid());
		budgetSupportImpl.setBudgetSupportId(getBudgetSupportId());
		budgetSupportImpl.setGroupId(getGroupId());
		budgetSupportImpl.setCompanyId(getCompanyId());
		budgetSupportImpl.setCreateDate(getCreateDate());
		budgetSupportImpl.setModifiedDate(getModifiedDate());
		budgetSupportImpl.setStatus(getStatus());
		budgetSupportImpl.setStatusByUserId(getStatusByUserId());
		budgetSupportImpl.setStatusByUserName(getStatusByUserName());
		budgetSupportImpl.setStatusDate(getStatusDate());
		budgetSupportImpl.setCitoyenLastName(getCitoyenLastName());
		budgetSupportImpl.setCitoyenFirstname(getCitoyenFirstname());
		budgetSupportImpl.setCitoyenBirthday(getCitoyenBirthday());
		budgetSupportImpl.setCitoyenAddress(getCitoyenAddress());
		budgetSupportImpl.setCitoyenMail(getCitoyenMail());
		budgetSupportImpl.setCitoyenPostalCode(getCitoyenPostalCode());
		budgetSupportImpl.setCitoyenMobilePhone(getCitoyenMobilePhone());
		budgetSupportImpl.setCitoyenPhone(getCitoyenPhone());
		budgetSupportImpl.setCitoyenCity(getCitoyenCity());
		budgetSupportImpl.setPublikUserId(getPublikUserId());
		budgetSupportImpl.setBudgetParticipatifId(getBudgetParticipatifId());

		budgetSupportImpl.resetOriginalValues();

		return budgetSupportImpl;
	}

	@Override
	public BudgetSupport cloneWithOriginalValues() {
		BudgetSupportImpl budgetSupportImpl = new BudgetSupportImpl();

		budgetSupportImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		budgetSupportImpl.setBudgetSupportId(
			this.<Long>getColumnOriginalValue("budgetSupportId"));
		budgetSupportImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		budgetSupportImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		budgetSupportImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		budgetSupportImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		budgetSupportImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		budgetSupportImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		budgetSupportImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		budgetSupportImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		budgetSupportImpl.setCitoyenLastName(
			this.<String>getColumnOriginalValue("citoyenLastName"));
		budgetSupportImpl.setCitoyenFirstname(
			this.<String>getColumnOriginalValue("citoyenFirstname"));
		budgetSupportImpl.setCitoyenBirthday(
			this.<Date>getColumnOriginalValue("citoyenBirthday"));
		budgetSupportImpl.setCitoyenAddress(
			this.<String>getColumnOriginalValue("citoyenAddress"));
		budgetSupportImpl.setCitoyenMail(
			this.<String>getColumnOriginalValue("citoyenMail"));
		budgetSupportImpl.setCitoyenPostalCode(
			this.<Long>getColumnOriginalValue("citoyenPostalCode"));
		budgetSupportImpl.setCitoyenMobilePhone(
			this.<String>getColumnOriginalValue("citoyenMobilePhone"));
		budgetSupportImpl.setCitoyenPhone(
			this.<String>getColumnOriginalValue("citoyenPhone"));
		budgetSupportImpl.setCitoyenCity(
			this.<String>getColumnOriginalValue("citoyenCity"));
		budgetSupportImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		budgetSupportImpl.setBudgetParticipatifId(
			this.<Long>getColumnOriginalValue("budgetParticipatifId"));

		return budgetSupportImpl;
	}

	@Override
	public int compareTo(BudgetSupport budgetSupport) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), budgetSupport.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BudgetSupport)) {
			return false;
		}

		BudgetSupport budgetSupport = (BudgetSupport)object;

		long primaryKey = budgetSupport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BudgetSupport> toCacheModel() {
		BudgetSupportCacheModel budgetSupportCacheModel =
			new BudgetSupportCacheModel();

		budgetSupportCacheModel.uuid = getUuid();

		String uuid = budgetSupportCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			budgetSupportCacheModel.uuid = null;
		}

		budgetSupportCacheModel.budgetSupportId = getBudgetSupportId();

		budgetSupportCacheModel.groupId = getGroupId();

		budgetSupportCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			budgetSupportCacheModel.createDate = createDate.getTime();
		}
		else {
			budgetSupportCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			budgetSupportCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			budgetSupportCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		budgetSupportCacheModel.status = getStatus();

		budgetSupportCacheModel.statusByUserId = getStatusByUserId();

		budgetSupportCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = budgetSupportCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			budgetSupportCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			budgetSupportCacheModel.statusDate = statusDate.getTime();
		}
		else {
			budgetSupportCacheModel.statusDate = Long.MIN_VALUE;
		}

		budgetSupportCacheModel.citoyenLastName = getCitoyenLastName();

		String citoyenLastName = budgetSupportCacheModel.citoyenLastName;

		if ((citoyenLastName != null) && (citoyenLastName.length() == 0)) {
			budgetSupportCacheModel.citoyenLastName = null;
		}

		budgetSupportCacheModel.citoyenFirstname = getCitoyenFirstname();

		String citoyenFirstname = budgetSupportCacheModel.citoyenFirstname;

		if ((citoyenFirstname != null) && (citoyenFirstname.length() == 0)) {
			budgetSupportCacheModel.citoyenFirstname = null;
		}

		Date citoyenBirthday = getCitoyenBirthday();

		if (citoyenBirthday != null) {
			budgetSupportCacheModel.citoyenBirthday = citoyenBirthday.getTime();
		}
		else {
			budgetSupportCacheModel.citoyenBirthday = Long.MIN_VALUE;
		}

		budgetSupportCacheModel.citoyenAddress = getCitoyenAddress();

		String citoyenAddress = budgetSupportCacheModel.citoyenAddress;

		if ((citoyenAddress != null) && (citoyenAddress.length() == 0)) {
			budgetSupportCacheModel.citoyenAddress = null;
		}

		budgetSupportCacheModel.citoyenMail = getCitoyenMail();

		String citoyenMail = budgetSupportCacheModel.citoyenMail;

		if ((citoyenMail != null) && (citoyenMail.length() == 0)) {
			budgetSupportCacheModel.citoyenMail = null;
		}

		budgetSupportCacheModel.citoyenPostalCode = getCitoyenPostalCode();

		budgetSupportCacheModel.citoyenMobilePhone = getCitoyenMobilePhone();

		String citoyenMobilePhone = budgetSupportCacheModel.citoyenMobilePhone;

		if ((citoyenMobilePhone != null) &&
			(citoyenMobilePhone.length() == 0)) {

			budgetSupportCacheModel.citoyenMobilePhone = null;
		}

		budgetSupportCacheModel.citoyenPhone = getCitoyenPhone();

		String citoyenPhone = budgetSupportCacheModel.citoyenPhone;

		if ((citoyenPhone != null) && (citoyenPhone.length() == 0)) {
			budgetSupportCacheModel.citoyenPhone = null;
		}

		budgetSupportCacheModel.citoyenCity = getCitoyenCity();

		String citoyenCity = budgetSupportCacheModel.citoyenCity;

		if ((citoyenCity != null) && (citoyenCity.length() == 0)) {
			budgetSupportCacheModel.citoyenCity = null;
		}

		budgetSupportCacheModel.publikUserId = getPublikUserId();

		String publikUserId = budgetSupportCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			budgetSupportCacheModel.publikUserId = null;
		}

		budgetSupportCacheModel.budgetParticipatifId =
			getBudgetParticipatifId();

		return budgetSupportCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BudgetSupport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BudgetSupport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BudgetSupport, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BudgetSupport)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BudgetSupport>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BudgetSupport.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _budgetSupportId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _citoyenLastName;
	private String _citoyenFirstname;
	private Date _citoyenBirthday;
	private String _citoyenAddress;
	private String _citoyenMail;
	private long _citoyenPostalCode;
	private String _citoyenMobilePhone;
	private String _citoyenPhone;
	private String _citoyenCity;
	private String _publikUserId;
	private long _budgetParticipatifId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BudgetSupport, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BudgetSupport)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("budgetSupportId", _budgetSupportId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("citoyenLastName", _citoyenLastName);
		_columnOriginalValues.put("citoyenFirstname", _citoyenFirstname);
		_columnOriginalValues.put("citoyenBirthday", _citoyenBirthday);
		_columnOriginalValues.put("citoyenAddress", _citoyenAddress);
		_columnOriginalValues.put("citoyenMail", _citoyenMail);
		_columnOriginalValues.put("citoyenPostalCode", _citoyenPostalCode);
		_columnOriginalValues.put("citoyenMobilePhone", _citoyenMobilePhone);
		_columnOriginalValues.put("citoyenPhone", _citoyenPhone);
		_columnOriginalValues.put("citoyenCity", _citoyenCity);
		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put(
			"budgetParticipatifId", _budgetParticipatifId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("budgetSupportId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("statusByUserId", 128L);

		columnBitmasks.put("statusByUserName", 256L);

		columnBitmasks.put("statusDate", 512L);

		columnBitmasks.put("citoyenLastName", 1024L);

		columnBitmasks.put("citoyenFirstname", 2048L);

		columnBitmasks.put("citoyenBirthday", 4096L);

		columnBitmasks.put("citoyenAddress", 8192L);

		columnBitmasks.put("citoyenMail", 16384L);

		columnBitmasks.put("citoyenPostalCode", 32768L);

		columnBitmasks.put("citoyenMobilePhone", 65536L);

		columnBitmasks.put("citoyenPhone", 131072L);

		columnBitmasks.put("citoyenCity", 262144L);

		columnBitmasks.put("publikUserId", 524288L);

		columnBitmasks.put("budgetParticipatifId", 1048576L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BudgetSupport _escapedModel;

}