/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import eu.strasbourg.service.project.model.InitiativeHelp;
import eu.strasbourg.service.project.model.InitiativeHelpModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the InitiativeHelp service. Represents a row in the &quot;project_InitiativeHelp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InitiativeHelpModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InitiativeHelpImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see InitiativeHelpImpl
 * @generated
 */
@JSON(strict = true)
public class InitiativeHelpModelImpl
	extends BaseModelImpl<InitiativeHelp> implements InitiativeHelpModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a initiative help model instance should use the <code>InitiativeHelp</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_InitiativeHelp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"initiativeHelpId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"publikUserId", Types.VARCHAR},
		{"initiativeId", Types.BIGINT}, {"helpTypes", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"message", Types.VARCHAR},
		{"helpDisplay", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("initiativeHelpId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("initiativeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("helpTypes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("helpDisplay", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_InitiativeHelp (uuid_ VARCHAR(75) null,initiativeHelpId LONG not null primary key,createDate DATE null,publikUserId VARCHAR(75) null,initiativeId LONG,helpTypes VARCHAR(75) null,groupId LONG,message STRING null,helpDisplay BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table project_InitiativeHelp";

	public static final String ORDER_BY_JPQL =
		" ORDER BY initiativeHelp.initiativeHelpId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_InitiativeHelp.initiativeHelpId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INITIATIVEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INITIATIVEHELPID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.InitiativeHelp"));

	public InitiativeHelpModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _initiativeHelpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInitiativeHelpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _initiativeHelpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InitiativeHelp.class;
	}

	@Override
	public String getModelClassName() {
		return InitiativeHelp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InitiativeHelp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InitiativeHelp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InitiativeHelp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InitiativeHelp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InitiativeHelp, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InitiativeHelp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InitiativeHelp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InitiativeHelp, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InitiativeHelp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<InitiativeHelp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<InitiativeHelp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<InitiativeHelp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<InitiativeHelp, Object>>();
		Map<String, BiConsumer<InitiativeHelp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<InitiativeHelp, ?>>();

		attributeGetterFunctions.put("uuid", InitiativeHelp::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<InitiativeHelp, String>)InitiativeHelp::setUuid);
		attributeGetterFunctions.put(
			"initiativeHelpId", InitiativeHelp::getInitiativeHelpId);
		attributeSetterBiConsumers.put(
			"initiativeHelpId",
			(BiConsumer<InitiativeHelp, Long>)
				InitiativeHelp::setInitiativeHelpId);
		attributeGetterFunctions.put(
			"createDate", InitiativeHelp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<InitiativeHelp, Date>)InitiativeHelp::setCreateDate);
		attributeGetterFunctions.put(
			"publikUserId", InitiativeHelp::getPublikUserId);
		attributeSetterBiConsumers.put(
			"publikUserId",
			(BiConsumer<InitiativeHelp, String>)
				InitiativeHelp::setPublikUserId);
		attributeGetterFunctions.put(
			"initiativeId", InitiativeHelp::getInitiativeId);
		attributeSetterBiConsumers.put(
			"initiativeId",
			(BiConsumer<InitiativeHelp, Long>)InitiativeHelp::setInitiativeId);
		attributeGetterFunctions.put("helpTypes", InitiativeHelp::getHelpTypes);
		attributeSetterBiConsumers.put(
			"helpTypes",
			(BiConsumer<InitiativeHelp, String>)InitiativeHelp::setHelpTypes);
		attributeGetterFunctions.put("groupId", InitiativeHelp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<InitiativeHelp, Long>)InitiativeHelp::setGroupId);
		attributeGetterFunctions.put("message", InitiativeHelp::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<InitiativeHelp, String>)InitiativeHelp::setMessage);
		attributeGetterFunctions.put(
			"helpDisplay", InitiativeHelp::getHelpDisplay);
		attributeSetterBiConsumers.put(
			"helpDisplay",
			(BiConsumer<InitiativeHelp, Boolean>)
				InitiativeHelp::setHelpDisplay);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getInitiativeHelpId() {
		return _initiativeHelpId;
	}

	@Override
	public void setInitiativeHelpId(long initiativeHelpId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_initiativeHelpId = initiativeHelpId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@JSON
	@Override
	public long getInitiativeId() {
		return _initiativeId;
	}

	@Override
	public void setInitiativeId(long initiativeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_initiativeId = initiativeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalInitiativeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("initiativeId"));
	}

	@JSON
	@Override
	public String getHelpTypes() {
		if (_helpTypes == null) {
			return "";
		}
		else {
			return _helpTypes;
		}
	}

	@Override
	public void setHelpTypes(String helpTypes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_helpTypes = helpTypes;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public String getMessage(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getMessage(languageId);
	}

	@Override
	public String getMessage(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getMessage(languageId, useDefault);
	}

	@Override
	public String getMessage(String languageId) {
		return LocalizationUtil.getLocalization(getMessage(), languageId);
	}

	@Override
	public String getMessage(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getMessage(), languageId, useDefault);
	}

	@Override
	public String getMessageCurrentLanguageId() {
		return _messageCurrentLanguageId;
	}

	@JSON
	@Override
	public String getMessageCurrentValue() {
		Locale locale = getLocale(_messageCurrentLanguageId);

		return getMessage(locale);
	}

	@Override
	public Map<Locale, String> getMessageMap() {
		return LocalizationUtil.getLocalizationMap(getMessage());
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@Override
	public void setMessage(String message, Locale locale) {
		setMessage(message, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setMessage(
		String message, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(message)) {
			setMessage(
				LocalizationUtil.updateLocalization(
					getMessage(), "Message", message, languageId,
					defaultLanguageId));
		}
		else {
			setMessage(
				LocalizationUtil.removeLocalization(
					getMessage(), "Message", languageId));
		}
	}

	@Override
	public void setMessageCurrentLanguageId(String languageId) {
		_messageCurrentLanguageId = languageId;
	}

	@Override
	public void setMessageMap(Map<Locale, String> messageMap) {
		setMessageMap(messageMap, LocaleUtil.getDefault());
	}

	@Override
	public void setMessageMap(
		Map<Locale, String> messageMap, Locale defaultLocale) {

		if (messageMap == null) {
			return;
		}

		setMessage(
			LocalizationUtil.updateLocalization(
				messageMap, getMessage(), "Message",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public boolean getHelpDisplay() {
		return _helpDisplay;
	}

	@JSON
	@Override
	public boolean isHelpDisplay() {
		return _helpDisplay;
	}

	@Override
	public void setHelpDisplay(boolean helpDisplay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_helpDisplay = helpDisplay;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, InitiativeHelp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> messageMap = getMessageMap();

		for (Map.Entry<Locale, String> entry : messageMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getMessage();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			InitiativeHelp.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String message = getMessage(defaultLocale);

		if (Validator.isNull(message)) {
			setMessage(getMessage(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setMessage(getMessage(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public InitiativeHelp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InitiativeHelp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InitiativeHelpImpl initiativeHelpImpl = new InitiativeHelpImpl();

		initiativeHelpImpl.setUuid(getUuid());
		initiativeHelpImpl.setInitiativeHelpId(getInitiativeHelpId());
		initiativeHelpImpl.setCreateDate(getCreateDate());
		initiativeHelpImpl.setPublikUserId(getPublikUserId());
		initiativeHelpImpl.setInitiativeId(getInitiativeId());
		initiativeHelpImpl.setHelpTypes(getHelpTypes());
		initiativeHelpImpl.setGroupId(getGroupId());
		initiativeHelpImpl.setMessage(getMessage());
		initiativeHelpImpl.setHelpDisplay(isHelpDisplay());

		initiativeHelpImpl.resetOriginalValues();

		return initiativeHelpImpl;
	}

	@Override
	public InitiativeHelp cloneWithOriginalValues() {
		InitiativeHelpImpl initiativeHelpImpl = new InitiativeHelpImpl();

		initiativeHelpImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		initiativeHelpImpl.setInitiativeHelpId(
			this.<Long>getColumnOriginalValue("initiativeHelpId"));
		initiativeHelpImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		initiativeHelpImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		initiativeHelpImpl.setInitiativeId(
			this.<Long>getColumnOriginalValue("initiativeId"));
		initiativeHelpImpl.setHelpTypes(
			this.<String>getColumnOriginalValue("helpTypes"));
		initiativeHelpImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		initiativeHelpImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));
		initiativeHelpImpl.setHelpDisplay(
			this.<Boolean>getColumnOriginalValue("helpDisplay"));

		return initiativeHelpImpl;
	}

	@Override
	public int compareTo(InitiativeHelp initiativeHelp) {
		long primaryKey = initiativeHelp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof InitiativeHelp)) {
			return false;
		}

		InitiativeHelp initiativeHelp = (InitiativeHelp)object;

		long primaryKey = initiativeHelp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<InitiativeHelp> toCacheModel() {
		InitiativeHelpCacheModel initiativeHelpCacheModel =
			new InitiativeHelpCacheModel();

		initiativeHelpCacheModel.uuid = getUuid();

		String uuid = initiativeHelpCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			initiativeHelpCacheModel.uuid = null;
		}

		initiativeHelpCacheModel.initiativeHelpId = getInitiativeHelpId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			initiativeHelpCacheModel.createDate = createDate.getTime();
		}
		else {
			initiativeHelpCacheModel.createDate = Long.MIN_VALUE;
		}

		initiativeHelpCacheModel.publikUserId = getPublikUserId();

		String publikUserId = initiativeHelpCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			initiativeHelpCacheModel.publikUserId = null;
		}

		initiativeHelpCacheModel.initiativeId = getInitiativeId();

		initiativeHelpCacheModel.helpTypes = getHelpTypes();

		String helpTypes = initiativeHelpCacheModel.helpTypes;

		if ((helpTypes != null) && (helpTypes.length() == 0)) {
			initiativeHelpCacheModel.helpTypes = null;
		}

		initiativeHelpCacheModel.groupId = getGroupId();

		initiativeHelpCacheModel.message = getMessage();

		String message = initiativeHelpCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			initiativeHelpCacheModel.message = null;
		}

		initiativeHelpCacheModel.helpDisplay = isHelpDisplay();

		return initiativeHelpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InitiativeHelp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InitiativeHelp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InitiativeHelp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((InitiativeHelp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InitiativeHelp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					InitiativeHelp.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _initiativeHelpId;
	private Date _createDate;
	private String _publikUserId;
	private long _initiativeId;
	private String _helpTypes;
	private long _groupId;
	private String _message;
	private String _messageCurrentLanguageId;
	private boolean _helpDisplay;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<InitiativeHelp, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((InitiativeHelp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("initiativeHelpId", _initiativeHelpId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put("initiativeId", _initiativeId);
		_columnOriginalValues.put("helpTypes", _helpTypes);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("helpDisplay", _helpDisplay);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("initiativeHelpId", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("publikUserId", 8L);

		columnBitmasks.put("initiativeId", 16L);

		columnBitmasks.put("helpTypes", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("message", 128L);

		columnBitmasks.put("helpDisplay", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private InitiativeHelp _escapedModel;

}