/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.Participation;
import eu.strasbourg.service.project.model.ParticipationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Participation service. Represents a row in the &quot;project_Participation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParticipationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParticipationImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see ParticipationImpl
 * @generated
 */
@JSON(strict = true)
public class ParticipationModelImpl
	extends BaseModelImpl<Participation> implements ParticipationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a participation model instance should use the <code>Participation</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_Participation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"participationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"contactName", Types.VARCHAR},
		{"contactLine1", Types.VARCHAR}, {"contactLine2", Types.VARCHAR},
		{"contactPhoneNumber", Types.VARCHAR}, {"videoUrl", Types.VARCHAR},
		{"externalImageURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"mediaChoice", Types.BOOLEAN}, {"descriptionChapeau", Types.VARCHAR},
		{"descriptionBody", Types.CLOB}, {"consultationPlacesBody", Types.CLOB},
		{"imageId", Types.BIGINT}, {"filesIds", Types.VARCHAR},
		{"eventsIds", Types.VARCHAR}, {"publicationDate", Types.TIMESTAMP},
		{"expirationDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("participationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactPhoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("videoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mediaChoice", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("descriptionChapeau", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descriptionBody", Types.CLOB);
		TABLE_COLUMNS_MAP.put("consultationPlacesBody", Types.CLOB);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("filesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventsIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_Participation (uuid_ VARCHAR(75) null,participationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,contactName VARCHAR(75) null,contactLine1 VARCHAR(400) null,contactLine2 VARCHAR(400) null,contactPhoneNumber VARCHAR(75) null,videoUrl VARCHAR(400) null,externalImageURL VARCHAR(400) null,externalImageCopyright VARCHAR(400) null,mediaChoice BOOLEAN,descriptionChapeau VARCHAR(400) null,descriptionBody TEXT null,consultationPlacesBody TEXT null,imageId LONG,filesIds VARCHAR(400) null,eventsIds VARCHAR(75) null,publicationDate DATE null,expirationDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table project_Participation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY participation.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_Participation.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.Participation"));

	public ParticipationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _participationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParticipationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _participationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Participation.class;
	}

	@Override
	public String getModelClassName() {
		return Participation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Participation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Participation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Participation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Participation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Participation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Participation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Participation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Participation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Participation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Participation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Participation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Participation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Participation, Object>>();
		Map<String, BiConsumer<Participation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Participation, ?>>();

		attributeGetterFunctions.put("uuid", Participation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Participation, String>)Participation::setUuid);
		attributeGetterFunctions.put(
			"participationId", Participation::getParticipationId);
		attributeSetterBiConsumers.put(
			"participationId",
			(BiConsumer<Participation, Long>)Participation::setParticipationId);
		attributeGetterFunctions.put("groupId", Participation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<Participation, Long>)Participation::setGroupId);
		attributeGetterFunctions.put("companyId", Participation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Participation, Long>)Participation::setCompanyId);
		attributeGetterFunctions.put("userId", Participation::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<Participation, Long>)Participation::setUserId);
		attributeGetterFunctions.put("userName", Participation::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Participation, String>)Participation::setUserName);
		attributeGetterFunctions.put(
			"createDate", Participation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Participation, Date>)Participation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Participation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Participation, Date>)Participation::setModifiedDate);
		attributeGetterFunctions.put("status", Participation::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<Participation, Integer>)Participation::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Participation::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Participation, Long>)Participation::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Participation::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Participation, String>)
				Participation::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", Participation::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<Participation, Date>)Participation::setStatusDate);
		attributeGetterFunctions.put("title", Participation::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<Participation, String>)Participation::setTitle);
		attributeGetterFunctions.put(
			"contactName", Participation::getContactName);
		attributeSetterBiConsumers.put(
			"contactName",
			(BiConsumer<Participation, String>)Participation::setContactName);
		attributeGetterFunctions.put(
			"contactLine1", Participation::getContactLine1);
		attributeSetterBiConsumers.put(
			"contactLine1",
			(BiConsumer<Participation, String>)Participation::setContactLine1);
		attributeGetterFunctions.put(
			"contactLine2", Participation::getContactLine2);
		attributeSetterBiConsumers.put(
			"contactLine2",
			(BiConsumer<Participation, String>)Participation::setContactLine2);
		attributeGetterFunctions.put(
			"contactPhoneNumber", Participation::getContactPhoneNumber);
		attributeSetterBiConsumers.put(
			"contactPhoneNumber",
			(BiConsumer<Participation, String>)
				Participation::setContactPhoneNumber);
		attributeGetterFunctions.put("videoUrl", Participation::getVideoUrl);
		attributeSetterBiConsumers.put(
			"videoUrl",
			(BiConsumer<Participation, String>)Participation::setVideoUrl);
		attributeGetterFunctions.put(
			"externalImageURL", Participation::getExternalImageURL);
		attributeSetterBiConsumers.put(
			"externalImageURL",
			(BiConsumer<Participation, String>)
				Participation::setExternalImageURL);
		attributeGetterFunctions.put(
			"externalImageCopyright", Participation::getExternalImageCopyright);
		attributeSetterBiConsumers.put(
			"externalImageCopyright",
			(BiConsumer<Participation, String>)
				Participation::setExternalImageCopyright);
		attributeGetterFunctions.put(
			"mediaChoice", Participation::getMediaChoice);
		attributeSetterBiConsumers.put(
			"mediaChoice",
			(BiConsumer<Participation, Boolean>)Participation::setMediaChoice);
		attributeGetterFunctions.put(
			"descriptionChapeau", Participation::getDescriptionChapeau);
		attributeSetterBiConsumers.put(
			"descriptionChapeau",
			(BiConsumer<Participation, String>)
				Participation::setDescriptionChapeau);
		attributeGetterFunctions.put(
			"descriptionBody", Participation::getDescriptionBody);
		attributeSetterBiConsumers.put(
			"descriptionBody",
			(BiConsumer<Participation, String>)
				Participation::setDescriptionBody);
		attributeGetterFunctions.put(
			"consultationPlacesBody", Participation::getConsultationPlacesBody);
		attributeSetterBiConsumers.put(
			"consultationPlacesBody",
			(BiConsumer<Participation, String>)
				Participation::setConsultationPlacesBody);
		attributeGetterFunctions.put("imageId", Participation::getImageId);
		attributeSetterBiConsumers.put(
			"imageId",
			(BiConsumer<Participation, Long>)Participation::setImageId);
		attributeGetterFunctions.put("filesIds", Participation::getFilesIds);
		attributeSetterBiConsumers.put(
			"filesIds",
			(BiConsumer<Participation, String>)Participation::setFilesIds);
		attributeGetterFunctions.put("eventsIds", Participation::getEventsIds);
		attributeSetterBiConsumers.put(
			"eventsIds",
			(BiConsumer<Participation, String>)Participation::setEventsIds);
		attributeGetterFunctions.put(
			"publicationDate", Participation::getPublicationDate);
		attributeSetterBiConsumers.put(
			"publicationDate",
			(BiConsumer<Participation, Date>)Participation::setPublicationDate);
		attributeGetterFunctions.put(
			"expirationDate", Participation::getExpirationDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<Participation, Date>)Participation::setExpirationDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getParticipationId() {
		return _participationId;
	}

	@Override
	public void setParticipationId(long participationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_participationId = participationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getContactName() {
		if (_contactName == null) {
			return "";
		}
		else {
			return _contactName;
		}
	}

	@Override
	public void setContactName(String contactName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactName = contactName;
	}

	@JSON
	@Override
	public String getContactLine1() {
		if (_contactLine1 == null) {
			return "";
		}
		else {
			return _contactLine1;
		}
	}

	@Override
	public void setContactLine1(String contactLine1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactLine1 = contactLine1;
	}

	@JSON
	@Override
	public String getContactLine2() {
		if (_contactLine2 == null) {
			return "";
		}
		else {
			return _contactLine2;
		}
	}

	@Override
	public void setContactLine2(String contactLine2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactLine2 = contactLine2;
	}

	@JSON
	@Override
	public String getContactPhoneNumber() {
		if (_contactPhoneNumber == null) {
			return "";
		}
		else {
			return _contactPhoneNumber;
		}
	}

	@Override
	public void setContactPhoneNumber(String contactPhoneNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactPhoneNumber = contactPhoneNumber;
	}

	@JSON
	@Override
	public String getVideoUrl() {
		if (_videoUrl == null) {
			return "";
		}
		else {
			return _videoUrl;
		}
	}

	@Override
	public void setVideoUrl(String videoUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_videoUrl = videoUrl;
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public boolean getMediaChoice() {
		return _mediaChoice;
	}

	@JSON
	@Override
	public boolean isMediaChoice() {
		return _mediaChoice;
	}

	@Override
	public void setMediaChoice(boolean mediaChoice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mediaChoice = mediaChoice;
	}

	@JSON
	@Override
	public String getDescriptionChapeau() {
		if (_descriptionChapeau == null) {
			return "";
		}
		else {
			return _descriptionChapeau;
		}
	}

	@Override
	public void setDescriptionChapeau(String descriptionChapeau) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descriptionChapeau = descriptionChapeau;
	}

	@JSON
	@Override
	public String getDescriptionBody() {
		if (_descriptionBody == null) {
			return "";
		}
		else {
			return _descriptionBody;
		}
	}

	@Override
	public void setDescriptionBody(String descriptionBody) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descriptionBody = descriptionBody;
	}

	@JSON
	@Override
	public String getConsultationPlacesBody() {
		if (_consultationPlacesBody == null) {
			return "";
		}
		else {
			return _consultationPlacesBody;
		}
	}

	@Override
	public void setConsultationPlacesBody(String consultationPlacesBody) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_consultationPlacesBody = consultationPlacesBody;
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@JSON
	@Override
	public String getFilesIds() {
		if (_filesIds == null) {
			return "";
		}
		else {
			return _filesIds;
		}
	}

	@Override
	public void setFilesIds(String filesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filesIds = filesIds;
	}

	@JSON
	@Override
	public String getEventsIds() {
		if (_eventsIds == null) {
			return "";
		}
		else {
			return _eventsIds;
		}
	}

	@Override
	public void setEventsIds(String eventsIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventsIds = eventsIds;
	}

	@JSON
	@Override
	public Date getPublicationDate() {
		return _publicationDate;
	}

	@Override
	public void setPublicationDate(Date publicationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicationDate = publicationDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Participation.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Participation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Participation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Participation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParticipationImpl participationImpl = new ParticipationImpl();

		participationImpl.setUuid(getUuid());
		participationImpl.setParticipationId(getParticipationId());
		participationImpl.setGroupId(getGroupId());
		participationImpl.setCompanyId(getCompanyId());
		participationImpl.setUserId(getUserId());
		participationImpl.setUserName(getUserName());
		participationImpl.setCreateDate(getCreateDate());
		participationImpl.setModifiedDate(getModifiedDate());
		participationImpl.setStatus(getStatus());
		participationImpl.setStatusByUserId(getStatusByUserId());
		participationImpl.setStatusByUserName(getStatusByUserName());
		participationImpl.setStatusDate(getStatusDate());
		participationImpl.setTitle(getTitle());
		participationImpl.setContactName(getContactName());
		participationImpl.setContactLine1(getContactLine1());
		participationImpl.setContactLine2(getContactLine2());
		participationImpl.setContactPhoneNumber(getContactPhoneNumber());
		participationImpl.setVideoUrl(getVideoUrl());
		participationImpl.setExternalImageURL(getExternalImageURL());
		participationImpl.setExternalImageCopyright(
			getExternalImageCopyright());
		participationImpl.setMediaChoice(isMediaChoice());
		participationImpl.setDescriptionChapeau(getDescriptionChapeau());
		participationImpl.setDescriptionBody(getDescriptionBody());
		participationImpl.setConsultationPlacesBody(
			getConsultationPlacesBody());
		participationImpl.setImageId(getImageId());
		participationImpl.setFilesIds(getFilesIds());
		participationImpl.setEventsIds(getEventsIds());
		participationImpl.setPublicationDate(getPublicationDate());
		participationImpl.setExpirationDate(getExpirationDate());

		participationImpl.resetOriginalValues();

		return participationImpl;
	}

	@Override
	public Participation cloneWithOriginalValues() {
		ParticipationImpl participationImpl = new ParticipationImpl();

		participationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		participationImpl.setParticipationId(
			this.<Long>getColumnOriginalValue("participationId"));
		participationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		participationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		participationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		participationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		participationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		participationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		participationImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		participationImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		participationImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		participationImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		participationImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		participationImpl.setContactName(
			this.<String>getColumnOriginalValue("contactName"));
		participationImpl.setContactLine1(
			this.<String>getColumnOriginalValue("contactLine1"));
		participationImpl.setContactLine2(
			this.<String>getColumnOriginalValue("contactLine2"));
		participationImpl.setContactPhoneNumber(
			this.<String>getColumnOriginalValue("contactPhoneNumber"));
		participationImpl.setVideoUrl(
			this.<String>getColumnOriginalValue("videoUrl"));
		participationImpl.setExternalImageURL(
			this.<String>getColumnOriginalValue("externalImageURL"));
		participationImpl.setExternalImageCopyright(
			this.<String>getColumnOriginalValue("externalImageCopyright"));
		participationImpl.setMediaChoice(
			this.<Boolean>getColumnOriginalValue("mediaChoice"));
		participationImpl.setDescriptionChapeau(
			this.<String>getColumnOriginalValue("descriptionChapeau"));
		participationImpl.setDescriptionBody(
			this.<String>getColumnOriginalValue("descriptionBody"));
		participationImpl.setConsultationPlacesBody(
			this.<String>getColumnOriginalValue("consultationPlacesBody"));
		participationImpl.setImageId(
			this.<Long>getColumnOriginalValue("imageId"));
		participationImpl.setFilesIds(
			this.<String>getColumnOriginalValue("filesIds"));
		participationImpl.setEventsIds(
			this.<String>getColumnOriginalValue("eventsIds"));
		participationImpl.setPublicationDate(
			this.<Date>getColumnOriginalValue("publicationDate"));
		participationImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));

		return participationImpl;
	}

	@Override
	public int compareTo(Participation participation) {
		int value = 0;

		value = getTitle().compareTo(participation.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Participation)) {
			return false;
		}

		Participation participation = (Participation)object;

		long primaryKey = participation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Participation> toCacheModel() {
		ParticipationCacheModel participationCacheModel =
			new ParticipationCacheModel();

		participationCacheModel.uuid = getUuid();

		String uuid = participationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			participationCacheModel.uuid = null;
		}

		participationCacheModel.participationId = getParticipationId();

		participationCacheModel.groupId = getGroupId();

		participationCacheModel.companyId = getCompanyId();

		participationCacheModel.userId = getUserId();

		participationCacheModel.userName = getUserName();

		String userName = participationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			participationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			participationCacheModel.createDate = createDate.getTime();
		}
		else {
			participationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			participationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			participationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		participationCacheModel.status = getStatus();

		participationCacheModel.statusByUserId = getStatusByUserId();

		participationCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = participationCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			participationCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			participationCacheModel.statusDate = statusDate.getTime();
		}
		else {
			participationCacheModel.statusDate = Long.MIN_VALUE;
		}

		participationCacheModel.title = getTitle();

		String title = participationCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			participationCacheModel.title = null;
		}

		participationCacheModel.contactName = getContactName();

		String contactName = participationCacheModel.contactName;

		if ((contactName != null) && (contactName.length() == 0)) {
			participationCacheModel.contactName = null;
		}

		participationCacheModel.contactLine1 = getContactLine1();

		String contactLine1 = participationCacheModel.contactLine1;

		if ((contactLine1 != null) && (contactLine1.length() == 0)) {
			participationCacheModel.contactLine1 = null;
		}

		participationCacheModel.contactLine2 = getContactLine2();

		String contactLine2 = participationCacheModel.contactLine2;

		if ((contactLine2 != null) && (contactLine2.length() == 0)) {
			participationCacheModel.contactLine2 = null;
		}

		participationCacheModel.contactPhoneNumber = getContactPhoneNumber();

		String contactPhoneNumber = participationCacheModel.contactPhoneNumber;

		if ((contactPhoneNumber != null) &&
			(contactPhoneNumber.length() == 0)) {

			participationCacheModel.contactPhoneNumber = null;
		}

		participationCacheModel.videoUrl = getVideoUrl();

		String videoUrl = participationCacheModel.videoUrl;

		if ((videoUrl != null) && (videoUrl.length() == 0)) {
			participationCacheModel.videoUrl = null;
		}

		participationCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL = participationCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			participationCacheModel.externalImageURL = null;
		}

		participationCacheModel.externalImageCopyright =
			getExternalImageCopyright();

		String externalImageCopyright =
			participationCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			participationCacheModel.externalImageCopyright = null;
		}

		participationCacheModel.mediaChoice = isMediaChoice();

		participationCacheModel.descriptionChapeau = getDescriptionChapeau();

		String descriptionChapeau = participationCacheModel.descriptionChapeau;

		if ((descriptionChapeau != null) &&
			(descriptionChapeau.length() == 0)) {

			participationCacheModel.descriptionChapeau = null;
		}

		participationCacheModel.descriptionBody = getDescriptionBody();

		String descriptionBody = participationCacheModel.descriptionBody;

		if ((descriptionBody != null) && (descriptionBody.length() == 0)) {
			participationCacheModel.descriptionBody = null;
		}

		participationCacheModel.consultationPlacesBody =
			getConsultationPlacesBody();

		String consultationPlacesBody =
			participationCacheModel.consultationPlacesBody;

		if ((consultationPlacesBody != null) &&
			(consultationPlacesBody.length() == 0)) {

			participationCacheModel.consultationPlacesBody = null;
		}

		participationCacheModel.imageId = getImageId();

		participationCacheModel.filesIds = getFilesIds();

		String filesIds = participationCacheModel.filesIds;

		if ((filesIds != null) && (filesIds.length() == 0)) {
			participationCacheModel.filesIds = null;
		}

		participationCacheModel.eventsIds = getEventsIds();

		String eventsIds = participationCacheModel.eventsIds;

		if ((eventsIds != null) && (eventsIds.length() == 0)) {
			participationCacheModel.eventsIds = null;
		}

		Date publicationDate = getPublicationDate();

		if (publicationDate != null) {
			participationCacheModel.publicationDate = publicationDate.getTime();
		}
		else {
			participationCacheModel.publicationDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			participationCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			participationCacheModel.expirationDate = Long.MIN_VALUE;
		}

		return participationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Participation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Participation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Participation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Participation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Participation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Participation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _participationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _contactName;
	private String _contactLine1;
	private String _contactLine2;
	private String _contactPhoneNumber;
	private String _videoUrl;
	private String _externalImageURL;
	private String _externalImageCopyright;
	private boolean _mediaChoice;
	private String _descriptionChapeau;
	private String _descriptionBody;
	private String _consultationPlacesBody;
	private long _imageId;
	private String _filesIds;
	private String _eventsIds;
	private Date _publicationDate;
	private Date _expirationDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Participation, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Participation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("participationId", _participationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("contactName", _contactName);
		_columnOriginalValues.put("contactLine1", _contactLine1);
		_columnOriginalValues.put("contactLine2", _contactLine2);
		_columnOriginalValues.put("contactPhoneNumber", _contactPhoneNumber);
		_columnOriginalValues.put("videoUrl", _videoUrl);
		_columnOriginalValues.put("externalImageURL", _externalImageURL);
		_columnOriginalValues.put(
			"externalImageCopyright", _externalImageCopyright);
		_columnOriginalValues.put("mediaChoice", _mediaChoice);
		_columnOriginalValues.put("descriptionChapeau", _descriptionChapeau);
		_columnOriginalValues.put("descriptionBody", _descriptionBody);
		_columnOriginalValues.put(
			"consultationPlacesBody", _consultationPlacesBody);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("filesIds", _filesIds);
		_columnOriginalValues.put("eventsIds", _eventsIds);
		_columnOriginalValues.put("publicationDate", _publicationDate);
		_columnOriginalValues.put("expirationDate", _expirationDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("participationId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("title", 4096L);

		columnBitmasks.put("contactName", 8192L);

		columnBitmasks.put("contactLine1", 16384L);

		columnBitmasks.put("contactLine2", 32768L);

		columnBitmasks.put("contactPhoneNumber", 65536L);

		columnBitmasks.put("videoUrl", 131072L);

		columnBitmasks.put("externalImageURL", 262144L);

		columnBitmasks.put("externalImageCopyright", 524288L);

		columnBitmasks.put("mediaChoice", 1048576L);

		columnBitmasks.put("descriptionChapeau", 2097152L);

		columnBitmasks.put("descriptionBody", 4194304L);

		columnBitmasks.put("consultationPlacesBody", 8388608L);

		columnBitmasks.put("imageId", 16777216L);

		columnBitmasks.put("filesIds", 33554432L);

		columnBitmasks.put("eventsIds", 67108864L);

		columnBitmasks.put("publicationDate", 134217728L);

		columnBitmasks.put("expirationDate", 268435456L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Participation _escapedModel;

}