/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.Petition;
import eu.strasbourg.service.project.model.PetitionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Petition service. Represents a row in the &quot;project_Petition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PetitionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PetitionImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see PetitionImpl
 * @generated
 */
@JSON(strict = true)
public class PetitionModelImpl
	extends BaseModelImpl<Petition> implements PetitionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a petition model instance should use the <code>Petition</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_Petition";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"petitionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"summary", Types.VARCHAR},
		{"description", Types.CLOB}, {"placeTextArea", Types.VARCHAR},
		{"filesDownload", Types.VARCHAR}, {"publicationDate", Types.TIMESTAMP},
		{"expirationDate", Types.TIMESTAMP}, {"extensionDate", Types.TIMESTAMP},
		{"quotaSignature", Types.BIGINT}, {"inTheNameOf", Types.VARCHAR},
		{"petitionnaireLastname", Types.VARCHAR},
		{"petitionnaireFirstname", Types.VARCHAR},
		{"petitionnaireBirthday", Types.TIMESTAMP},
		{"petitionnaireAdresse", Types.VARCHAR},
		{"petitionnairePostalCode", Types.BIGINT},
		{"petitionnaireCity", Types.VARCHAR},
		{"petitionnairePhone", Types.VARCHAR},
		{"petitionnaireEmail", Types.VARCHAR}, {"isSupported", Types.BOOLEAN},
		{"supportedBy", Types.VARCHAR}, {"videoUrl", Types.VARCHAR},
		{"externalImageURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"mediaChoice", Types.BOOLEAN}, {"publikId", Types.VARCHAR},
		{"imageId", Types.BIGINT}, {"filesIds", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("summary", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("placeTextArea", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filesDownload", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("extensionDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("quotaSignature", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inTheNameOf", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireLastname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireFirstname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireBirthday", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("petitionnaireAdresse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnairePostalCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("petitionnaireCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnairePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isSupported", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("supportedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("videoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mediaChoice", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("publikId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("filesIds", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_Petition (uuid_ VARCHAR(75) null,petitionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,summary VARCHAR(500) null,description TEXT null,placeTextArea VARCHAR(400) null,filesDownload VARCHAR(75) null,publicationDate DATE null,expirationDate DATE null,extensionDate DATE null,quotaSignature LONG,inTheNameOf VARCHAR(400) null,petitionnaireLastname VARCHAR(75) null,petitionnaireFirstname VARCHAR(75) null,petitionnaireBirthday DATE null,petitionnaireAdresse VARCHAR(400) null,petitionnairePostalCode LONG,petitionnaireCity VARCHAR(400) null,petitionnairePhone VARCHAR(75) null,petitionnaireEmail VARCHAR(400) null,isSupported BOOLEAN,supportedBy VARCHAR(75) null,videoUrl VARCHAR(400) null,externalImageURL VARCHAR(400) null,externalImageCopyright VARCHAR(75) null,mediaChoice BOOLEAN,publikId VARCHAR(75) null,imageId LONG,filesIds VARCHAR(400) null)";

	public static final String TABLE_SQL_DROP = "drop table project_Petition";

	public static final String ORDER_BY_JPQL = " ORDER BY petition.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_Petition.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.Petition"));

	public PetitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _petitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPetitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _petitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Petition.class;
	}

	@Override
	public String getModelClassName() {
		return Petition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Petition, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Petition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Petition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Petition)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Petition, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Petition, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Petition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Petition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Petition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Petition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Petition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Petition, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Petition, Object>>();
		Map<String, BiConsumer<Petition, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Petition, ?>>();

		attributeGetterFunctions.put("uuid", Petition::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Petition, String>)Petition::setUuid);
		attributeGetterFunctions.put("petitionId", Petition::getPetitionId);
		attributeSetterBiConsumers.put(
			"petitionId", (BiConsumer<Petition, Long>)Petition::setPetitionId);
		attributeGetterFunctions.put("groupId", Petition::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Petition, Long>)Petition::setGroupId);
		attributeGetterFunctions.put("companyId", Petition::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Petition, Long>)Petition::setCompanyId);
		attributeGetterFunctions.put("userId", Petition::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Petition, Long>)Petition::setUserId);
		attributeGetterFunctions.put("userName", Petition::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Petition, String>)Petition::setUserName);
		attributeGetterFunctions.put("createDate", Petition::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Petition, Date>)Petition::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Petition::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Petition, Date>)Petition::setModifiedDate);
		attributeGetterFunctions.put("status", Petition::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Petition, Integer>)Petition::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Petition::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Petition, Long>)Petition::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Petition::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Petition, String>)Petition::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Petition::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Petition, Date>)Petition::setStatusDate);
		attributeGetterFunctions.put("title", Petition::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Petition, String>)Petition::setTitle);
		attributeGetterFunctions.put("summary", Petition::getSummary);
		attributeSetterBiConsumers.put(
			"summary", (BiConsumer<Petition, String>)Petition::setSummary);
		attributeGetterFunctions.put("description", Petition::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Petition, String>)Petition::setDescription);
		attributeGetterFunctions.put(
			"placeTextArea", Petition::getPlaceTextArea);
		attributeSetterBiConsumers.put(
			"placeTextArea",
			(BiConsumer<Petition, String>)Petition::setPlaceTextArea);
		attributeGetterFunctions.put(
			"filesDownload", Petition::getFilesDownload);
		attributeSetterBiConsumers.put(
			"filesDownload",
			(BiConsumer<Petition, String>)Petition::setFilesDownload);
		attributeGetterFunctions.put(
			"publicationDate", Petition::getPublicationDate);
		attributeSetterBiConsumers.put(
			"publicationDate",
			(BiConsumer<Petition, Date>)Petition::setPublicationDate);
		attributeGetterFunctions.put(
			"expirationDate", Petition::getExpirationDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<Petition, Date>)Petition::setExpirationDate);
		attributeGetterFunctions.put(
			"extensionDate", Petition::getExtensionDate);
		attributeSetterBiConsumers.put(
			"extensionDate",
			(BiConsumer<Petition, Date>)Petition::setExtensionDate);
		attributeGetterFunctions.put(
			"quotaSignature", Petition::getQuotaSignature);
		attributeSetterBiConsumers.put(
			"quotaSignature",
			(BiConsumer<Petition, Long>)Petition::setQuotaSignature);
		attributeGetterFunctions.put("inTheNameOf", Petition::getInTheNameOf);
		attributeSetterBiConsumers.put(
			"inTheNameOf",
			(BiConsumer<Petition, String>)Petition::setInTheNameOf);
		attributeGetterFunctions.put(
			"petitionnaireLastname", Petition::getPetitionnaireLastname);
		attributeSetterBiConsumers.put(
			"petitionnaireLastname",
			(BiConsumer<Petition, String>)Petition::setPetitionnaireLastname);
		attributeGetterFunctions.put(
			"petitionnaireFirstname", Petition::getPetitionnaireFirstname);
		attributeSetterBiConsumers.put(
			"petitionnaireFirstname",
			(BiConsumer<Petition, String>)Petition::setPetitionnaireFirstname);
		attributeGetterFunctions.put(
			"petitionnaireBirthday", Petition::getPetitionnaireBirthday);
		attributeSetterBiConsumers.put(
			"petitionnaireBirthday",
			(BiConsumer<Petition, Date>)Petition::setPetitionnaireBirthday);
		attributeGetterFunctions.put(
			"petitionnaireAdresse", Petition::getPetitionnaireAdresse);
		attributeSetterBiConsumers.put(
			"petitionnaireAdresse",
			(BiConsumer<Petition, String>)Petition::setPetitionnaireAdresse);
		attributeGetterFunctions.put(
			"petitionnairePostalCode", Petition::getPetitionnairePostalCode);
		attributeSetterBiConsumers.put(
			"petitionnairePostalCode",
			(BiConsumer<Petition, Long>)Petition::setPetitionnairePostalCode);
		attributeGetterFunctions.put(
			"petitionnaireCity", Petition::getPetitionnaireCity);
		attributeSetterBiConsumers.put(
			"petitionnaireCity",
			(BiConsumer<Petition, String>)Petition::setPetitionnaireCity);
		attributeGetterFunctions.put(
			"petitionnairePhone", Petition::getPetitionnairePhone);
		attributeSetterBiConsumers.put(
			"petitionnairePhone",
			(BiConsumer<Petition, String>)Petition::setPetitionnairePhone);
		attributeGetterFunctions.put(
			"petitionnaireEmail", Petition::getPetitionnaireEmail);
		attributeSetterBiConsumers.put(
			"petitionnaireEmail",
			(BiConsumer<Petition, String>)Petition::setPetitionnaireEmail);
		attributeGetterFunctions.put("isSupported", Petition::getIsSupported);
		attributeSetterBiConsumers.put(
			"isSupported",
			(BiConsumer<Petition, Boolean>)Petition::setIsSupported);
		attributeGetterFunctions.put("supportedBy", Petition::getSupportedBy);
		attributeSetterBiConsumers.put(
			"supportedBy",
			(BiConsumer<Petition, String>)Petition::setSupportedBy);
		attributeGetterFunctions.put("videoUrl", Petition::getVideoUrl);
		attributeSetterBiConsumers.put(
			"videoUrl", (BiConsumer<Petition, String>)Petition::setVideoUrl);
		attributeGetterFunctions.put(
			"externalImageURL", Petition::getExternalImageURL);
		attributeSetterBiConsumers.put(
			"externalImageURL",
			(BiConsumer<Petition, String>)Petition::setExternalImageURL);
		attributeGetterFunctions.put(
			"externalImageCopyright", Petition::getExternalImageCopyright);
		attributeSetterBiConsumers.put(
			"externalImageCopyright",
			(BiConsumer<Petition, String>)Petition::setExternalImageCopyright);
		attributeGetterFunctions.put("mediaChoice", Petition::getMediaChoice);
		attributeSetterBiConsumers.put(
			"mediaChoice",
			(BiConsumer<Petition, Boolean>)Petition::setMediaChoice);
		attributeGetterFunctions.put("publikId", Petition::getPublikId);
		attributeSetterBiConsumers.put(
			"publikId", (BiConsumer<Petition, String>)Petition::setPublikId);
		attributeGetterFunctions.put("imageId", Petition::getImageId);
		attributeSetterBiConsumers.put(
			"imageId", (BiConsumer<Petition, Long>)Petition::setImageId);
		attributeGetterFunctions.put("filesIds", Petition::getFilesIds);
		attributeSetterBiConsumers.put(
			"filesIds", (BiConsumer<Petition, String>)Petition::setFilesIds);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPetitionId() {
		return _petitionId;
	}

	@Override
	public void setPetitionId(long petitionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionId = petitionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getSummary() {
		if (_summary == null) {
			return "";
		}
		else {
			return _summary;
		}
	}

	@Override
	public void setSummary(String summary) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_summary = summary;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getPlaceTextArea() {
		if (_placeTextArea == null) {
			return "";
		}
		else {
			return _placeTextArea;
		}
	}

	@Override
	public void setPlaceTextArea(String placeTextArea) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeTextArea = placeTextArea;
	}

	@JSON
	@Override
	public String getFilesDownload() {
		if (_filesDownload == null) {
			return "";
		}
		else {
			return _filesDownload;
		}
	}

	@Override
	public void setFilesDownload(String filesDownload) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filesDownload = filesDownload;
	}

	@JSON
	@Override
	public Date getPublicationDate() {
		return _publicationDate;
	}

	@Override
	public void setPublicationDate(Date publicationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicationDate = publicationDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public Date getExtensionDate() {
		return _extensionDate;
	}

	@Override
	public void setExtensionDate(Date extensionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extensionDate = extensionDate;
	}

	@JSON
	@Override
	public long getQuotaSignature() {
		return _quotaSignature;
	}

	@Override
	public void setQuotaSignature(long quotaSignature) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quotaSignature = quotaSignature;
	}

	@JSON
	@Override
	public String getInTheNameOf() {
		if (_inTheNameOf == null) {
			return "";
		}
		else {
			return _inTheNameOf;
		}
	}

	@Override
	public void setInTheNameOf(String inTheNameOf) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_inTheNameOf = inTheNameOf;
	}

	@JSON
	@Override
	public String getPetitionnaireLastname() {
		if (_petitionnaireLastname == null) {
			return "";
		}
		else {
			return _petitionnaireLastname;
		}
	}

	@Override
	public void setPetitionnaireLastname(String petitionnaireLastname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireLastname = petitionnaireLastname;
	}

	@JSON
	@Override
	public String getPetitionnaireFirstname() {
		if (_petitionnaireFirstname == null) {
			return "";
		}
		else {
			return _petitionnaireFirstname;
		}
	}

	@Override
	public void setPetitionnaireFirstname(String petitionnaireFirstname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireFirstname = petitionnaireFirstname;
	}

	@JSON
	@Override
	public Date getPetitionnaireBirthday() {
		return _petitionnaireBirthday;
	}

	@Override
	public void setPetitionnaireBirthday(Date petitionnaireBirthday) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireBirthday = petitionnaireBirthday;
	}

	@JSON
	@Override
	public String getPetitionnaireAdresse() {
		if (_petitionnaireAdresse == null) {
			return "";
		}
		else {
			return _petitionnaireAdresse;
		}
	}

	@Override
	public void setPetitionnaireAdresse(String petitionnaireAdresse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireAdresse = petitionnaireAdresse;
	}

	@JSON
	@Override
	public long getPetitionnairePostalCode() {
		return _petitionnairePostalCode;
	}

	@Override
	public void setPetitionnairePostalCode(long petitionnairePostalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnairePostalCode = petitionnairePostalCode;
	}

	@JSON
	@Override
	public String getPetitionnaireCity() {
		if (_petitionnaireCity == null) {
			return "";
		}
		else {
			return _petitionnaireCity;
		}
	}

	@Override
	public void setPetitionnaireCity(String petitionnaireCity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireCity = petitionnaireCity;
	}

	@JSON
	@Override
	public String getPetitionnairePhone() {
		if (_petitionnairePhone == null) {
			return "";
		}
		else {
			return _petitionnairePhone;
		}
	}

	@Override
	public void setPetitionnairePhone(String petitionnairePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnairePhone = petitionnairePhone;
	}

	@JSON
	@Override
	public String getPetitionnaireEmail() {
		if (_petitionnaireEmail == null) {
			return "";
		}
		else {
			return _petitionnaireEmail;
		}
	}

	@Override
	public void setPetitionnaireEmail(String petitionnaireEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireEmail = petitionnaireEmail;
	}

	@JSON
	@Override
	public boolean getIsSupported() {
		return _isSupported;
	}

	@JSON
	@Override
	public boolean isIsSupported() {
		return _isSupported;
	}

	@Override
	public void setIsSupported(boolean isSupported) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isSupported = isSupported;
	}

	@JSON
	@Override
	public String getSupportedBy() {
		if (_supportedBy == null) {
			return "";
		}
		else {
			return _supportedBy;
		}
	}

	@Override
	public void setSupportedBy(String supportedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_supportedBy = supportedBy;
	}

	@JSON
	@Override
	public String getVideoUrl() {
		if (_videoUrl == null) {
			return "";
		}
		else {
			return _videoUrl;
		}
	}

	@Override
	public void setVideoUrl(String videoUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_videoUrl = videoUrl;
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public boolean getMediaChoice() {
		return _mediaChoice;
	}

	@JSON
	@Override
	public boolean isMediaChoice() {
		return _mediaChoice;
	}

	@Override
	public void setMediaChoice(boolean mediaChoice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mediaChoice = mediaChoice;
	}

	@JSON
	@Override
	public String getPublikId() {
		if (_publikId == null) {
			return "";
		}
		else {
			return _publikId;
		}
	}

	@Override
	public void setPublikId(String publikId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikId = publikId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikId() {
		return getColumnOriginalValue("publikId");
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@JSON
	@Override
	public String getFilesIds() {
		if (_filesIds == null) {
			return "";
		}
		else {
			return _filesIds;
		}
	}

	@Override
	public void setFilesIds(String filesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filesIds = filesIds;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Petition.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Petition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Petition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Petition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PetitionImpl petitionImpl = new PetitionImpl();

		petitionImpl.setUuid(getUuid());
		petitionImpl.setPetitionId(getPetitionId());
		petitionImpl.setGroupId(getGroupId());
		petitionImpl.setCompanyId(getCompanyId());
		petitionImpl.setUserId(getUserId());
		petitionImpl.setUserName(getUserName());
		petitionImpl.setCreateDate(getCreateDate());
		petitionImpl.setModifiedDate(getModifiedDate());
		petitionImpl.setStatus(getStatus());
		petitionImpl.setStatusByUserId(getStatusByUserId());
		petitionImpl.setStatusByUserName(getStatusByUserName());
		petitionImpl.setStatusDate(getStatusDate());
		petitionImpl.setTitle(getTitle());
		petitionImpl.setSummary(getSummary());
		petitionImpl.setDescription(getDescription());
		petitionImpl.setPlaceTextArea(getPlaceTextArea());
		petitionImpl.setFilesDownload(getFilesDownload());
		petitionImpl.setPublicationDate(getPublicationDate());
		petitionImpl.setExpirationDate(getExpirationDate());
		petitionImpl.setExtensionDate(getExtensionDate());
		petitionImpl.setQuotaSignature(getQuotaSignature());
		petitionImpl.setInTheNameOf(getInTheNameOf());
		petitionImpl.setPetitionnaireLastname(getPetitionnaireLastname());
		petitionImpl.setPetitionnaireFirstname(getPetitionnaireFirstname());
		petitionImpl.setPetitionnaireBirthday(getPetitionnaireBirthday());
		petitionImpl.setPetitionnaireAdresse(getPetitionnaireAdresse());
		petitionImpl.setPetitionnairePostalCode(getPetitionnairePostalCode());
		petitionImpl.setPetitionnaireCity(getPetitionnaireCity());
		petitionImpl.setPetitionnairePhone(getPetitionnairePhone());
		petitionImpl.setPetitionnaireEmail(getPetitionnaireEmail());
		petitionImpl.setIsSupported(isIsSupported());
		petitionImpl.setSupportedBy(getSupportedBy());
		petitionImpl.setVideoUrl(getVideoUrl());
		petitionImpl.setExternalImageURL(getExternalImageURL());
		petitionImpl.setExternalImageCopyright(getExternalImageCopyright());
		petitionImpl.setMediaChoice(isMediaChoice());
		petitionImpl.setPublikId(getPublikId());
		petitionImpl.setImageId(getImageId());
		petitionImpl.setFilesIds(getFilesIds());

		petitionImpl.resetOriginalValues();

		return petitionImpl;
	}

	@Override
	public Petition cloneWithOriginalValues() {
		PetitionImpl petitionImpl = new PetitionImpl();

		petitionImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		petitionImpl.setPetitionId(
			this.<Long>getColumnOriginalValue("petitionId"));
		petitionImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		petitionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		petitionImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		petitionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		petitionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		petitionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		petitionImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		petitionImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		petitionImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		petitionImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		petitionImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		petitionImpl.setSummary(this.<String>getColumnOriginalValue("summary"));
		petitionImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		petitionImpl.setPlaceTextArea(
			this.<String>getColumnOriginalValue("placeTextArea"));
		petitionImpl.setFilesDownload(
			this.<String>getColumnOriginalValue("filesDownload"));
		petitionImpl.setPublicationDate(
			this.<Date>getColumnOriginalValue("publicationDate"));
		petitionImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));
		petitionImpl.setExtensionDate(
			this.<Date>getColumnOriginalValue("extensionDate"));
		petitionImpl.setQuotaSignature(
			this.<Long>getColumnOriginalValue("quotaSignature"));
		petitionImpl.setInTheNameOf(
			this.<String>getColumnOriginalValue("inTheNameOf"));
		petitionImpl.setPetitionnaireLastname(
			this.<String>getColumnOriginalValue("petitionnaireLastname"));
		petitionImpl.setPetitionnaireFirstname(
			this.<String>getColumnOriginalValue("petitionnaireFirstname"));
		petitionImpl.setPetitionnaireBirthday(
			this.<Date>getColumnOriginalValue("petitionnaireBirthday"));
		petitionImpl.setPetitionnaireAdresse(
			this.<String>getColumnOriginalValue("petitionnaireAdresse"));
		petitionImpl.setPetitionnairePostalCode(
			this.<Long>getColumnOriginalValue("petitionnairePostalCode"));
		petitionImpl.setPetitionnaireCity(
			this.<String>getColumnOriginalValue("petitionnaireCity"));
		petitionImpl.setPetitionnairePhone(
			this.<String>getColumnOriginalValue("petitionnairePhone"));
		petitionImpl.setPetitionnaireEmail(
			this.<String>getColumnOriginalValue("petitionnaireEmail"));
		petitionImpl.setIsSupported(
			this.<Boolean>getColumnOriginalValue("isSupported"));
		petitionImpl.setSupportedBy(
			this.<String>getColumnOriginalValue("supportedBy"));
		petitionImpl.setVideoUrl(
			this.<String>getColumnOriginalValue("videoUrl"));
		petitionImpl.setExternalImageURL(
			this.<String>getColumnOriginalValue("externalImageURL"));
		petitionImpl.setExternalImageCopyright(
			this.<String>getColumnOriginalValue("externalImageCopyright"));
		petitionImpl.setMediaChoice(
			this.<Boolean>getColumnOriginalValue("mediaChoice"));
		petitionImpl.setPublikId(
			this.<String>getColumnOriginalValue("publikId"));
		petitionImpl.setImageId(this.<Long>getColumnOriginalValue("imageId"));
		petitionImpl.setFilesIds(
			this.<String>getColumnOriginalValue("filesIds"));

		return petitionImpl;
	}

	@Override
	public int compareTo(Petition petition) {
		int value = 0;

		value = getTitle().compareTo(petition.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Petition)) {
			return false;
		}

		Petition petition = (Petition)object;

		long primaryKey = petition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Petition> toCacheModel() {
		PetitionCacheModel petitionCacheModel = new PetitionCacheModel();

		petitionCacheModel.uuid = getUuid();

		String uuid = petitionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			petitionCacheModel.uuid = null;
		}

		petitionCacheModel.petitionId = getPetitionId();

		petitionCacheModel.groupId = getGroupId();

		petitionCacheModel.companyId = getCompanyId();

		petitionCacheModel.userId = getUserId();

		petitionCacheModel.userName = getUserName();

		String userName = petitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			petitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			petitionCacheModel.createDate = createDate.getTime();
		}
		else {
			petitionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			petitionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			petitionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		petitionCacheModel.status = getStatus();

		petitionCacheModel.statusByUserId = getStatusByUserId();

		petitionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = petitionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			petitionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			petitionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			petitionCacheModel.statusDate = Long.MIN_VALUE;
		}

		petitionCacheModel.title = getTitle();

		String title = petitionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			petitionCacheModel.title = null;
		}

		petitionCacheModel.summary = getSummary();

		String summary = petitionCacheModel.summary;

		if ((summary != null) && (summary.length() == 0)) {
			petitionCacheModel.summary = null;
		}

		petitionCacheModel.description = getDescription();

		String description = petitionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			petitionCacheModel.description = null;
		}

		petitionCacheModel.placeTextArea = getPlaceTextArea();

		String placeTextArea = petitionCacheModel.placeTextArea;

		if ((placeTextArea != null) && (placeTextArea.length() == 0)) {
			petitionCacheModel.placeTextArea = null;
		}

		petitionCacheModel.filesDownload = getFilesDownload();

		String filesDownload = petitionCacheModel.filesDownload;

		if ((filesDownload != null) && (filesDownload.length() == 0)) {
			petitionCacheModel.filesDownload = null;
		}

		Date publicationDate = getPublicationDate();

		if (publicationDate != null) {
			petitionCacheModel.publicationDate = publicationDate.getTime();
		}
		else {
			petitionCacheModel.publicationDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			petitionCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			petitionCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date extensionDate = getExtensionDate();

		if (extensionDate != null) {
			petitionCacheModel.extensionDate = extensionDate.getTime();
		}
		else {
			petitionCacheModel.extensionDate = Long.MIN_VALUE;
		}

		petitionCacheModel.quotaSignature = getQuotaSignature();

		petitionCacheModel.inTheNameOf = getInTheNameOf();

		String inTheNameOf = petitionCacheModel.inTheNameOf;

		if ((inTheNameOf != null) && (inTheNameOf.length() == 0)) {
			petitionCacheModel.inTheNameOf = null;
		}

		petitionCacheModel.petitionnaireLastname = getPetitionnaireLastname();

		String petitionnaireLastname = petitionCacheModel.petitionnaireLastname;

		if ((petitionnaireLastname != null) &&
			(petitionnaireLastname.length() == 0)) {

			petitionCacheModel.petitionnaireLastname = null;
		}

		petitionCacheModel.petitionnaireFirstname = getPetitionnaireFirstname();

		String petitionnaireFirstname =
			petitionCacheModel.petitionnaireFirstname;

		if ((petitionnaireFirstname != null) &&
			(petitionnaireFirstname.length() == 0)) {

			petitionCacheModel.petitionnaireFirstname = null;
		}

		Date petitionnaireBirthday = getPetitionnaireBirthday();

		if (petitionnaireBirthday != null) {
			petitionCacheModel.petitionnaireBirthday =
				petitionnaireBirthday.getTime();
		}
		else {
			petitionCacheModel.petitionnaireBirthday = Long.MIN_VALUE;
		}

		petitionCacheModel.petitionnaireAdresse = getPetitionnaireAdresse();

		String petitionnaireAdresse = petitionCacheModel.petitionnaireAdresse;

		if ((petitionnaireAdresse != null) &&
			(petitionnaireAdresse.length() == 0)) {

			petitionCacheModel.petitionnaireAdresse = null;
		}

		petitionCacheModel.petitionnairePostalCode =
			getPetitionnairePostalCode();

		petitionCacheModel.petitionnaireCity = getPetitionnaireCity();

		String petitionnaireCity = petitionCacheModel.petitionnaireCity;

		if ((petitionnaireCity != null) && (petitionnaireCity.length() == 0)) {
			petitionCacheModel.petitionnaireCity = null;
		}

		petitionCacheModel.petitionnairePhone = getPetitionnairePhone();

		String petitionnairePhone = petitionCacheModel.petitionnairePhone;

		if ((petitionnairePhone != null) &&
			(petitionnairePhone.length() == 0)) {

			petitionCacheModel.petitionnairePhone = null;
		}

		petitionCacheModel.petitionnaireEmail = getPetitionnaireEmail();

		String petitionnaireEmail = petitionCacheModel.petitionnaireEmail;

		if ((petitionnaireEmail != null) &&
			(petitionnaireEmail.length() == 0)) {

			petitionCacheModel.petitionnaireEmail = null;
		}

		petitionCacheModel.isSupported = isIsSupported();

		petitionCacheModel.supportedBy = getSupportedBy();

		String supportedBy = petitionCacheModel.supportedBy;

		if ((supportedBy != null) && (supportedBy.length() == 0)) {
			petitionCacheModel.supportedBy = null;
		}

		petitionCacheModel.videoUrl = getVideoUrl();

		String videoUrl = petitionCacheModel.videoUrl;

		if ((videoUrl != null) && (videoUrl.length() == 0)) {
			petitionCacheModel.videoUrl = null;
		}

		petitionCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL = petitionCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			petitionCacheModel.externalImageURL = null;
		}

		petitionCacheModel.externalImageCopyright = getExternalImageCopyright();

		String externalImageCopyright =
			petitionCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			petitionCacheModel.externalImageCopyright = null;
		}

		petitionCacheModel.mediaChoice = isMediaChoice();

		petitionCacheModel.publikId = getPublikId();

		String publikId = petitionCacheModel.publikId;

		if ((publikId != null) && (publikId.length() == 0)) {
			petitionCacheModel.publikId = null;
		}

		petitionCacheModel.imageId = getImageId();

		petitionCacheModel.filesIds = getFilesIds();

		String filesIds = petitionCacheModel.filesIds;

		if ((filesIds != null) && (filesIds.length() == 0)) {
			petitionCacheModel.filesIds = null;
		}

		return petitionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Petition, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Petition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Petition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Petition)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Petition>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Petition.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _petitionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _summary;
	private String _description;
	private String _placeTextArea;
	private String _filesDownload;
	private Date _publicationDate;
	private Date _expirationDate;
	private Date _extensionDate;
	private long _quotaSignature;
	private String _inTheNameOf;
	private String _petitionnaireLastname;
	private String _petitionnaireFirstname;
	private Date _petitionnaireBirthday;
	private String _petitionnaireAdresse;
	private long _petitionnairePostalCode;
	private String _petitionnaireCity;
	private String _petitionnairePhone;
	private String _petitionnaireEmail;
	private boolean _isSupported;
	private String _supportedBy;
	private String _videoUrl;
	private String _externalImageURL;
	private String _externalImageCopyright;
	private boolean _mediaChoice;
	private String _publikId;
	private long _imageId;
	private String _filesIds;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Petition, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Petition)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("petitionId", _petitionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("summary", _summary);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("placeTextArea", _placeTextArea);
		_columnOriginalValues.put("filesDownload", _filesDownload);
		_columnOriginalValues.put("publicationDate", _publicationDate);
		_columnOriginalValues.put("expirationDate", _expirationDate);
		_columnOriginalValues.put("extensionDate", _extensionDate);
		_columnOriginalValues.put("quotaSignature", _quotaSignature);
		_columnOriginalValues.put("inTheNameOf", _inTheNameOf);
		_columnOriginalValues.put(
			"petitionnaireLastname", _petitionnaireLastname);
		_columnOriginalValues.put(
			"petitionnaireFirstname", _petitionnaireFirstname);
		_columnOriginalValues.put(
			"petitionnaireBirthday", _petitionnaireBirthday);
		_columnOriginalValues.put(
			"petitionnaireAdresse", _petitionnaireAdresse);
		_columnOriginalValues.put(
			"petitionnairePostalCode", _petitionnairePostalCode);
		_columnOriginalValues.put("petitionnaireCity", _petitionnaireCity);
		_columnOriginalValues.put("petitionnairePhone", _petitionnairePhone);
		_columnOriginalValues.put("petitionnaireEmail", _petitionnaireEmail);
		_columnOriginalValues.put("isSupported", _isSupported);
		_columnOriginalValues.put("supportedBy", _supportedBy);
		_columnOriginalValues.put("videoUrl", _videoUrl);
		_columnOriginalValues.put("externalImageURL", _externalImageURL);
		_columnOriginalValues.put(
			"externalImageCopyright", _externalImageCopyright);
		_columnOriginalValues.put("mediaChoice", _mediaChoice);
		_columnOriginalValues.put("publikId", _publikId);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("filesIds", _filesIds);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("petitionId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("title", 4096L);

		columnBitmasks.put("summary", 8192L);

		columnBitmasks.put("description", 16384L);

		columnBitmasks.put("placeTextArea", 32768L);

		columnBitmasks.put("filesDownload", 65536L);

		columnBitmasks.put("publicationDate", 131072L);

		columnBitmasks.put("expirationDate", 262144L);

		columnBitmasks.put("extensionDate", 524288L);

		columnBitmasks.put("quotaSignature", 1048576L);

		columnBitmasks.put("inTheNameOf", 2097152L);

		columnBitmasks.put("petitionnaireLastname", 4194304L);

		columnBitmasks.put("petitionnaireFirstname", 8388608L);

		columnBitmasks.put("petitionnaireBirthday", 16777216L);

		columnBitmasks.put("petitionnaireAdresse", 33554432L);

		columnBitmasks.put("petitionnairePostalCode", 67108864L);

		columnBitmasks.put("petitionnaireCity", 134217728L);

		columnBitmasks.put("petitionnairePhone", 268435456L);

		columnBitmasks.put("petitionnaireEmail", 536870912L);

		columnBitmasks.put("isSupported", 1073741824L);

		columnBitmasks.put("supportedBy", 2147483648L);

		columnBitmasks.put("videoUrl", 4294967296L);

		columnBitmasks.put("externalImageURL", 8589934592L);

		columnBitmasks.put("externalImageCopyright", 17179869184L);

		columnBitmasks.put("mediaChoice", 34359738368L);

		columnBitmasks.put("publikId", 68719476736L);

		columnBitmasks.put("imageId", 137438953472L);

		columnBitmasks.put("filesIds", 274877906944L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Petition _escapedModel;

}