/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.Project;
import eu.strasbourg.service.project.model.ProjectModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Project service. Represents a row in the &quot;project_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see ProjectImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectModelImpl
	extends BaseModelImpl<Project> implements ProjectModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project model instance should use the <code>Project</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_Project";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"projectId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"externalImageURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"opacityImage", Types.DOUBLE}, {"description", Types.CLOB},
		{"detailURL", Types.VARCHAR}, {"budget", Types.VARCHAR},
		{"label", Types.VARCHAR}, {"duration", Types.VARCHAR},
		{"partners", Types.CLOB}, {"contactName", Types.VARCHAR},
		{"contactLine1", Types.VARCHAR}, {"contactLine2", Types.VARCHAR},
		{"contactPhoneNumber", Types.VARCHAR}, {"imageId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("opacityImage", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("detailURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budget", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("label", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("duration", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("partners", Types.CLOB);
		TABLE_COLUMNS_MAP.put("contactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactPhoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_Project (uuid_ VARCHAR(75) null,projectId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,externalImageURL VARCHAR(400) null,externalImageCopyright VARCHAR(400) null,opacityImage DOUBLE,description TEXT null,detailURL VARCHAR(75) null,budget VARCHAR(75) null,label VARCHAR(75) null,duration VARCHAR(75) null,partners TEXT null,contactName VARCHAR(75) null,contactLine1 VARCHAR(400) null,contactLine2 VARCHAR(400) null,contactPhoneNumber VARCHAR(75) null,imageId LONG)";

	public static final String TABLE_SQL_DROP = "drop table project_Project";

	public static final String ORDER_BY_JPQL = " ORDER BY project.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_Project.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.Project"));

	public ProjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Project.class;
	}

	@Override
	public String getModelClassName() {
		return Project.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Project, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Project, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Project, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Project)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Project, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Project, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Project)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Project, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Project, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Project, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Project, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Project, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Project, Object>>();
		Map<String, BiConsumer<Project, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Project, ?>>();

		attributeGetterFunctions.put("uuid", Project::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Project, String>)Project::setUuid);
		attributeGetterFunctions.put("projectId", Project::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<Project, Long>)Project::setProjectId);
		attributeGetterFunctions.put("groupId", Project::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Project, Long>)Project::setGroupId);
		attributeGetterFunctions.put("companyId", Project::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Project, Long>)Project::setCompanyId);
		attributeGetterFunctions.put("userId", Project::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Project, Long>)Project::setUserId);
		attributeGetterFunctions.put("userName", Project::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Project, String>)Project::setUserName);
		attributeGetterFunctions.put("createDate", Project::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Project, Date>)Project::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Project::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Project, Date>)Project::setModifiedDate);
		attributeGetterFunctions.put("status", Project::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Project, Integer>)Project::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Project::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Project, Long>)Project::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Project::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Project, String>)Project::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Project::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Project, Date>)Project::setStatusDate);
		attributeGetterFunctions.put("title", Project::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Project, String>)Project::setTitle);
		attributeGetterFunctions.put(
			"externalImageURL", Project::getExternalImageURL);
		attributeSetterBiConsumers.put(
			"externalImageURL",
			(BiConsumer<Project, String>)Project::setExternalImageURL);
		attributeGetterFunctions.put(
			"externalImageCopyright", Project::getExternalImageCopyright);
		attributeSetterBiConsumers.put(
			"externalImageCopyright",
			(BiConsumer<Project, String>)Project::setExternalImageCopyright);
		attributeGetterFunctions.put("opacityImage", Project::getOpacityImage);
		attributeSetterBiConsumers.put(
			"opacityImage",
			(BiConsumer<Project, Double>)Project::setOpacityImage);
		attributeGetterFunctions.put("description", Project::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Project, String>)Project::setDescription);
		attributeGetterFunctions.put("detailURL", Project::getDetailURL);
		attributeSetterBiConsumers.put(
			"detailURL", (BiConsumer<Project, String>)Project::setDetailURL);
		attributeGetterFunctions.put("budget", Project::getBudget);
		attributeSetterBiConsumers.put(
			"budget", (BiConsumer<Project, String>)Project::setBudget);
		attributeGetterFunctions.put("label", Project::getLabel);
		attributeSetterBiConsumers.put(
			"label", (BiConsumer<Project, String>)Project::setLabel);
		attributeGetterFunctions.put("duration", Project::getDuration);
		attributeSetterBiConsumers.put(
			"duration", (BiConsumer<Project, String>)Project::setDuration);
		attributeGetterFunctions.put("partners", Project::getPartners);
		attributeSetterBiConsumers.put(
			"partners", (BiConsumer<Project, String>)Project::setPartners);
		attributeGetterFunctions.put("contactName", Project::getContactName);
		attributeSetterBiConsumers.put(
			"contactName",
			(BiConsumer<Project, String>)Project::setContactName);
		attributeGetterFunctions.put("contactLine1", Project::getContactLine1);
		attributeSetterBiConsumers.put(
			"contactLine1",
			(BiConsumer<Project, String>)Project::setContactLine1);
		attributeGetterFunctions.put("contactLine2", Project::getContactLine2);
		attributeSetterBiConsumers.put(
			"contactLine2",
			(BiConsumer<Project, String>)Project::setContactLine2);
		attributeGetterFunctions.put(
			"contactPhoneNumber", Project::getContactPhoneNumber);
		attributeSetterBiConsumers.put(
			"contactPhoneNumber",
			(BiConsumer<Project, String>)Project::setContactPhoneNumber);
		attributeGetterFunctions.put("imageId", Project::getImageId);
		attributeSetterBiConsumers.put(
			"imageId", (BiConsumer<Project, Long>)Project::setImageId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public double getOpacityImage() {
		return _opacityImage;
	}

	@Override
	public void setOpacityImage(double opacityImage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_opacityImage = opacityImage;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getDetailURL() {
		if (_detailURL == null) {
			return "";
		}
		else {
			return _detailURL;
		}
	}

	@Override
	public void setDetailURL(String detailURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detailURL = detailURL;
	}

	@JSON
	@Override
	public String getBudget() {
		if (_budget == null) {
			return "";
		}
		else {
			return _budget;
		}
	}

	@Override
	public void setBudget(String budget) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_budget = budget;
	}

	@JSON
	@Override
	public String getLabel() {
		if (_label == null) {
			return "";
		}
		else {
			return _label;
		}
	}

	@Override
	public void setLabel(String label) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_label = label;
	}

	@JSON
	@Override
	public String getDuration() {
		if (_duration == null) {
			return "";
		}
		else {
			return _duration;
		}
	}

	@Override
	public void setDuration(String duration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_duration = duration;
	}

	@JSON
	@Override
	public String getPartners() {
		if (_partners == null) {
			return "";
		}
		else {
			return _partners;
		}
	}

	@Override
	public void setPartners(String partners) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_partners = partners;
	}

	@JSON
	@Override
	public String getContactName() {
		if (_contactName == null) {
			return "";
		}
		else {
			return _contactName;
		}
	}

	@Override
	public void setContactName(String contactName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactName = contactName;
	}

	@JSON
	@Override
	public String getContactLine1() {
		if (_contactLine1 == null) {
			return "";
		}
		else {
			return _contactLine1;
		}
	}

	@Override
	public void setContactLine1(String contactLine1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactLine1 = contactLine1;
	}

	@JSON
	@Override
	public String getContactLine2() {
		if (_contactLine2 == null) {
			return "";
		}
		else {
			return _contactLine2;
		}
	}

	@Override
	public void setContactLine2(String contactLine2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactLine2 = contactLine2;
	}

	@JSON
	@Override
	public String getContactPhoneNumber() {
		if (_contactPhoneNumber == null) {
			return "";
		}
		else {
			return _contactPhoneNumber;
		}
	}

	@Override
	public void setContactPhoneNumber(String contactPhoneNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactPhoneNumber = contactPhoneNumber;
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Project.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Project.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Project toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Project>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectImpl projectImpl = new ProjectImpl();

		projectImpl.setUuid(getUuid());
		projectImpl.setProjectId(getProjectId());
		projectImpl.setGroupId(getGroupId());
		projectImpl.setCompanyId(getCompanyId());
		projectImpl.setUserId(getUserId());
		projectImpl.setUserName(getUserName());
		projectImpl.setCreateDate(getCreateDate());
		projectImpl.setModifiedDate(getModifiedDate());
		projectImpl.setStatus(getStatus());
		projectImpl.setStatusByUserId(getStatusByUserId());
		projectImpl.setStatusByUserName(getStatusByUserName());
		projectImpl.setStatusDate(getStatusDate());
		projectImpl.setTitle(getTitle());
		projectImpl.setExternalImageURL(getExternalImageURL());
		projectImpl.setExternalImageCopyright(getExternalImageCopyright());
		projectImpl.setOpacityImage(getOpacityImage());
		projectImpl.setDescription(getDescription());
		projectImpl.setDetailURL(getDetailURL());
		projectImpl.setBudget(getBudget());
		projectImpl.setLabel(getLabel());
		projectImpl.setDuration(getDuration());
		projectImpl.setPartners(getPartners());
		projectImpl.setContactName(getContactName());
		projectImpl.setContactLine1(getContactLine1());
		projectImpl.setContactLine2(getContactLine2());
		projectImpl.setContactPhoneNumber(getContactPhoneNumber());
		projectImpl.setImageId(getImageId());

		projectImpl.resetOriginalValues();

		return projectImpl;
	}

	@Override
	public Project cloneWithOriginalValues() {
		ProjectImpl projectImpl = new ProjectImpl();

		projectImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		projectImpl.setProjectId(
			this.<Long>getColumnOriginalValue("projectId"));
		projectImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		projectImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		projectImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		projectImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		projectImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		projectImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		projectImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		projectImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		projectImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		projectImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		projectImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		projectImpl.setExternalImageURL(
			this.<String>getColumnOriginalValue("externalImageURL"));
		projectImpl.setExternalImageCopyright(
			this.<String>getColumnOriginalValue("externalImageCopyright"));
		projectImpl.setOpacityImage(
			this.<Double>getColumnOriginalValue("opacityImage"));
		projectImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		projectImpl.setDetailURL(
			this.<String>getColumnOriginalValue("detailURL"));
		projectImpl.setBudget(this.<String>getColumnOriginalValue("budget"));
		projectImpl.setLabel(this.<String>getColumnOriginalValue("label"));
		projectImpl.setDuration(
			this.<String>getColumnOriginalValue("duration"));
		projectImpl.setPartners(
			this.<String>getColumnOriginalValue("partners"));
		projectImpl.setContactName(
			this.<String>getColumnOriginalValue("contactName"));
		projectImpl.setContactLine1(
			this.<String>getColumnOriginalValue("contactLine1"));
		projectImpl.setContactLine2(
			this.<String>getColumnOriginalValue("contactLine2"));
		projectImpl.setContactPhoneNumber(
			this.<String>getColumnOriginalValue("contactPhoneNumber"));
		projectImpl.setImageId(this.<Long>getColumnOriginalValue("imageId"));

		return projectImpl;
	}

	@Override
	public int compareTo(Project project) {
		int value = 0;

		value = getTitle().compareTo(project.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Project)) {
			return false;
		}

		Project project = (Project)object;

		long primaryKey = project.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Project> toCacheModel() {
		ProjectCacheModel projectCacheModel = new ProjectCacheModel();

		projectCacheModel.uuid = getUuid();

		String uuid = projectCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectCacheModel.uuid = null;
		}

		projectCacheModel.projectId = getProjectId();

		projectCacheModel.groupId = getGroupId();

		projectCacheModel.companyId = getCompanyId();

		projectCacheModel.userId = getUserId();

		projectCacheModel.userName = getUserName();

		String userName = projectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			projectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectCacheModel.createDate = createDate.getTime();
		}
		else {
			projectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			projectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectCacheModel.status = getStatus();

		projectCacheModel.statusByUserId = getStatusByUserId();

		projectCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = projectCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			projectCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			projectCacheModel.statusDate = statusDate.getTime();
		}
		else {
			projectCacheModel.statusDate = Long.MIN_VALUE;
		}

		projectCacheModel.title = getTitle();

		String title = projectCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			projectCacheModel.title = null;
		}

		projectCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL = projectCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			projectCacheModel.externalImageURL = null;
		}

		projectCacheModel.externalImageCopyright = getExternalImageCopyright();

		String externalImageCopyright =
			projectCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			projectCacheModel.externalImageCopyright = null;
		}

		projectCacheModel.opacityImage = getOpacityImage();

		projectCacheModel.description = getDescription();

		String description = projectCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			projectCacheModel.description = null;
		}

		projectCacheModel.detailURL = getDetailURL();

		String detailURL = projectCacheModel.detailURL;

		if ((detailURL != null) && (detailURL.length() == 0)) {
			projectCacheModel.detailURL = null;
		}

		projectCacheModel.budget = getBudget();

		String budget = projectCacheModel.budget;

		if ((budget != null) && (budget.length() == 0)) {
			projectCacheModel.budget = null;
		}

		projectCacheModel.label = getLabel();

		String label = projectCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			projectCacheModel.label = null;
		}

		projectCacheModel.duration = getDuration();

		String duration = projectCacheModel.duration;

		if ((duration != null) && (duration.length() == 0)) {
			projectCacheModel.duration = null;
		}

		projectCacheModel.partners = getPartners();

		String partners = projectCacheModel.partners;

		if ((partners != null) && (partners.length() == 0)) {
			projectCacheModel.partners = null;
		}

		projectCacheModel.contactName = getContactName();

		String contactName = projectCacheModel.contactName;

		if ((contactName != null) && (contactName.length() == 0)) {
			projectCacheModel.contactName = null;
		}

		projectCacheModel.contactLine1 = getContactLine1();

		String contactLine1 = projectCacheModel.contactLine1;

		if ((contactLine1 != null) && (contactLine1.length() == 0)) {
			projectCacheModel.contactLine1 = null;
		}

		projectCacheModel.contactLine2 = getContactLine2();

		String contactLine2 = projectCacheModel.contactLine2;

		if ((contactLine2 != null) && (contactLine2.length() == 0)) {
			projectCacheModel.contactLine2 = null;
		}

		projectCacheModel.contactPhoneNumber = getContactPhoneNumber();

		String contactPhoneNumber = projectCacheModel.contactPhoneNumber;

		if ((contactPhoneNumber != null) &&
			(contactPhoneNumber.length() == 0)) {

			projectCacheModel.contactPhoneNumber = null;
		}

		projectCacheModel.imageId = getImageId();

		return projectCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Project, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Project, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Project, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Project)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Project>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Project.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _projectId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _externalImageURL;
	private String _externalImageCopyright;
	private double _opacityImage;
	private String _description;
	private String _detailURL;
	private String _budget;
	private String _label;
	private String _duration;
	private String _partners;
	private String _contactName;
	private String _contactLine1;
	private String _contactLine2;
	private String _contactPhoneNumber;
	private long _imageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Project, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Project)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("externalImageURL", _externalImageURL);
		_columnOriginalValues.put(
			"externalImageCopyright", _externalImageCopyright);
		_columnOriginalValues.put("opacityImage", _opacityImage);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("detailURL", _detailURL);
		_columnOriginalValues.put("budget", _budget);
		_columnOriginalValues.put("label", _label);
		_columnOriginalValues.put("duration", _duration);
		_columnOriginalValues.put("partners", _partners);
		_columnOriginalValues.put("contactName", _contactName);
		_columnOriginalValues.put("contactLine1", _contactLine1);
		_columnOriginalValues.put("contactLine2", _contactLine2);
		_columnOriginalValues.put("contactPhoneNumber", _contactPhoneNumber);
		_columnOriginalValues.put("imageId", _imageId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("projectId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("title", 4096L);

		columnBitmasks.put("externalImageURL", 8192L);

		columnBitmasks.put("externalImageCopyright", 16384L);

		columnBitmasks.put("opacityImage", 32768L);

		columnBitmasks.put("description", 65536L);

		columnBitmasks.put("detailURL", 131072L);

		columnBitmasks.put("budget", 262144L);

		columnBitmasks.put("label", 524288L);

		columnBitmasks.put("duration", 1048576L);

		columnBitmasks.put("partners", 2097152L);

		columnBitmasks.put("contactName", 4194304L);

		columnBitmasks.put("contactLine1", 8388608L);

		columnBitmasks.put("contactLine2", 16777216L);

		columnBitmasks.put("contactPhoneNumber", 33554432L);

		columnBitmasks.put("imageId", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Project _escapedModel;

}