/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import eu.strasbourg.service.project.model.ProjectFollowed;
import eu.strasbourg.service.project.model.ProjectFollowedModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectFollowed service. Represents a row in the &quot;project_ProjectFollowed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectFollowedModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectFollowedImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see ProjectFollowedImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectFollowedModelImpl
	extends BaseModelImpl<ProjectFollowed> implements ProjectFollowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project followed model instance should use the <code>ProjectFollowed</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_ProjectFollowed";

	public static final Object[][] TABLE_COLUMNS = {
		{"projectFollowedId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"publikUserId", Types.VARCHAR}, {"projectId", Types.BIGINT},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("projectFollowedId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_ProjectFollowed (projectFollowedId LONG not null primary key,createDate DATE null,publikUserId VARCHAR(75) null,projectId LONG,groupId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table project_ProjectFollowed";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectFollowed.projectFollowedId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_ProjectFollowed.projectFollowedId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTFOLLOWEDID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.ProjectFollowed"));

	public ProjectFollowedModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectFollowedId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectFollowedId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectFollowedId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectFollowed.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectFollowed.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectFollowed, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectFollowed, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectFollowed, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectFollowed)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectFollowed, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectFollowed, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectFollowed)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectFollowed, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectFollowed, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProjectFollowed, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProjectFollowed, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProjectFollowed, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ProjectFollowed, Object>>();
		Map<String, BiConsumer<ProjectFollowed, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ProjectFollowed, ?>>();

		attributeGetterFunctions.put(
			"projectFollowedId", ProjectFollowed::getProjectFollowedId);
		attributeSetterBiConsumers.put(
			"projectFollowedId",
			(BiConsumer<ProjectFollowed, Long>)
				ProjectFollowed::setProjectFollowedId);
		attributeGetterFunctions.put(
			"createDate", ProjectFollowed::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ProjectFollowed, Date>)ProjectFollowed::setCreateDate);
		attributeGetterFunctions.put(
			"publikUserId", ProjectFollowed::getPublikUserId);
		attributeSetterBiConsumers.put(
			"publikUserId",
			(BiConsumer<ProjectFollowed, String>)
				ProjectFollowed::setPublikUserId);
		attributeGetterFunctions.put(
			"projectId", ProjectFollowed::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId",
			(BiConsumer<ProjectFollowed, Long>)ProjectFollowed::setProjectId);
		attributeGetterFunctions.put("groupId", ProjectFollowed::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ProjectFollowed, Long>)ProjectFollowed::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getProjectFollowedId() {
		return _projectFollowedId;
	}

	@Override
	public void setProjectFollowedId(long projectFollowedId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectFollowedId = projectFollowedId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProjectId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("projectId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProjectFollowed.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectFollowed toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectFollowed>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectFollowedImpl projectFollowedImpl = new ProjectFollowedImpl();

		projectFollowedImpl.setProjectFollowedId(getProjectFollowedId());
		projectFollowedImpl.setCreateDate(getCreateDate());
		projectFollowedImpl.setPublikUserId(getPublikUserId());
		projectFollowedImpl.setProjectId(getProjectId());
		projectFollowedImpl.setGroupId(getGroupId());

		projectFollowedImpl.resetOriginalValues();

		return projectFollowedImpl;
	}

	@Override
	public ProjectFollowed cloneWithOriginalValues() {
		ProjectFollowedImpl projectFollowedImpl = new ProjectFollowedImpl();

		projectFollowedImpl.setProjectFollowedId(
			this.<Long>getColumnOriginalValue("projectFollowedId"));
		projectFollowedImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		projectFollowedImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		projectFollowedImpl.setProjectId(
			this.<Long>getColumnOriginalValue("projectId"));
		projectFollowedImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));

		return projectFollowedImpl;
	}

	@Override
	public int compareTo(ProjectFollowed projectFollowed) {
		long primaryKey = projectFollowed.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectFollowed)) {
			return false;
		}

		ProjectFollowed projectFollowed = (ProjectFollowed)object;

		long primaryKey = projectFollowed.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectFollowed> toCacheModel() {
		ProjectFollowedCacheModel projectFollowedCacheModel =
			new ProjectFollowedCacheModel();

		projectFollowedCacheModel.projectFollowedId = getProjectFollowedId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectFollowedCacheModel.createDate = createDate.getTime();
		}
		else {
			projectFollowedCacheModel.createDate = Long.MIN_VALUE;
		}

		projectFollowedCacheModel.publikUserId = getPublikUserId();

		String publikUserId = projectFollowedCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			projectFollowedCacheModel.publikUserId = null;
		}

		projectFollowedCacheModel.projectId = getProjectId();

		projectFollowedCacheModel.groupId = getGroupId();

		return projectFollowedCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectFollowed, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectFollowed, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectFollowed, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProjectFollowed)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProjectFollowed>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProjectFollowed.class, ModelWrapper.class);

	}

	private long _projectFollowedId;
	private Date _createDate;
	private String _publikUserId;
	private long _projectId;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		Function<ProjectFollowed, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProjectFollowed)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("projectFollowedId", _projectFollowedId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("projectFollowedId", 1L);

		columnBitmasks.put("createDate", 2L);

		columnBitmasks.put("publikUserId", 4L);

		columnBitmasks.put("projectId", 8L);

		columnBitmasks.put("groupId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProjectFollowed _escapedModel;

}