/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.SaisineObservatoire;
import eu.strasbourg.service.project.model.SaisineObservatoireModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SaisineObservatoire service. Represents a row in the &quot;project_SaisineObservatoire&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SaisineObservatoireModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SaisineObservatoireImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see SaisineObservatoireImpl
 * @generated
 */
@JSON(strict = true)
public class SaisineObservatoireModelImpl
	extends BaseModelImpl<SaisineObservatoire>
	implements SaisineObservatoireModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a saisine observatoire model instance should use the <code>SaisineObservatoire</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_SaisineObservatoire";

	public static final Object[][] TABLE_COLUMNS = {
		{"saisineObservatoireId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"description", Types.CLOB}, {"placeTextArea", Types.VARCHAR},
		{"filesDownload", Types.VARCHAR}, {"cityResponse", Types.CLOB},
		{"projectTarget", Types.VARCHAR}, {"otherMechanism", Types.VARCHAR},
		{"collectiveName", Types.VARCHAR},
		{"petitionnaireLastname", Types.VARCHAR},
		{"petitionnaireFirstname", Types.VARCHAR},
		{"petitionnaireBirthday", Types.TIMESTAMP},
		{"petitionnaireAdresse", Types.VARCHAR},
		{"petitionnairePostalCode", Types.BIGINT},
		{"petitionnaireCity", Types.VARCHAR},
		{"petitionnairePhone", Types.VARCHAR},
		{"petitionnaireEmail", Types.VARCHAR}, {"videoUrl", Types.VARCHAR},
		{"externalImageURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"mediaChoice", Types.BOOLEAN}, {"publikId", Types.VARCHAR},
		{"imageId", Types.BIGINT}, {"filesIds", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("saisineObservatoireId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("placeTextArea", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filesDownload", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cityResponse", Types.CLOB);
		TABLE_COLUMNS_MAP.put("projectTarget", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("otherMechanism", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("collectiveName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireLastname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireFirstname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireBirthday", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("petitionnaireAdresse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnairePostalCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("petitionnaireCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnairePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionnaireEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("videoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mediaChoice", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("publikId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("filesIds", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_SaisineObservatoire (saisineObservatoireId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,description TEXT null,placeTextArea VARCHAR(400) null,filesDownload VARCHAR(75) null,cityResponse TEXT null,projectTarget VARCHAR(150) null,otherMechanism VARCHAR(150) null,collectiveName VARCHAR(150) null,petitionnaireLastname VARCHAR(75) null,petitionnaireFirstname VARCHAR(75) null,petitionnaireBirthday DATE null,petitionnaireAdresse VARCHAR(400) null,petitionnairePostalCode LONG,petitionnaireCity VARCHAR(400) null,petitionnairePhone VARCHAR(75) null,petitionnaireEmail VARCHAR(400) null,videoUrl VARCHAR(400) null,externalImageURL VARCHAR(400) null,externalImageCopyright VARCHAR(75) null,mediaChoice BOOLEAN,publikId VARCHAR(75) null,imageId LONG,filesIds VARCHAR(400) null)";

	public static final String TABLE_SQL_DROP =
		"drop table project_SaisineObservatoire";

	public static final String ORDER_BY_JPQL =
		" ORDER BY saisineObservatoire.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_SaisineObservatoire.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.SaisineObservatoire"));

	public SaisineObservatoireModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _saisineObservatoireId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSaisineObservatoireId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _saisineObservatoireId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SaisineObservatoire.class;
	}

	@Override
	public String getModelClassName() {
		return SaisineObservatoire.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SaisineObservatoire, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SaisineObservatoire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SaisineObservatoire, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SaisineObservatoire)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SaisineObservatoire, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SaisineObservatoire, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SaisineObservatoire)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SaisineObservatoire, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SaisineObservatoire, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SaisineObservatoire, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SaisineObservatoire, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<SaisineObservatoire, Object>>();

			attributeGetterFunctions.put(
				"saisineObservatoireId",
				SaisineObservatoire::getSaisineObservatoireId);
			attributeGetterFunctions.put(
				"groupId", SaisineObservatoire::getGroupId);
			attributeGetterFunctions.put(
				"companyId", SaisineObservatoire::getCompanyId);
			attributeGetterFunctions.put(
				"userId", SaisineObservatoire::getUserId);
			attributeGetterFunctions.put(
				"userName", SaisineObservatoire::getUserName);
			attributeGetterFunctions.put(
				"createDate", SaisineObservatoire::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", SaisineObservatoire::getModifiedDate);
			attributeGetterFunctions.put(
				"status", SaisineObservatoire::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", SaisineObservatoire::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", SaisineObservatoire::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", SaisineObservatoire::getStatusDate);
			attributeGetterFunctions.put(
				"title", SaisineObservatoire::getTitle);
			attributeGetterFunctions.put(
				"description", SaisineObservatoire::getDescription);
			attributeGetterFunctions.put(
				"placeTextArea", SaisineObservatoire::getPlaceTextArea);
			attributeGetterFunctions.put(
				"filesDownload", SaisineObservatoire::getFilesDownload);
			attributeGetterFunctions.put(
				"cityResponse", SaisineObservatoire::getCityResponse);
			attributeGetterFunctions.put(
				"projectTarget", SaisineObservatoire::getProjectTarget);
			attributeGetterFunctions.put(
				"otherMechanism", SaisineObservatoire::getOtherMechanism);
			attributeGetterFunctions.put(
				"collectiveName", SaisineObservatoire::getCollectiveName);
			attributeGetterFunctions.put(
				"petitionnaireLastname",
				SaisineObservatoire::getPetitionnaireLastname);
			attributeGetterFunctions.put(
				"petitionnaireFirstname",
				SaisineObservatoire::getPetitionnaireFirstname);
			attributeGetterFunctions.put(
				"petitionnaireBirthday",
				SaisineObservatoire::getPetitionnaireBirthday);
			attributeGetterFunctions.put(
				"petitionnaireAdresse",
				SaisineObservatoire::getPetitionnaireAdresse);
			attributeGetterFunctions.put(
				"petitionnairePostalCode",
				SaisineObservatoire::getPetitionnairePostalCode);
			attributeGetterFunctions.put(
				"petitionnaireCity", SaisineObservatoire::getPetitionnaireCity);
			attributeGetterFunctions.put(
				"petitionnairePhone",
				SaisineObservatoire::getPetitionnairePhone);
			attributeGetterFunctions.put(
				"petitionnaireEmail",
				SaisineObservatoire::getPetitionnaireEmail);
			attributeGetterFunctions.put(
				"videoUrl", SaisineObservatoire::getVideoUrl);
			attributeGetterFunctions.put(
				"externalImageURL", SaisineObservatoire::getExternalImageURL);
			attributeGetterFunctions.put(
				"externalImageCopyright",
				SaisineObservatoire::getExternalImageCopyright);
			attributeGetterFunctions.put(
				"mediaChoice", SaisineObservatoire::getMediaChoice);
			attributeGetterFunctions.put(
				"publikId", SaisineObservatoire::getPublikId);
			attributeGetterFunctions.put(
				"imageId", SaisineObservatoire::getImageId);
			attributeGetterFunctions.put(
				"filesIds", SaisineObservatoire::getFilesIds);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<SaisineObservatoire, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SaisineObservatoire, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<SaisineObservatoire, ?>>();

			attributeSetterBiConsumers.put(
				"saisineObservatoireId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setSaisineObservatoireId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SaisineObservatoire, Date>)
					SaisineObservatoire::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SaisineObservatoire, Date>)
					SaisineObservatoire::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<SaisineObservatoire, Integer>)
					SaisineObservatoire::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<SaisineObservatoire, Date>)
					SaisineObservatoire::setStatusDate);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setTitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setDescription);
			attributeSetterBiConsumers.put(
				"placeTextArea",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPlaceTextArea);
			attributeSetterBiConsumers.put(
				"filesDownload",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setFilesDownload);
			attributeSetterBiConsumers.put(
				"cityResponse",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setCityResponse);
			attributeSetterBiConsumers.put(
				"projectTarget",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setProjectTarget);
			attributeSetterBiConsumers.put(
				"otherMechanism",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setOtherMechanism);
			attributeSetterBiConsumers.put(
				"collectiveName",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setCollectiveName);
			attributeSetterBiConsumers.put(
				"petitionnaireLastname",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnaireLastname);
			attributeSetterBiConsumers.put(
				"petitionnaireFirstname",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnaireFirstname);
			attributeSetterBiConsumers.put(
				"petitionnaireBirthday",
				(BiConsumer<SaisineObservatoire, Date>)
					SaisineObservatoire::setPetitionnaireBirthday);
			attributeSetterBiConsumers.put(
				"petitionnaireAdresse",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnaireAdresse);
			attributeSetterBiConsumers.put(
				"petitionnairePostalCode",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setPetitionnairePostalCode);
			attributeSetterBiConsumers.put(
				"petitionnaireCity",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnaireCity);
			attributeSetterBiConsumers.put(
				"petitionnairePhone",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnairePhone);
			attributeSetterBiConsumers.put(
				"petitionnaireEmail",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPetitionnaireEmail);
			attributeSetterBiConsumers.put(
				"videoUrl",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setVideoUrl);
			attributeSetterBiConsumers.put(
				"externalImageURL",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setExternalImageURL);
			attributeSetterBiConsumers.put(
				"externalImageCopyright",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setExternalImageCopyright);
			attributeSetterBiConsumers.put(
				"mediaChoice",
				(BiConsumer<SaisineObservatoire, Boolean>)
					SaisineObservatoire::setMediaChoice);
			attributeSetterBiConsumers.put(
				"publikId",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setPublikId);
			attributeSetterBiConsumers.put(
				"imageId",
				(BiConsumer<SaisineObservatoire, Long>)
					SaisineObservatoire::setImageId);
			attributeSetterBiConsumers.put(
				"filesIds",
				(BiConsumer<SaisineObservatoire, String>)
					SaisineObservatoire::setFilesIds);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getSaisineObservatoireId() {
		return _saisineObservatoireId;
	}

	@Override
	public void setSaisineObservatoireId(long saisineObservatoireId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_saisineObservatoireId = saisineObservatoireId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getPlaceTextArea() {
		if (_placeTextArea == null) {
			return "";
		}
		else {
			return _placeTextArea;
		}
	}

	@Override
	public void setPlaceTextArea(String placeTextArea) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeTextArea = placeTextArea;
	}

	@JSON
	@Override
	public String getFilesDownload() {
		if (_filesDownload == null) {
			return "";
		}
		else {
			return _filesDownload;
		}
	}

	@Override
	public void setFilesDownload(String filesDownload) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filesDownload = filesDownload;
	}

	@JSON
	@Override
	public String getCityResponse() {
		if (_cityResponse == null) {
			return "";
		}
		else {
			return _cityResponse;
		}
	}

	@Override
	public String getCityResponse(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCityResponse(languageId);
	}

	@Override
	public String getCityResponse(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCityResponse(languageId, useDefault);
	}

	@Override
	public String getCityResponse(String languageId) {
		return LocalizationUtil.getLocalization(getCityResponse(), languageId);
	}

	@Override
	public String getCityResponse(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getCityResponse(), languageId, useDefault);
	}

	@Override
	public String getCityResponseCurrentLanguageId() {
		return _cityResponseCurrentLanguageId;
	}

	@JSON
	@Override
	public String getCityResponseCurrentValue() {
		Locale locale = getLocale(_cityResponseCurrentLanguageId);

		return getCityResponse(locale);
	}

	@Override
	public Map<Locale, String> getCityResponseMap() {
		return LocalizationUtil.getLocalizationMap(getCityResponse());
	}

	@Override
	public void setCityResponse(String cityResponse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cityResponse = cityResponse;
	}

	@Override
	public void setCityResponse(String cityResponse, Locale locale) {
		setCityResponse(cityResponse, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCityResponse(
		String cityResponse, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(cityResponse)) {
			setCityResponse(
				LocalizationUtil.updateLocalization(
					getCityResponse(), "CityResponse", cityResponse, languageId,
					defaultLanguageId));
		}
		else {
			setCityResponse(
				LocalizationUtil.removeLocalization(
					getCityResponse(), "CityResponse", languageId));
		}
	}

	@Override
	public void setCityResponseCurrentLanguageId(String languageId) {
		_cityResponseCurrentLanguageId = languageId;
	}

	@Override
	public void setCityResponseMap(Map<Locale, String> cityResponseMap) {
		setCityResponseMap(cityResponseMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCityResponseMap(
		Map<Locale, String> cityResponseMap, Locale defaultLocale) {

		if (cityResponseMap == null) {
			return;
		}

		setCityResponse(
			LocalizationUtil.updateLocalization(
				cityResponseMap, getCityResponse(), "CityResponse",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getProjectTarget() {
		if (_projectTarget == null) {
			return "";
		}
		else {
			return _projectTarget;
		}
	}

	@Override
	public void setProjectTarget(String projectTarget) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectTarget = projectTarget;
	}

	@JSON
	@Override
	public String getOtherMechanism() {
		if (_otherMechanism == null) {
			return "";
		}
		else {
			return _otherMechanism;
		}
	}

	@Override
	public void setOtherMechanism(String otherMechanism) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_otherMechanism = otherMechanism;
	}

	@JSON
	@Override
	public String getCollectiveName() {
		if (_collectiveName == null) {
			return "";
		}
		else {
			return _collectiveName;
		}
	}

	@Override
	public void setCollectiveName(String collectiveName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_collectiveName = collectiveName;
	}

	@JSON
	@Override
	public String getPetitionnaireLastname() {
		if (_petitionnaireLastname == null) {
			return "";
		}
		else {
			return _petitionnaireLastname;
		}
	}

	@Override
	public void setPetitionnaireLastname(String petitionnaireLastname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireLastname = petitionnaireLastname;
	}

	@JSON
	@Override
	public String getPetitionnaireFirstname() {
		if (_petitionnaireFirstname == null) {
			return "";
		}
		else {
			return _petitionnaireFirstname;
		}
	}

	@Override
	public void setPetitionnaireFirstname(String petitionnaireFirstname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireFirstname = petitionnaireFirstname;
	}

	@JSON
	@Override
	public Date getPetitionnaireBirthday() {
		return _petitionnaireBirthday;
	}

	@Override
	public void setPetitionnaireBirthday(Date petitionnaireBirthday) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireBirthday = petitionnaireBirthday;
	}

	@JSON
	@Override
	public String getPetitionnaireAdresse() {
		if (_petitionnaireAdresse == null) {
			return "";
		}
		else {
			return _petitionnaireAdresse;
		}
	}

	@Override
	public void setPetitionnaireAdresse(String petitionnaireAdresse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireAdresse = petitionnaireAdresse;
	}

	@JSON
	@Override
	public long getPetitionnairePostalCode() {
		return _petitionnairePostalCode;
	}

	@Override
	public void setPetitionnairePostalCode(long petitionnairePostalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnairePostalCode = petitionnairePostalCode;
	}

	@JSON
	@Override
	public String getPetitionnaireCity() {
		if (_petitionnaireCity == null) {
			return "";
		}
		else {
			return _petitionnaireCity;
		}
	}

	@Override
	public void setPetitionnaireCity(String petitionnaireCity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireCity = petitionnaireCity;
	}

	@JSON
	@Override
	public String getPetitionnairePhone() {
		if (_petitionnairePhone == null) {
			return "";
		}
		else {
			return _petitionnairePhone;
		}
	}

	@Override
	public void setPetitionnairePhone(String petitionnairePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnairePhone = petitionnairePhone;
	}

	@JSON
	@Override
	public String getPetitionnaireEmail() {
		if (_petitionnaireEmail == null) {
			return "";
		}
		else {
			return _petitionnaireEmail;
		}
	}

	@Override
	public void setPetitionnaireEmail(String petitionnaireEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionnaireEmail = petitionnaireEmail;
	}

	@JSON
	@Override
	public String getVideoUrl() {
		if (_videoUrl == null) {
			return "";
		}
		else {
			return _videoUrl;
		}
	}

	@Override
	public void setVideoUrl(String videoUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_videoUrl = videoUrl;
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public boolean getMediaChoice() {
		return _mediaChoice;
	}

	@JSON
	@Override
	public boolean isMediaChoice() {
		return _mediaChoice;
	}

	@Override
	public void setMediaChoice(boolean mediaChoice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mediaChoice = mediaChoice;
	}

	@JSON
	@Override
	public String getPublikId() {
		if (_publikId == null) {
			return "";
		}
		else {
			return _publikId;
		}
	}

	@Override
	public void setPublikId(String publikId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikId = publikId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikId() {
		return getColumnOriginalValue("publikId");
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@JSON
	@Override
	public String getFilesIds() {
		if (_filesIds == null) {
			return "";
		}
		else {
			return _filesIds;
		}
	}

	@Override
	public void setFilesIds(String filesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filesIds = filesIds;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SaisineObservatoire.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> cityResponseMap = getCityResponseMap();

		for (Map.Entry<Locale, String> entry : cityResponseMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDescription();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			SaisineObservatoire.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}

		String cityResponse = getCityResponse(defaultLocale);

		if (Validator.isNull(cityResponse)) {
			setCityResponse(
				getCityResponse(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setCityResponse(
				getCityResponse(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public SaisineObservatoire toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SaisineObservatoire>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SaisineObservatoireImpl saisineObservatoireImpl =
			new SaisineObservatoireImpl();

		saisineObservatoireImpl.setSaisineObservatoireId(
			getSaisineObservatoireId());
		saisineObservatoireImpl.setGroupId(getGroupId());
		saisineObservatoireImpl.setCompanyId(getCompanyId());
		saisineObservatoireImpl.setUserId(getUserId());
		saisineObservatoireImpl.setUserName(getUserName());
		saisineObservatoireImpl.setCreateDate(getCreateDate());
		saisineObservatoireImpl.setModifiedDate(getModifiedDate());
		saisineObservatoireImpl.setStatus(getStatus());
		saisineObservatoireImpl.setStatusByUserId(getStatusByUserId());
		saisineObservatoireImpl.setStatusByUserName(getStatusByUserName());
		saisineObservatoireImpl.setStatusDate(getStatusDate());
		saisineObservatoireImpl.setTitle(getTitle());
		saisineObservatoireImpl.setDescription(getDescription());
		saisineObservatoireImpl.setPlaceTextArea(getPlaceTextArea());
		saisineObservatoireImpl.setFilesDownload(getFilesDownload());
		saisineObservatoireImpl.setCityResponse(getCityResponse());
		saisineObservatoireImpl.setProjectTarget(getProjectTarget());
		saisineObservatoireImpl.setOtherMechanism(getOtherMechanism());
		saisineObservatoireImpl.setCollectiveName(getCollectiveName());
		saisineObservatoireImpl.setPetitionnaireLastname(
			getPetitionnaireLastname());
		saisineObservatoireImpl.setPetitionnaireFirstname(
			getPetitionnaireFirstname());
		saisineObservatoireImpl.setPetitionnaireBirthday(
			getPetitionnaireBirthday());
		saisineObservatoireImpl.setPetitionnaireAdresse(
			getPetitionnaireAdresse());
		saisineObservatoireImpl.setPetitionnairePostalCode(
			getPetitionnairePostalCode());
		saisineObservatoireImpl.setPetitionnaireCity(getPetitionnaireCity());
		saisineObservatoireImpl.setPetitionnairePhone(getPetitionnairePhone());
		saisineObservatoireImpl.setPetitionnaireEmail(getPetitionnaireEmail());
		saisineObservatoireImpl.setVideoUrl(getVideoUrl());
		saisineObservatoireImpl.setExternalImageURL(getExternalImageURL());
		saisineObservatoireImpl.setExternalImageCopyright(
			getExternalImageCopyright());
		saisineObservatoireImpl.setMediaChoice(isMediaChoice());
		saisineObservatoireImpl.setPublikId(getPublikId());
		saisineObservatoireImpl.setImageId(getImageId());
		saisineObservatoireImpl.setFilesIds(getFilesIds());

		saisineObservatoireImpl.resetOriginalValues();

		return saisineObservatoireImpl;
	}

	@Override
	public SaisineObservatoire cloneWithOriginalValues() {
		SaisineObservatoireImpl saisineObservatoireImpl =
			new SaisineObservatoireImpl();

		saisineObservatoireImpl.setSaisineObservatoireId(
			this.<Long>getColumnOriginalValue("saisineObservatoireId"));
		saisineObservatoireImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		saisineObservatoireImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		saisineObservatoireImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		saisineObservatoireImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		saisineObservatoireImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		saisineObservatoireImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		saisineObservatoireImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		saisineObservatoireImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		saisineObservatoireImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		saisineObservatoireImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		saisineObservatoireImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		saisineObservatoireImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		saisineObservatoireImpl.setPlaceTextArea(
			this.<String>getColumnOriginalValue("placeTextArea"));
		saisineObservatoireImpl.setFilesDownload(
			this.<String>getColumnOriginalValue("filesDownload"));
		saisineObservatoireImpl.setCityResponse(
			this.<String>getColumnOriginalValue("cityResponse"));
		saisineObservatoireImpl.setProjectTarget(
			this.<String>getColumnOriginalValue("projectTarget"));
		saisineObservatoireImpl.setOtherMechanism(
			this.<String>getColumnOriginalValue("otherMechanism"));
		saisineObservatoireImpl.setCollectiveName(
			this.<String>getColumnOriginalValue("collectiveName"));
		saisineObservatoireImpl.setPetitionnaireLastname(
			this.<String>getColumnOriginalValue("petitionnaireLastname"));
		saisineObservatoireImpl.setPetitionnaireFirstname(
			this.<String>getColumnOriginalValue("petitionnaireFirstname"));
		saisineObservatoireImpl.setPetitionnaireBirthday(
			this.<Date>getColumnOriginalValue("petitionnaireBirthday"));
		saisineObservatoireImpl.setPetitionnaireAdresse(
			this.<String>getColumnOriginalValue("petitionnaireAdresse"));
		saisineObservatoireImpl.setPetitionnairePostalCode(
			this.<Long>getColumnOriginalValue("petitionnairePostalCode"));
		saisineObservatoireImpl.setPetitionnaireCity(
			this.<String>getColumnOriginalValue("petitionnaireCity"));
		saisineObservatoireImpl.setPetitionnairePhone(
			this.<String>getColumnOriginalValue("petitionnairePhone"));
		saisineObservatoireImpl.setPetitionnaireEmail(
			this.<String>getColumnOriginalValue("petitionnaireEmail"));
		saisineObservatoireImpl.setVideoUrl(
			this.<String>getColumnOriginalValue("videoUrl"));
		saisineObservatoireImpl.setExternalImageURL(
			this.<String>getColumnOriginalValue("externalImageURL"));
		saisineObservatoireImpl.setExternalImageCopyright(
			this.<String>getColumnOriginalValue("externalImageCopyright"));
		saisineObservatoireImpl.setMediaChoice(
			this.<Boolean>getColumnOriginalValue("mediaChoice"));
		saisineObservatoireImpl.setPublikId(
			this.<String>getColumnOriginalValue("publikId"));
		saisineObservatoireImpl.setImageId(
			this.<Long>getColumnOriginalValue("imageId"));
		saisineObservatoireImpl.setFilesIds(
			this.<String>getColumnOriginalValue("filesIds"));

		return saisineObservatoireImpl;
	}

	@Override
	public int compareTo(SaisineObservatoire saisineObservatoire) {
		int value = 0;

		value = getTitle().compareTo(saisineObservatoire.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SaisineObservatoire)) {
			return false;
		}

		SaisineObservatoire saisineObservatoire = (SaisineObservatoire)object;

		long primaryKey = saisineObservatoire.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SaisineObservatoire> toCacheModel() {
		SaisineObservatoireCacheModel saisineObservatoireCacheModel =
			new SaisineObservatoireCacheModel();

		saisineObservatoireCacheModel.saisineObservatoireId =
			getSaisineObservatoireId();

		saisineObservatoireCacheModel.groupId = getGroupId();

		saisineObservatoireCacheModel.companyId = getCompanyId();

		saisineObservatoireCacheModel.userId = getUserId();

		saisineObservatoireCacheModel.userName = getUserName();

		String userName = saisineObservatoireCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			saisineObservatoireCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			saisineObservatoireCacheModel.createDate = createDate.getTime();
		}
		else {
			saisineObservatoireCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			saisineObservatoireCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			saisineObservatoireCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		saisineObservatoireCacheModel.status = getStatus();

		saisineObservatoireCacheModel.statusByUserId = getStatusByUserId();

		saisineObservatoireCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName =
			saisineObservatoireCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			saisineObservatoireCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			saisineObservatoireCacheModel.statusDate = statusDate.getTime();
		}
		else {
			saisineObservatoireCacheModel.statusDate = Long.MIN_VALUE;
		}

		saisineObservatoireCacheModel.title = getTitle();

		String title = saisineObservatoireCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			saisineObservatoireCacheModel.title = null;
		}

		saisineObservatoireCacheModel.description = getDescription();

		String description = saisineObservatoireCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			saisineObservatoireCacheModel.description = null;
		}

		saisineObservatoireCacheModel.placeTextArea = getPlaceTextArea();

		String placeTextArea = saisineObservatoireCacheModel.placeTextArea;

		if ((placeTextArea != null) && (placeTextArea.length() == 0)) {
			saisineObservatoireCacheModel.placeTextArea = null;
		}

		saisineObservatoireCacheModel.filesDownload = getFilesDownload();

		String filesDownload = saisineObservatoireCacheModel.filesDownload;

		if ((filesDownload != null) && (filesDownload.length() == 0)) {
			saisineObservatoireCacheModel.filesDownload = null;
		}

		saisineObservatoireCacheModel.cityResponse = getCityResponse();

		String cityResponse = saisineObservatoireCacheModel.cityResponse;

		if ((cityResponse != null) && (cityResponse.length() == 0)) {
			saisineObservatoireCacheModel.cityResponse = null;
		}

		saisineObservatoireCacheModel.projectTarget = getProjectTarget();

		String projectTarget = saisineObservatoireCacheModel.projectTarget;

		if ((projectTarget != null) && (projectTarget.length() == 0)) {
			saisineObservatoireCacheModel.projectTarget = null;
		}

		saisineObservatoireCacheModel.otherMechanism = getOtherMechanism();

		String otherMechanism = saisineObservatoireCacheModel.otherMechanism;

		if ((otherMechanism != null) && (otherMechanism.length() == 0)) {
			saisineObservatoireCacheModel.otherMechanism = null;
		}

		saisineObservatoireCacheModel.collectiveName = getCollectiveName();

		String collectiveName = saisineObservatoireCacheModel.collectiveName;

		if ((collectiveName != null) && (collectiveName.length() == 0)) {
			saisineObservatoireCacheModel.collectiveName = null;
		}

		saisineObservatoireCacheModel.petitionnaireLastname =
			getPetitionnaireLastname();

		String petitionnaireLastname =
			saisineObservatoireCacheModel.petitionnaireLastname;

		if ((petitionnaireLastname != null) &&
			(petitionnaireLastname.length() == 0)) {

			saisineObservatoireCacheModel.petitionnaireLastname = null;
		}

		saisineObservatoireCacheModel.petitionnaireFirstname =
			getPetitionnaireFirstname();

		String petitionnaireFirstname =
			saisineObservatoireCacheModel.petitionnaireFirstname;

		if ((petitionnaireFirstname != null) &&
			(petitionnaireFirstname.length() == 0)) {

			saisineObservatoireCacheModel.petitionnaireFirstname = null;
		}

		Date petitionnaireBirthday = getPetitionnaireBirthday();

		if (petitionnaireBirthday != null) {
			saisineObservatoireCacheModel.petitionnaireBirthday =
				petitionnaireBirthday.getTime();
		}
		else {
			saisineObservatoireCacheModel.petitionnaireBirthday =
				Long.MIN_VALUE;
		}

		saisineObservatoireCacheModel.petitionnaireAdresse =
			getPetitionnaireAdresse();

		String petitionnaireAdresse =
			saisineObservatoireCacheModel.petitionnaireAdresse;

		if ((petitionnaireAdresse != null) &&
			(petitionnaireAdresse.length() == 0)) {

			saisineObservatoireCacheModel.petitionnaireAdresse = null;
		}

		saisineObservatoireCacheModel.petitionnairePostalCode =
			getPetitionnairePostalCode();

		saisineObservatoireCacheModel.petitionnaireCity =
			getPetitionnaireCity();

		String petitionnaireCity =
			saisineObservatoireCacheModel.petitionnaireCity;

		if ((petitionnaireCity != null) && (petitionnaireCity.length() == 0)) {
			saisineObservatoireCacheModel.petitionnaireCity = null;
		}

		saisineObservatoireCacheModel.petitionnairePhone =
			getPetitionnairePhone();

		String petitionnairePhone =
			saisineObservatoireCacheModel.petitionnairePhone;

		if ((petitionnairePhone != null) &&
			(petitionnairePhone.length() == 0)) {

			saisineObservatoireCacheModel.petitionnairePhone = null;
		}

		saisineObservatoireCacheModel.petitionnaireEmail =
			getPetitionnaireEmail();

		String petitionnaireEmail =
			saisineObservatoireCacheModel.petitionnaireEmail;

		if ((petitionnaireEmail != null) &&
			(petitionnaireEmail.length() == 0)) {

			saisineObservatoireCacheModel.petitionnaireEmail = null;
		}

		saisineObservatoireCacheModel.videoUrl = getVideoUrl();

		String videoUrl = saisineObservatoireCacheModel.videoUrl;

		if ((videoUrl != null) && (videoUrl.length() == 0)) {
			saisineObservatoireCacheModel.videoUrl = null;
		}

		saisineObservatoireCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL =
			saisineObservatoireCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			saisineObservatoireCacheModel.externalImageURL = null;
		}

		saisineObservatoireCacheModel.externalImageCopyright =
			getExternalImageCopyright();

		String externalImageCopyright =
			saisineObservatoireCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			saisineObservatoireCacheModel.externalImageCopyright = null;
		}

		saisineObservatoireCacheModel.mediaChoice = isMediaChoice();

		saisineObservatoireCacheModel.publikId = getPublikId();

		String publikId = saisineObservatoireCacheModel.publikId;

		if ((publikId != null) && (publikId.length() == 0)) {
			saisineObservatoireCacheModel.publikId = null;
		}

		saisineObservatoireCacheModel.imageId = getImageId();

		saisineObservatoireCacheModel.filesIds = getFilesIds();

		String filesIds = saisineObservatoireCacheModel.filesIds;

		if ((filesIds != null) && (filesIds.length() == 0)) {
			saisineObservatoireCacheModel.filesIds = null;
		}

		return saisineObservatoireCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SaisineObservatoire, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SaisineObservatoire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SaisineObservatoire, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SaisineObservatoire)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SaisineObservatoire>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SaisineObservatoire.class, ModelWrapper.class);

	}

	private long _saisineObservatoireId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _placeTextArea;
	private String _filesDownload;
	private String _cityResponse;
	private String _cityResponseCurrentLanguageId;
	private String _projectTarget;
	private String _otherMechanism;
	private String _collectiveName;
	private String _petitionnaireLastname;
	private String _petitionnaireFirstname;
	private Date _petitionnaireBirthday;
	private String _petitionnaireAdresse;
	private long _petitionnairePostalCode;
	private String _petitionnaireCity;
	private String _petitionnairePhone;
	private String _petitionnaireEmail;
	private String _videoUrl;
	private String _externalImageURL;
	private String _externalImageCopyright;
	private boolean _mediaChoice;
	private String _publikId;
	private long _imageId;
	private String _filesIds;

	public <T> T getColumnValue(String columnName) {
		Function<SaisineObservatoire, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SaisineObservatoire)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"saisineObservatoireId", _saisineObservatoireId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("placeTextArea", _placeTextArea);
		_columnOriginalValues.put("filesDownload", _filesDownload);
		_columnOriginalValues.put("cityResponse", _cityResponse);
		_columnOriginalValues.put("projectTarget", _projectTarget);
		_columnOriginalValues.put("otherMechanism", _otherMechanism);
		_columnOriginalValues.put("collectiveName", _collectiveName);
		_columnOriginalValues.put(
			"petitionnaireLastname", _petitionnaireLastname);
		_columnOriginalValues.put(
			"petitionnaireFirstname", _petitionnaireFirstname);
		_columnOriginalValues.put(
			"petitionnaireBirthday", _petitionnaireBirthday);
		_columnOriginalValues.put(
			"petitionnaireAdresse", _petitionnaireAdresse);
		_columnOriginalValues.put(
			"petitionnairePostalCode", _petitionnairePostalCode);
		_columnOriginalValues.put("petitionnaireCity", _petitionnaireCity);
		_columnOriginalValues.put("petitionnairePhone", _petitionnairePhone);
		_columnOriginalValues.put("petitionnaireEmail", _petitionnaireEmail);
		_columnOriginalValues.put("videoUrl", _videoUrl);
		_columnOriginalValues.put("externalImageURL", _externalImageURL);
		_columnOriginalValues.put(
			"externalImageCopyright", _externalImageCopyright);
		_columnOriginalValues.put("mediaChoice", _mediaChoice);
		_columnOriginalValues.put("publikId", _publikId);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("filesIds", _filesIds);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("saisineObservatoireId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("status", 128L);

		columnBitmasks.put("statusByUserId", 256L);

		columnBitmasks.put("statusByUserName", 512L);

		columnBitmasks.put("statusDate", 1024L);

		columnBitmasks.put("title", 2048L);

		columnBitmasks.put("description", 4096L);

		columnBitmasks.put("placeTextArea", 8192L);

		columnBitmasks.put("filesDownload", 16384L);

		columnBitmasks.put("cityResponse", 32768L);

		columnBitmasks.put("projectTarget", 65536L);

		columnBitmasks.put("otherMechanism", 131072L);

		columnBitmasks.put("collectiveName", 262144L);

		columnBitmasks.put("petitionnaireLastname", 524288L);

		columnBitmasks.put("petitionnaireFirstname", 1048576L);

		columnBitmasks.put("petitionnaireBirthday", 2097152L);

		columnBitmasks.put("petitionnaireAdresse", 4194304L);

		columnBitmasks.put("petitionnairePostalCode", 8388608L);

		columnBitmasks.put("petitionnaireCity", 16777216L);

		columnBitmasks.put("petitionnairePhone", 33554432L);

		columnBitmasks.put("petitionnaireEmail", 67108864L);

		columnBitmasks.put("videoUrl", 134217728L);

		columnBitmasks.put("externalImageURL", 268435456L);

		columnBitmasks.put("externalImageCopyright", 536870912L);

		columnBitmasks.put("mediaChoice", 1073741824L);

		columnBitmasks.put("publikId", 2147483648L);

		columnBitmasks.put("imageId", 4294967296L);

		columnBitmasks.put("filesIds", 8589934592L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SaisineObservatoire _escapedModel;

}