/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.project.model.impl;

import eu.strasbourg.service.project.model.SaisineObservatoire;
import eu.strasbourg.service.project.service.SaisineObservatoireLocalServiceUtil;

/**
 * The extended model base implementation for the SaisineObservatoire service. Represents a row in the &quot;project_SaisineObservatoire&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SaisineObservatoireImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see SaisineObservatoireImpl
 * @see SaisineObservatoire
 * @generated
 */
public abstract class SaisineObservatoireBaseImpl
	extends SaisineObservatoireModelImpl implements SaisineObservatoire {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a saisine observatoire model instance should use the <code>SaisineObservatoire</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SaisineObservatoireLocalServiceUtil.addSaisineObservatoire(this);
		}
		else {
			SaisineObservatoireLocalServiceUtil.updateSaisineObservatoire(this);
		}
	}

}