/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.Signataire;
import eu.strasbourg.service.project.model.SignataireModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Signataire service. Represents a row in the &quot;project_Signataire&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SignataireModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SignataireImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see SignataireImpl
 * @generated
 */
@JSON(strict = true)
public class SignataireModelImpl
	extends BaseModelImpl<Signataire> implements SignataireModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a signataire model instance should use the <code>Signataire</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_Signataire";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"signataireId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"signataireName", Types.VARCHAR},
		{"signataireFirstname", Types.VARCHAR}, {"birthday", Types.TIMESTAMP},
		{"address", Types.VARCHAR}, {"mail", Types.VARCHAR},
		{"postalCode", Types.BIGINT}, {"mobilePhone", Types.VARCHAR},
		{"phone", Types.VARCHAR}, {"city", Types.VARCHAR},
		{"signatureDate", Types.TIMESTAMP}, {"publikUserId", Types.VARCHAR},
		{"petitionId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("signataireId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("signataireName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("signataireFirstname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthday", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("signatureDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petitionId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_Signataire (uuid_ VARCHAR(75) null,signataireId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,signataireName VARCHAR(75) null,signataireFirstname VARCHAR(75) null,birthday DATE null,address VARCHAR(400) null,mail VARCHAR(400) null,postalCode LONG,mobilePhone VARCHAR(75) null,phone VARCHAR(75) null,city VARCHAR(400) null,signatureDate DATE null,publikUserId VARCHAR(75) null,petitionId LONG)";

	public static final String TABLE_SQL_DROP = "drop table project_Signataire";

	public static final String ORDER_BY_JPQL =
		" ORDER BY signataire.signataireId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_Signataire.signataireId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PETITIONID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SIGNATAIRENAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SIGNATAIREID_COLUMN_BITMASK = 64L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.Signataire"));

	public SignataireModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _signataireId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSignataireId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _signataireId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Signataire.class;
	}

	@Override
	public String getModelClassName() {
		return Signataire.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Signataire, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Signataire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Signataire, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Signataire)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Signataire, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Signataire, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Signataire)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Signataire, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Signataire, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Signataire, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Signataire, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Signataire, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Signataire, Object>>();
		Map<String, BiConsumer<Signataire, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Signataire, ?>>();

		attributeGetterFunctions.put("uuid", Signataire::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Signataire, String>)Signataire::setUuid);
		attributeGetterFunctions.put(
			"signataireId", Signataire::getSignataireId);
		attributeSetterBiConsumers.put(
			"signataireId",
			(BiConsumer<Signataire, Long>)Signataire::setSignataireId);
		attributeGetterFunctions.put("groupId", Signataire::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Signataire, Long>)Signataire::setGroupId);
		attributeGetterFunctions.put("companyId", Signataire::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Signataire, Long>)Signataire::setCompanyId);
		attributeGetterFunctions.put("userId", Signataire::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Signataire, Long>)Signataire::setUserId);
		attributeGetterFunctions.put("userName", Signataire::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Signataire, String>)Signataire::setUserName);
		attributeGetterFunctions.put("createDate", Signataire::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Signataire, Date>)Signataire::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Signataire::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Signataire, Date>)Signataire::setModifiedDate);
		attributeGetterFunctions.put("status", Signataire::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Signataire, Integer>)Signataire::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Signataire::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Signataire, Long>)Signataire::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Signataire::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Signataire, String>)Signataire::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Signataire::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<Signataire, Date>)Signataire::setStatusDate);
		attributeGetterFunctions.put(
			"signataireName", Signataire::getSignataireName);
		attributeSetterBiConsumers.put(
			"signataireName",
			(BiConsumer<Signataire, String>)Signataire::setSignataireName);
		attributeGetterFunctions.put(
			"signataireFirstname", Signataire::getSignataireFirstname);
		attributeSetterBiConsumers.put(
			"signataireFirstname",
			(BiConsumer<Signataire, String>)Signataire::setSignataireFirstname);
		attributeGetterFunctions.put("birthday", Signataire::getBirthday);
		attributeSetterBiConsumers.put(
			"birthday", (BiConsumer<Signataire, Date>)Signataire::setBirthday);
		attributeGetterFunctions.put("address", Signataire::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<Signataire, String>)Signataire::setAddress);
		attributeGetterFunctions.put("mail", Signataire::getMail);
		attributeSetterBiConsumers.put(
			"mail", (BiConsumer<Signataire, String>)Signataire::setMail);
		attributeGetterFunctions.put("postalCode", Signataire::getPostalCode);
		attributeSetterBiConsumers.put(
			"postalCode",
			(BiConsumer<Signataire, Long>)Signataire::setPostalCode);
		attributeGetterFunctions.put("mobilePhone", Signataire::getMobilePhone);
		attributeSetterBiConsumers.put(
			"mobilePhone",
			(BiConsumer<Signataire, String>)Signataire::setMobilePhone);
		attributeGetterFunctions.put("phone", Signataire::getPhone);
		attributeSetterBiConsumers.put(
			"phone", (BiConsumer<Signataire, String>)Signataire::setPhone);
		attributeGetterFunctions.put("city", Signataire::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<Signataire, String>)Signataire::setCity);
		attributeGetterFunctions.put(
			"signatureDate", Signataire::getSignatureDate);
		attributeSetterBiConsumers.put(
			"signatureDate",
			(BiConsumer<Signataire, Date>)Signataire::setSignatureDate);
		attributeGetterFunctions.put(
			"publikUserId", Signataire::getPublikUserId);
		attributeSetterBiConsumers.put(
			"publikUserId",
			(BiConsumer<Signataire, String>)Signataire::setPublikUserId);
		attributeGetterFunctions.put("petitionId", Signataire::getPetitionId);
		attributeSetterBiConsumers.put(
			"petitionId",
			(BiConsumer<Signataire, Long>)Signataire::setPetitionId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSignataireId() {
		return _signataireId;
	}

	@Override
	public void setSignataireId(long signataireId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_signataireId = signataireId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getSignataireName() {
		if (_signataireName == null) {
			return "";
		}
		else {
			return _signataireName;
		}
	}

	@Override
	public void setSignataireName(String signataireName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_signataireName = signataireName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSignataireName() {
		return getColumnOriginalValue("signataireName");
	}

	@JSON
	@Override
	public String getSignataireFirstname() {
		if (_signataireFirstname == null) {
			return "";
		}
		else {
			return _signataireFirstname;
		}
	}

	@Override
	public void setSignataireFirstname(String signataireFirstname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_signataireFirstname = signataireFirstname;
	}

	@JSON
	@Override
	public Date getBirthday() {
		return _birthday;
	}

	@Override
	public void setBirthday(Date birthday) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthday = birthday;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getMail() {
		if (_mail == null) {
			return "";
		}
		else {
			return _mail;
		}
	}

	@Override
	public void setMail(String mail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mail = mail;
	}

	@JSON
	@Override
	public long getPostalCode() {
		return _postalCode;
	}

	@Override
	public void setPostalCode(long postalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postalCode = postalCode;
	}

	@JSON
	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return "";
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobilePhone = mobilePhone;
	}

	@JSON
	@Override
	public String getPhone() {
		if (_phone == null) {
			return "";
		}
		else {
			return _phone;
		}
	}

	@Override
	public void setPhone(String phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phone = phone;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public Date getSignatureDate() {
		return _signatureDate;
	}

	@Override
	public void setSignatureDate(Date signatureDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_signatureDate = signatureDate;
	}

	@JSON
	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@JSON
	@Override
	public long getPetitionId() {
		return _petitionId;
	}

	@Override
	public void setPetitionId(long petitionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petitionId = petitionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPetitionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("petitionId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Signataire.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Signataire.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Signataire toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Signataire>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SignataireImpl signataireImpl = new SignataireImpl();

		signataireImpl.setUuid(getUuid());
		signataireImpl.setSignataireId(getSignataireId());
		signataireImpl.setGroupId(getGroupId());
		signataireImpl.setCompanyId(getCompanyId());
		signataireImpl.setUserId(getUserId());
		signataireImpl.setUserName(getUserName());
		signataireImpl.setCreateDate(getCreateDate());
		signataireImpl.setModifiedDate(getModifiedDate());
		signataireImpl.setStatus(getStatus());
		signataireImpl.setStatusByUserId(getStatusByUserId());
		signataireImpl.setStatusByUserName(getStatusByUserName());
		signataireImpl.setStatusDate(getStatusDate());
		signataireImpl.setSignataireName(getSignataireName());
		signataireImpl.setSignataireFirstname(getSignataireFirstname());
		signataireImpl.setBirthday(getBirthday());
		signataireImpl.setAddress(getAddress());
		signataireImpl.setMail(getMail());
		signataireImpl.setPostalCode(getPostalCode());
		signataireImpl.setMobilePhone(getMobilePhone());
		signataireImpl.setPhone(getPhone());
		signataireImpl.setCity(getCity());
		signataireImpl.setSignatureDate(getSignatureDate());
		signataireImpl.setPublikUserId(getPublikUserId());
		signataireImpl.setPetitionId(getPetitionId());

		signataireImpl.resetOriginalValues();

		return signataireImpl;
	}

	@Override
	public Signataire cloneWithOriginalValues() {
		SignataireImpl signataireImpl = new SignataireImpl();

		signataireImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		signataireImpl.setSignataireId(
			this.<Long>getColumnOriginalValue("signataireId"));
		signataireImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		signataireImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		signataireImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		signataireImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		signataireImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		signataireImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		signataireImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		signataireImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		signataireImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		signataireImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		signataireImpl.setSignataireName(
			this.<String>getColumnOriginalValue("signataireName"));
		signataireImpl.setSignataireFirstname(
			this.<String>getColumnOriginalValue("signataireFirstname"));
		signataireImpl.setBirthday(
			this.<Date>getColumnOriginalValue("birthday"));
		signataireImpl.setAddress(
			this.<String>getColumnOriginalValue("address"));
		signataireImpl.setMail(this.<String>getColumnOriginalValue("mail"));
		signataireImpl.setPostalCode(
			this.<Long>getColumnOriginalValue("postalCode"));
		signataireImpl.setMobilePhone(
			this.<String>getColumnOriginalValue("mobilePhone"));
		signataireImpl.setPhone(this.<String>getColumnOriginalValue("phone"));
		signataireImpl.setCity(this.<String>getColumnOriginalValue("city"));
		signataireImpl.setSignatureDate(
			this.<Date>getColumnOriginalValue("signatureDate"));
		signataireImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		signataireImpl.setPetitionId(
			this.<Long>getColumnOriginalValue("petitionId"));

		return signataireImpl;
	}

	@Override
	public int compareTo(Signataire signataire) {
		long primaryKey = signataire.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Signataire)) {
			return false;
		}

		Signataire signataire = (Signataire)object;

		long primaryKey = signataire.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Signataire> toCacheModel() {
		SignataireCacheModel signataireCacheModel = new SignataireCacheModel();

		signataireCacheModel.uuid = getUuid();

		String uuid = signataireCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			signataireCacheModel.uuid = null;
		}

		signataireCacheModel.signataireId = getSignataireId();

		signataireCacheModel.groupId = getGroupId();

		signataireCacheModel.companyId = getCompanyId();

		signataireCacheModel.userId = getUserId();

		signataireCacheModel.userName = getUserName();

		String userName = signataireCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			signataireCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			signataireCacheModel.createDate = createDate.getTime();
		}
		else {
			signataireCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			signataireCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			signataireCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		signataireCacheModel.status = getStatus();

		signataireCacheModel.statusByUserId = getStatusByUserId();

		signataireCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = signataireCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			signataireCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			signataireCacheModel.statusDate = statusDate.getTime();
		}
		else {
			signataireCacheModel.statusDate = Long.MIN_VALUE;
		}

		signataireCacheModel.signataireName = getSignataireName();

		String signataireName = signataireCacheModel.signataireName;

		if ((signataireName != null) && (signataireName.length() == 0)) {
			signataireCacheModel.signataireName = null;
		}

		signataireCacheModel.signataireFirstname = getSignataireFirstname();

		String signataireFirstname = signataireCacheModel.signataireFirstname;

		if ((signataireFirstname != null) &&
			(signataireFirstname.length() == 0)) {

			signataireCacheModel.signataireFirstname = null;
		}

		Date birthday = getBirthday();

		if (birthday != null) {
			signataireCacheModel.birthday = birthday.getTime();
		}
		else {
			signataireCacheModel.birthday = Long.MIN_VALUE;
		}

		signataireCacheModel.address = getAddress();

		String address = signataireCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			signataireCacheModel.address = null;
		}

		signataireCacheModel.mail = getMail();

		String mail = signataireCacheModel.mail;

		if ((mail != null) && (mail.length() == 0)) {
			signataireCacheModel.mail = null;
		}

		signataireCacheModel.postalCode = getPostalCode();

		signataireCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = signataireCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			signataireCacheModel.mobilePhone = null;
		}

		signataireCacheModel.phone = getPhone();

		String phone = signataireCacheModel.phone;

		if ((phone != null) && (phone.length() == 0)) {
			signataireCacheModel.phone = null;
		}

		signataireCacheModel.city = getCity();

		String city = signataireCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			signataireCacheModel.city = null;
		}

		Date signatureDate = getSignatureDate();

		if (signatureDate != null) {
			signataireCacheModel.signatureDate = signatureDate.getTime();
		}
		else {
			signataireCacheModel.signatureDate = Long.MIN_VALUE;
		}

		signataireCacheModel.publikUserId = getPublikUserId();

		String publikUserId = signataireCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			signataireCacheModel.publikUserId = null;
		}

		signataireCacheModel.petitionId = getPetitionId();

		return signataireCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Signataire, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Signataire, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Signataire, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Signataire)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Signataire>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Signataire.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _signataireId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _signataireName;
	private String _signataireFirstname;
	private Date _birthday;
	private String _address;
	private String _mail;
	private long _postalCode;
	private String _mobilePhone;
	private String _phone;
	private String _city;
	private Date _signatureDate;
	private String _publikUserId;
	private long _petitionId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Signataire, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Signataire)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("signataireId", _signataireId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("signataireName", _signataireName);
		_columnOriginalValues.put("signataireFirstname", _signataireFirstname);
		_columnOriginalValues.put("birthday", _birthday);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("mail", _mail);
		_columnOriginalValues.put("postalCode", _postalCode);
		_columnOriginalValues.put("mobilePhone", _mobilePhone);
		_columnOriginalValues.put("phone", _phone);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("signatureDate", _signatureDate);
		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put("petitionId", _petitionId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("signataireId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("signataireName", 4096L);

		columnBitmasks.put("signataireFirstname", 8192L);

		columnBitmasks.put("birthday", 16384L);

		columnBitmasks.put("address", 32768L);

		columnBitmasks.put("mail", 65536L);

		columnBitmasks.put("postalCode", 131072L);

		columnBitmasks.put("mobilePhone", 262144L);

		columnBitmasks.put("phone", 524288L);

		columnBitmasks.put("city", 1048576L);

		columnBitmasks.put("signatureDate", 2097152L);

		columnBitmasks.put("publikUserId", 4194304L);

		columnBitmasks.put("petitionId", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Signataire _escapedModel;

}