/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.csmap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import eu.strasbourg.service.csmap.model.Agenda;
import eu.strasbourg.service.csmap.model.AgendaModel;

import java.io.Serializable;
import java.lang.reflect.InvocationHandler;
import java.sql.Blob;
import java.sql.Types;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Agenda service. Represents a row in the &quot;csmap_Agenda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AgendaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgendaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AgendaImpl
 * @generated
 */
public class AgendaModelImpl
	extends BaseModelImpl<Agenda> implements AgendaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agenda model instance should use the <code>Agenda</code> interface instead.
	 */
	public static final String TABLE_NAME = "csmap_Agenda";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"agendaId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"editorialTitle", Types.VARCHAR},
		{"subtitle", Types.VARCHAR}, {"imageId", Types.BIGINT},
		{"labelLink", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"publicationStartDate", Types.TIMESTAMP},
		{"publicationEndDate", Types.TIMESTAMP}, {"isPrincipal", Types.BOOLEAN},
		{"isActive", Types.BOOLEAN}, {"campaignsIds", Types.VARCHAR},
		{"themesIds", Types.VARCHAR}, {"typesIds", Types.VARCHAR},
		{"territoriesIds", Types.VARCHAR}, {"tags", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agendaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("editorialTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subtitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("labelLink", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicationStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publicationEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isPrincipal", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("campaignsIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("themesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("territoriesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tags", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table csmap_Agenda (uuid_ VARCHAR(75) null,agendaId LONG not null primary key,title STRING null,editorialTitle STRING null,subtitle STRING null,imageId LONG,labelLink STRING null,link STRING null,publicationStartDate DATE null,publicationEndDate DATE null,isPrincipal BOOLEAN,isActive BOOLEAN,campaignsIds STRING null,themesIds STRING null,typesIds STRING null,territoriesIds STRING null,tags STRING null)";

	public static final String TABLE_SQL_DROP = "drop table csmap_Agenda";

	public static final String ORDER_BY_JPQL = " ORDER BY agenda.agendaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY csmap_Agenda.agendaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISPRINCIPAL_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGENDAID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AgendaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _agendaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAgendaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _agendaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Agenda.class;
	}

	@Override
	public String getModelClassName() {
		return Agenda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Agenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Agenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Agenda, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Agenda)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Agenda, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Agenda, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Agenda)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Agenda, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Agenda, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Agenda, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Agenda, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Agenda, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Agenda, Object>>();
		Map<String, BiConsumer<Agenda, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Agenda, ?>>();

		attributeGetterFunctions.put("uuid", Agenda::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Agenda, String>)Agenda::setUuid);
		attributeGetterFunctions.put("agendaId", Agenda::getAgendaId);
		attributeSetterBiConsumers.put(
			"agendaId", (BiConsumer<Agenda, Long>)Agenda::setAgendaId);
		attributeGetterFunctions.put("title", Agenda::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Agenda, String>)Agenda::setTitle);
		attributeGetterFunctions.put(
			"editorialTitle", Agenda::getEditorialTitle);
		attributeSetterBiConsumers.put(
			"editorialTitle",
			(BiConsumer<Agenda, String>)Agenda::setEditorialTitle);
		attributeGetterFunctions.put("subtitle", Agenda::getSubtitle);
		attributeSetterBiConsumers.put(
			"subtitle", (BiConsumer<Agenda, String>)Agenda::setSubtitle);
		attributeGetterFunctions.put("imageId", Agenda::getImageId);
		attributeSetterBiConsumers.put(
			"imageId", (BiConsumer<Agenda, Long>)Agenda::setImageId);
		attributeGetterFunctions.put("labelLink", Agenda::getLabelLink);
		attributeSetterBiConsumers.put(
			"labelLink", (BiConsumer<Agenda, String>)Agenda::setLabelLink);
		attributeGetterFunctions.put("link", Agenda::getLink);
		attributeSetterBiConsumers.put(
			"link", (BiConsumer<Agenda, String>)Agenda::setLink);
		attributeGetterFunctions.put(
			"publicationStartDate", Agenda::getPublicationStartDate);
		attributeSetterBiConsumers.put(
			"publicationStartDate",
			(BiConsumer<Agenda, Date>)Agenda::setPublicationStartDate);
		attributeGetterFunctions.put(
			"publicationEndDate", Agenda::getPublicationEndDate);
		attributeSetterBiConsumers.put(
			"publicationEndDate",
			(BiConsumer<Agenda, Date>)Agenda::setPublicationEndDate);
		attributeGetterFunctions.put("isPrincipal", Agenda::getIsPrincipal);
		attributeSetterBiConsumers.put(
			"isPrincipal", (BiConsumer<Agenda, Boolean>)Agenda::setIsPrincipal);
		attributeGetterFunctions.put("isActive", Agenda::getIsActive);
		attributeSetterBiConsumers.put(
			"isActive", (BiConsumer<Agenda, Boolean>)Agenda::setIsActive);
		attributeGetterFunctions.put("campaignsIds", Agenda::getCampaignsIds);
		attributeSetterBiConsumers.put(
			"campaignsIds",
			(BiConsumer<Agenda, String>)Agenda::setCampaignsIds);
		attributeGetterFunctions.put("themesIds", Agenda::getThemesIds);
		attributeSetterBiConsumers.put(
			"themesIds", (BiConsumer<Agenda, String>)Agenda::setThemesIds);
		attributeGetterFunctions.put("typesIds", Agenda::getTypesIds);
		attributeSetterBiConsumers.put(
			"typesIds", (BiConsumer<Agenda, String>)Agenda::setTypesIds);
		attributeGetterFunctions.put(
			"territoriesIds", Agenda::getTerritoriesIds);
		attributeSetterBiConsumers.put(
			"territoriesIds",
			(BiConsumer<Agenda, String>)Agenda::setTerritoriesIds);
		attributeGetterFunctions.put("tags", Agenda::getTags);
		attributeSetterBiConsumers.put(
			"tags", (BiConsumer<Agenda, String>)Agenda::setTags);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAgendaId() {
		return _agendaId;
	}

	@Override
	public void setAgendaId(long agendaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agendaId = agendaId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getEditorialTitle() {
		if (_editorialTitle == null) {
			return "";
		}
		else {
			return _editorialTitle;
		}
	}

	@Override
	public String getEditorialTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getEditorialTitle(languageId);
	}

	@Override
	public String getEditorialTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getEditorialTitle(languageId, useDefault);
	}

	@Override
	public String getEditorialTitle(String languageId) {
		return LocalizationUtil.getLocalization(
			getEditorialTitle(), languageId);
	}

	@Override
	public String getEditorialTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getEditorialTitle(), languageId, useDefault);
	}

	@Override
	public String getEditorialTitleCurrentLanguageId() {
		return _editorialTitleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getEditorialTitleCurrentValue() {
		Locale locale = getLocale(_editorialTitleCurrentLanguageId);

		return getEditorialTitle(locale);
	}

	@Override
	public Map<Locale, String> getEditorialTitleMap() {
		return LocalizationUtil.getLocalizationMap(getEditorialTitle());
	}

	@Override
	public void setEditorialTitle(String editorialTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_editorialTitle = editorialTitle;
	}

	@Override
	public void setEditorialTitle(String editorialTitle, Locale locale) {
		setEditorialTitle(editorialTitle, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setEditorialTitle(
		String editorialTitle, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(editorialTitle)) {
			setEditorialTitle(
				LocalizationUtil.updateLocalization(
					getEditorialTitle(), "EditorialTitle", editorialTitle,
					languageId, defaultLanguageId));
		}
		else {
			setEditorialTitle(
				LocalizationUtil.removeLocalization(
					getEditorialTitle(), "EditorialTitle", languageId));
		}
	}

	@Override
	public void setEditorialTitleCurrentLanguageId(String languageId) {
		_editorialTitleCurrentLanguageId = languageId;
	}

	@Override
	public void setEditorialTitleMap(Map<Locale, String> editorialTitleMap) {
		setEditorialTitleMap(editorialTitleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setEditorialTitleMap(
		Map<Locale, String> editorialTitleMap, Locale defaultLocale) {

		if (editorialTitleMap == null) {
			return;
		}

		setEditorialTitle(
			LocalizationUtil.updateLocalization(
				editorialTitleMap, getEditorialTitle(), "EditorialTitle",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getSubtitle() {
		if (_subtitle == null) {
			return "";
		}
		else {
			return _subtitle;
		}
	}

	@Override
	public String getSubtitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSubtitle(languageId);
	}

	@Override
	public String getSubtitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSubtitle(languageId, useDefault);
	}

	@Override
	public String getSubtitle(String languageId) {
		return LocalizationUtil.getLocalization(getSubtitle(), languageId);
	}

	@Override
	public String getSubtitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getSubtitle(), languageId, useDefault);
	}

	@Override
	public String getSubtitleCurrentLanguageId() {
		return _subtitleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getSubtitleCurrentValue() {
		Locale locale = getLocale(_subtitleCurrentLanguageId);

		return getSubtitle(locale);
	}

	@Override
	public Map<Locale, String> getSubtitleMap() {
		return LocalizationUtil.getLocalizationMap(getSubtitle());
	}

	@Override
	public void setSubtitle(String subtitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subtitle = subtitle;
	}

	@Override
	public void setSubtitle(String subtitle, Locale locale) {
		setSubtitle(subtitle, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setSubtitle(
		String subtitle, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(subtitle)) {
			setSubtitle(
				LocalizationUtil.updateLocalization(
					getSubtitle(), "Subtitle", subtitle, languageId,
					defaultLanguageId));
		}
		else {
			setSubtitle(
				LocalizationUtil.removeLocalization(
					getSubtitle(), "Subtitle", languageId));
		}
	}

	@Override
	public void setSubtitleCurrentLanguageId(String languageId) {
		_subtitleCurrentLanguageId = languageId;
	}

	@Override
	public void setSubtitleMap(Map<Locale, String> subtitleMap) {
		setSubtitleMap(subtitleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setSubtitleMap(
		Map<Locale, String> subtitleMap, Locale defaultLocale) {

		if (subtitleMap == null) {
			return;
		}

		setSubtitle(
			LocalizationUtil.updateLocalization(
				subtitleMap, getSubtitle(), "Subtitle",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(Long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@Override
	public String getLabelLink() {
		if (_labelLink == null) {
			return "";
		}
		else {
			return _labelLink;
		}
	}

	@Override
	public String getLabelLink(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLabelLink(languageId);
	}

	@Override
	public String getLabelLink(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLabelLink(languageId, useDefault);
	}

	@Override
	public String getLabelLink(String languageId) {
		return LocalizationUtil.getLocalization(getLabelLink(), languageId);
	}

	@Override
	public String getLabelLink(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getLabelLink(), languageId, useDefault);
	}

	@Override
	public String getLabelLinkCurrentLanguageId() {
		return _labelLinkCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLabelLinkCurrentValue() {
		Locale locale = getLocale(_labelLinkCurrentLanguageId);

		return getLabelLink(locale);
	}

	@Override
	public Map<Locale, String> getLabelLinkMap() {
		return LocalizationUtil.getLocalizationMap(getLabelLink());
	}

	@Override
	public void setLabelLink(String labelLink) {
		_labelLink = labelLink;
	}

	@Override
	public void setLabelLink(String labelLink, Locale locale) {
		setLabelLink(labelLink, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setLabelLink(
		String labelLink, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(labelLink)) {
			setLabelLink(
				LocalizationUtil.updateLocalization(
					getLabelLink(), "LabelLink", labelLink, languageId,
					defaultLanguageId));
		}
		else {
			setLabelLink(
				LocalizationUtil.removeLocalization(
					getLabelLink(), "LabelLink", languageId));
		}
	}

	@Override
	public void setLabelLinkCurrentLanguageId(String languageId) {
		_labelLinkCurrentLanguageId = languageId;
	}

	@Override
	public void setLabelLinkMap(Map<Locale, String> labelLinkMap) {
		setLabelLinkMap(labelLinkMap, LocaleUtil.getDefault());
	}

	@Override
	public void setLabelLinkMap(
		Map<Locale, String> labelLinkMap, Locale defaultLocale) {

		if (labelLinkMap == null) {
			return;
		}

		setLabelLink(
			LocalizationUtil.updateLocalization(
				labelLinkMap, getLabelLink(), "LabelLink",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public String getLink(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLink(languageId);
	}

	@Override
	public String getLink(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getLink(languageId, useDefault);
	}

	@Override
	public String getLink(String languageId) {
		return LocalizationUtil.getLocalization(getLink(), languageId);
	}

	@Override
	public String getLink(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getLink(), languageId, useDefault);
	}

	@Override
	public String getLinkCurrentLanguageId() {
		return _linkCurrentLanguageId;
	}

	@JSON
	@Override
	public String getLinkCurrentValue() {
		Locale locale = getLocale(_linkCurrentLanguageId);

		return getLink(locale);
	}

	@Override
	public Map<Locale, String> getLinkMap() {
		return LocalizationUtil.getLocalizationMap(getLink());
	}

	@Override
	public void setLink(String link) {
		_link = link;
	}

	@Override
	public void setLink(String link, Locale locale) {
		setLink(link, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setLink(String link, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(link)) {
			setLink(
				LocalizationUtil.updateLocalization(
					getLink(), "Link", link, languageId, defaultLanguageId));
		}
		else {
			setLink(
				LocalizationUtil.removeLocalization(
					getLink(), "Link", languageId));
		}
	}

	@Override
	public void setLinkCurrentLanguageId(String languageId) {
		_linkCurrentLanguageId = languageId;
	}

	@Override
	public void setLinkMap(Map<Locale, String> linkMap) {
		setLinkMap(linkMap, LocaleUtil.getDefault());
	}

	@Override
	public void setLinkMap(Map<Locale, String> linkMap, Locale defaultLocale) {
		if (linkMap == null) {
			return;
		}

		setLink(
			LocalizationUtil.updateLocalization(
				linkMap, getLink(), "Link",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Date getPublicationStartDate() {
		return _publicationStartDate;
	}

	@Override
	public void setPublicationStartDate(Date publicationStartDate) {
		_publicationStartDate = publicationStartDate;
	}

	@Override
	public Date getPublicationEndDate() {
		return _publicationEndDate;
	}

	@Override
	public void setPublicationEndDate(Date publicationEndDate) {
		_publicationEndDate = publicationEndDate;
	}

	@Override
	public Boolean getIsPrincipal() {
		return _isPrincipal;
	}

	@Override
	public void setIsPrincipal(Boolean isPrincipal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isPrincipal = isPrincipal;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalIsPrincipal() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isPrincipal"));
	}

	@Override
	public Boolean getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(Boolean isActive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isActive = isActive;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalIsActive() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isActive"));
	}

	@Override
	public String getCampaignsIds() {
		if (_campaignsIds == null) {
			return "";
		}
		else {
			return _campaignsIds;
		}
	}

	@Override
	public void setCampaignsIds(String campaignsIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_campaignsIds = campaignsIds;
	}

	@Override
	public String getThemesIds() {
		if (_themesIds == null) {
			return "";
		}
		else {
			return _themesIds;
		}
	}

	@Override
	public void setThemesIds(String themesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themesIds = themesIds;
	}

	@Override
	public String getTypesIds() {
		if (_typesIds == null) {
			return "";
		}
		else {
			return _typesIds;
		}
	}

	@Override
	public void setTypesIds(String typesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typesIds = typesIds;
	}

	@Override
	public String getTerritoriesIds() {
		if (_territoriesIds == null) {
			return "";
		}
		else {
			return _territoriesIds;
		}
	}

	@Override
	public void setTerritoriesIds(String territoriesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_territoriesIds = territoriesIds;
	}

	@Override
	public String getTags() {
		if (_tags == null) {
			return "";
		}
		else {
			return _tags;
		}
	}

	@Override
	public void setTags(String tags) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tags = tags;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Agenda.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> editorialTitleMap = getEditorialTitleMap();

		for (Map.Entry<Locale, String> entry : editorialTitleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> subtitleMap = getSubtitleMap();

		for (Map.Entry<Locale, String> entry : subtitleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> labelLinkMap = getLabelLinkMap();

		for (Map.Entry<Locale, String> entry : labelLinkMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> linkMap = getLinkMap();

		for (Map.Entry<Locale, String> entry : linkMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Agenda.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String editorialTitle = getEditorialTitle(defaultLocale);

		if (Validator.isNull(editorialTitle)) {
			setEditorialTitle(
				getEditorialTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setEditorialTitle(
				getEditorialTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String subtitle = getSubtitle(defaultLocale);

		if (Validator.isNull(subtitle)) {
			setSubtitle(getSubtitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setSubtitle(
				getSubtitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String labelLink = getLabelLink(defaultLocale);

		if (Validator.isNull(labelLink)) {
			setLabelLink(getLabelLink(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLabelLink(
				getLabelLink(defaultLocale), defaultLocale, defaultLocale);
		}

		String link = getLink(defaultLocale);

		if (Validator.isNull(link)) {
			setLink(getLink(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setLink(getLink(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Agenda toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Agenda>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AgendaImpl agendaImpl = new AgendaImpl();

		agendaImpl.setUuid(getUuid());
		agendaImpl.setAgendaId(getAgendaId());
		agendaImpl.setTitle(getTitle());
		agendaImpl.setEditorialTitle(getEditorialTitle());
		agendaImpl.setSubtitle(getSubtitle());
		agendaImpl.setImageId(getImageId());
		agendaImpl.setLabelLink(getLabelLink());
		agendaImpl.setLink(getLink());
		agendaImpl.setPublicationStartDate(getPublicationStartDate());
		agendaImpl.setPublicationEndDate(getPublicationEndDate());
		agendaImpl.setIsPrincipal(getIsPrincipal());
		agendaImpl.setIsActive(getIsActive());
		agendaImpl.setCampaignsIds(getCampaignsIds());
		agendaImpl.setThemesIds(getThemesIds());
		agendaImpl.setTypesIds(getTypesIds());
		agendaImpl.setTerritoriesIds(getTerritoriesIds());
		agendaImpl.setTags(getTags());

		agendaImpl.resetOriginalValues();

		return agendaImpl;
	}

	@Override
	public Agenda cloneWithOriginalValues() {
		AgendaImpl agendaImpl = new AgendaImpl();

		agendaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		agendaImpl.setAgendaId(this.<Long>getColumnOriginalValue("agendaId"));
		agendaImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		agendaImpl.setEditorialTitle(
			this.<String>getColumnOriginalValue("editorialTitle"));
		agendaImpl.setSubtitle(this.<String>getColumnOriginalValue("subtitle"));
		agendaImpl.setImageId(this.<Long>getColumnOriginalValue("imageId"));
		agendaImpl.setIsPrincipal(
			this.<Boolean>getColumnOriginalValue("isPrincipal"));
		agendaImpl.setIsActive(
			this.<Boolean>getColumnOriginalValue("isActive"));
		agendaImpl.setCampaignsIds(
			this.<String>getColumnOriginalValue("campaignsIds"));
		agendaImpl.setThemesIds(
			this.<String>getColumnOriginalValue("themesIds"));
		agendaImpl.setTypesIds(this.<String>getColumnOriginalValue("typesIds"));
		agendaImpl.setTerritoriesIds(
			this.<String>getColumnOriginalValue("territoriesIds"));
		agendaImpl.setTags(this.<String>getColumnOriginalValue("tags"));

		return agendaImpl;
	}

	@Override
	public int compareTo(Agenda agenda) {
		long primaryKey = agenda.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Agenda)) {
			return false;
		}

		Agenda agenda = (Agenda)object;

		long primaryKey = agenda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Agenda> toCacheModel() {
		AgendaCacheModel agendaCacheModel = new AgendaCacheModel();

		agendaCacheModel.uuid = getUuid();

		String uuid = agendaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			agendaCacheModel.uuid = null;
		}

		agendaCacheModel.agendaId = getAgendaId();

		agendaCacheModel.title = getTitle();

		String title = agendaCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			agendaCacheModel.title = null;
		}

		agendaCacheModel.editorialTitle = getEditorialTitle();

		String editorialTitle = agendaCacheModel.editorialTitle;

		if ((editorialTitle != null) && (editorialTitle.length() == 0)) {
			agendaCacheModel.editorialTitle = null;
		}

		agendaCacheModel.subtitle = getSubtitle();

		String subtitle = agendaCacheModel.subtitle;

		if ((subtitle != null) && (subtitle.length() == 0)) {
			agendaCacheModel.subtitle = null;
		}

		Long imageId = getImageId();

		if (imageId != null) {
			agendaCacheModel.imageId = imageId;
		}

		agendaCacheModel.labelLink = getLabelLink();

		String labelLink = agendaCacheModel.labelLink;

		if ((labelLink != null) && (labelLink.length() == 0)) {
			agendaCacheModel.labelLink = null;
		}

		agendaCacheModel.link = getLink();

		String link = agendaCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			agendaCacheModel.link = null;
		}

		Date publicationStartDate = getPublicationStartDate();

		if (publicationStartDate != null) {
			agendaCacheModel.publicationStartDate =
				publicationStartDate.getTime();
		}
		else {
			agendaCacheModel.publicationStartDate = Long.MIN_VALUE;
		}

		Date publicationEndDate = getPublicationEndDate();

		if (publicationEndDate != null) {
			agendaCacheModel.publicationEndDate = publicationEndDate.getTime();
		}
		else {
			agendaCacheModel.publicationEndDate = Long.MIN_VALUE;
		}

		Boolean isPrincipal = getIsPrincipal();

		if (isPrincipal != null) {
			agendaCacheModel.isPrincipal = isPrincipal;
		}

		Boolean isActive = getIsActive();

		if (isActive != null) {
			agendaCacheModel.isActive = isActive;
		}

		agendaCacheModel.campaignsIds = getCampaignsIds();

		String campaignsIds = agendaCacheModel.campaignsIds;

		if ((campaignsIds != null) && (campaignsIds.length() == 0)) {
			agendaCacheModel.campaignsIds = null;
		}

		agendaCacheModel.themesIds = getThemesIds();

		String themesIds = agendaCacheModel.themesIds;

		if ((themesIds != null) && (themesIds.length() == 0)) {
			agendaCacheModel.themesIds = null;
		}

		agendaCacheModel.typesIds = getTypesIds();

		String typesIds = agendaCacheModel.typesIds;

		if ((typesIds != null) && (typesIds.length() == 0)) {
			agendaCacheModel.typesIds = null;
		}

		agendaCacheModel.territoriesIds = getTerritoriesIds();

		String territoriesIds = agendaCacheModel.territoriesIds;

		if ((territoriesIds != null) && (territoriesIds.length() == 0)) {
			agendaCacheModel.territoriesIds = null;
		}

		agendaCacheModel.tags = getTags();

		String tags = agendaCacheModel.tags;

		if ((tags != null) && (tags.length() == 0)) {
			agendaCacheModel.tags = null;
		}

		return agendaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Agenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Agenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Agenda, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Agenda)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Agenda>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Agenda.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _agendaId;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _editorialTitle;
	private String _editorialTitleCurrentLanguageId;
	private String _subtitle;
	private String _subtitleCurrentLanguageId;
	private Long _imageId;
	private String _labelLink;
	private String _labelLinkCurrentLanguageId;
	private String _link;
	private String _linkCurrentLanguageId;
	private Date _publicationStartDate;
	private Date _publicationEndDate;
	private Boolean _isPrincipal;
	private Boolean _isActive;
	private String _campaignsIds;
	private String _themesIds;
	private String _typesIds;
	private String _territoriesIds;
	private String _tags;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Agenda, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Agenda)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("agendaId", _agendaId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("editorialTitle", _editorialTitle);
		_columnOriginalValues.put("subtitle", _subtitle);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("isPrincipal", _isPrincipal);
		_columnOriginalValues.put("isActive", _isActive);
		_columnOriginalValues.put("campaignsIds", _campaignsIds);
		_columnOriginalValues.put("themesIds", _themesIds);
		_columnOriginalValues.put("typesIds", _typesIds);
		_columnOriginalValues.put("territoriesIds", _territoriesIds);
		_columnOriginalValues.put("tags", _tags);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("agendaId", 2L);

		columnBitmasks.put("title", 4L);

		columnBitmasks.put("editorialTitle", 8L);

		columnBitmasks.put("subtitle", 16L);

		columnBitmasks.put("imageId", 32L);

		columnBitmasks.put("isPrincipal", 64L);

		columnBitmasks.put("isActive", 128L);

		columnBitmasks.put("campaignsIds", 256L);

		columnBitmasks.put("themesIds", 512L);

		columnBitmasks.put("typesIds", 1024L);

		columnBitmasks.put("territoriesIds", 2048L);

		columnBitmasks.put("tags", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Agenda _escapedModel;

}