/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.formSendRecordField.model.impl;

import eu.strasbourg.service.formSendRecordField.model.FormSendRecordFieldSignalement;
import eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementLocalServiceUtil;

/**
 * The extended model base implementation for the FormSendRecordFieldSignalement service. Represents a row in the &quot;formSendRecordField_FormSendRecordFieldSignalement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormSendRecordFieldSignalementImpl}.
 * </p>
 *
 * @author Angélique Zunino
 * @see FormSendRecordFieldSignalementImpl
 * @see FormSendRecordFieldSignalement
 * @generated
 */
public abstract class FormSendRecordFieldSignalementBaseImpl
	extends FormSendRecordFieldSignalementModelImpl
	implements FormSendRecordFieldSignalement {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form send record field signalement model instance should use the <code>FormSendRecordFieldSignalement</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FormSendRecordFieldSignalementLocalServiceUtil.
				addFormSendRecordFieldSignalement(this);
		}
		else {
			FormSendRecordFieldSignalementLocalServiceUtil.
				updateFormSendRecordFieldSignalement(this);
		}
	}

}