/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.council.model.impl;

import eu.strasbourg.service.council.model.CouncilSession;
import eu.strasbourg.service.council.service.CouncilSessionLocalServiceUtil;

/**
 * The extended model base implementation for the CouncilSession service. Represents a row in the &quot;council_CouncilSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CouncilSessionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CouncilSessionImpl
 * @see CouncilSession
 * @generated
 */
public abstract class CouncilSessionBaseImpl
	extends CouncilSessionModelImpl implements CouncilSession {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a council session model instance should use the <code>CouncilSession</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CouncilSessionLocalServiceUtil.addCouncilSession(this);
		}
		else {
			CouncilSessionLocalServiceUtil.updateCouncilSession(this);
		}
	}

}