/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.council.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.council.model.CouncilSession;
import eu.strasbourg.service.council.model.CouncilSessionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CouncilSession service. Represents a row in the &quot;council_CouncilSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CouncilSessionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CouncilSessionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CouncilSessionImpl
 * @generated
 */
public class CouncilSessionModelImpl
	extends BaseModelImpl<CouncilSession> implements CouncilSessionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a council session model instance should use the <code>CouncilSession</code> interface instead.
	 */
	public static final String TABLE_NAME = "council_CouncilSession";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"councilSessionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"date_", Types.TIMESTAMP},
		{"lastDelibProcessed", Types.BIGINT},
		{"officialLeaderId", Types.BIGINT}, {"typeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("councilSessionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastDelibProcessed", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("officialLeaderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table council_CouncilSession (uuid_ VARCHAR(75) null,councilSessionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(75) null,date_ DATE null,lastDelibProcessed LONG,officialLeaderId LONG,typeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table council_CouncilSession";

	public static final String ORDER_BY_JPQL =
		" ORDER BY councilSession.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY council_CouncilSession.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.council.service.util.ServiceProps.get(
			"lock.expiration.time.eu.strasbourg.service.council.model.CouncilSession"));

	public CouncilSessionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _councilSessionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCouncilSessionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _councilSessionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CouncilSession.class;
	}

	@Override
	public String getModelClassName() {
		return CouncilSession.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CouncilSession, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CouncilSession, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CouncilSession, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CouncilSession)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CouncilSession, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CouncilSession, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CouncilSession)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CouncilSession, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CouncilSession, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CouncilSession, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CouncilSession, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CouncilSession, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CouncilSession, Object>>();
		Map<String, BiConsumer<CouncilSession, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CouncilSession, ?>>();

		attributeGetterFunctions.put("uuid", CouncilSession::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CouncilSession, String>)CouncilSession::setUuid);
		attributeGetterFunctions.put(
			"councilSessionId", CouncilSession::getCouncilSessionId);
		attributeSetterBiConsumers.put(
			"councilSessionId",
			(BiConsumer<CouncilSession, Long>)
				CouncilSession::setCouncilSessionId);
		attributeGetterFunctions.put("groupId", CouncilSession::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CouncilSession, Long>)CouncilSession::setGroupId);
		attributeGetterFunctions.put("companyId", CouncilSession::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CouncilSession, Long>)CouncilSession::setCompanyId);
		attributeGetterFunctions.put("userId", CouncilSession::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CouncilSession, Long>)CouncilSession::setUserId);
		attributeGetterFunctions.put("userName", CouncilSession::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CouncilSession, String>)CouncilSession::setUserName);
		attributeGetterFunctions.put(
			"createDate", CouncilSession::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CouncilSession, Date>)CouncilSession::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CouncilSession::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CouncilSession, Date>)CouncilSession::setModifiedDate);
		attributeGetterFunctions.put("status", CouncilSession::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<CouncilSession, Integer>)CouncilSession::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", CouncilSession::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<CouncilSession, Long>)
				CouncilSession::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", CouncilSession::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<CouncilSession, String>)
				CouncilSession::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", CouncilSession::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<CouncilSession, Date>)CouncilSession::setStatusDate);
		attributeGetterFunctions.put("title", CouncilSession::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<CouncilSession, String>)CouncilSession::setTitle);
		attributeGetterFunctions.put("date", CouncilSession::getDate);
		attributeSetterBiConsumers.put(
			"date", (BiConsumer<CouncilSession, Date>)CouncilSession::setDate);
		attributeGetterFunctions.put(
			"lastDelibProcessed", CouncilSession::getLastDelibProcessed);
		attributeSetterBiConsumers.put(
			"lastDelibProcessed",
			(BiConsumer<CouncilSession, Long>)
				CouncilSession::setLastDelibProcessed);
		attributeGetterFunctions.put(
			"officialLeaderId", CouncilSession::getOfficialLeaderId);
		attributeSetterBiConsumers.put(
			"officialLeaderId",
			(BiConsumer<CouncilSession, Long>)
				CouncilSession::setOfficialLeaderId);
		attributeGetterFunctions.put("typeId", CouncilSession::getTypeId);
		attributeSetterBiConsumers.put(
			"typeId",
			(BiConsumer<CouncilSession, Long>)CouncilSession::setTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getCouncilSessionId() {
		return _councilSessionId;
	}

	@Override
	public void setCouncilSessionId(long councilSessionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_councilSessionId = councilSessionId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTitle() {
		return getColumnOriginalValue("title");
	}

	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_date = date;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDate() {
		return getColumnOriginalValue("date_");
	}

	@Override
	public long getLastDelibProcessed() {
		return _lastDelibProcessed;
	}

	@Override
	public void setLastDelibProcessed(long lastDelibProcessed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastDelibProcessed = lastDelibProcessed;
	}

	@Override
	public long getOfficialLeaderId() {
		return _officialLeaderId;
	}

	@Override
	public void setOfficialLeaderId(long officialLeaderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_officialLeaderId = officialLeaderId;
	}

	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeId = typeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTypeId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("typeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CouncilSession.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CouncilSession.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CouncilSession toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CouncilSession>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CouncilSessionImpl councilSessionImpl = new CouncilSessionImpl();

		councilSessionImpl.setUuid(getUuid());
		councilSessionImpl.setCouncilSessionId(getCouncilSessionId());
		councilSessionImpl.setGroupId(getGroupId());
		councilSessionImpl.setCompanyId(getCompanyId());
		councilSessionImpl.setUserId(getUserId());
		councilSessionImpl.setUserName(getUserName());
		councilSessionImpl.setCreateDate(getCreateDate());
		councilSessionImpl.setModifiedDate(getModifiedDate());
		councilSessionImpl.setStatus(getStatus());
		councilSessionImpl.setStatusByUserId(getStatusByUserId());
		councilSessionImpl.setStatusByUserName(getStatusByUserName());
		councilSessionImpl.setStatusDate(getStatusDate());
		councilSessionImpl.setTitle(getTitle());
		councilSessionImpl.setDate(getDate());
		councilSessionImpl.setLastDelibProcessed(getLastDelibProcessed());
		councilSessionImpl.setOfficialLeaderId(getOfficialLeaderId());
		councilSessionImpl.setTypeId(getTypeId());

		councilSessionImpl.resetOriginalValues();

		return councilSessionImpl;
	}

	@Override
	public CouncilSession cloneWithOriginalValues() {
		CouncilSessionImpl councilSessionImpl = new CouncilSessionImpl();

		councilSessionImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		councilSessionImpl.setCouncilSessionId(
			this.<Long>getColumnOriginalValue("councilSessionId"));
		councilSessionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		councilSessionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		councilSessionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		councilSessionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		councilSessionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		councilSessionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		councilSessionImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		councilSessionImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		councilSessionImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		councilSessionImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		councilSessionImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		councilSessionImpl.setDate(this.<Date>getColumnOriginalValue("date_"));
		councilSessionImpl.setLastDelibProcessed(
			this.<Long>getColumnOriginalValue("lastDelibProcessed"));
		councilSessionImpl.setOfficialLeaderId(
			this.<Long>getColumnOriginalValue("officialLeaderId"));
		councilSessionImpl.setTypeId(
			this.<Long>getColumnOriginalValue("typeId"));

		return councilSessionImpl;
	}

	@Override
	public int compareTo(CouncilSession councilSession) {
		int value = 0;

		value = getTitle().compareTo(councilSession.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CouncilSession)) {
			return false;
		}

		CouncilSession councilSession = (CouncilSession)object;

		long primaryKey = councilSession.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CouncilSession> toCacheModel() {
		CouncilSessionCacheModel councilSessionCacheModel =
			new CouncilSessionCacheModel();

		councilSessionCacheModel.uuid = getUuid();

		String uuid = councilSessionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			councilSessionCacheModel.uuid = null;
		}

		councilSessionCacheModel.councilSessionId = getCouncilSessionId();

		councilSessionCacheModel.groupId = getGroupId();

		councilSessionCacheModel.companyId = getCompanyId();

		councilSessionCacheModel.userId = getUserId();

		councilSessionCacheModel.userName = getUserName();

		String userName = councilSessionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			councilSessionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			councilSessionCacheModel.createDate = createDate.getTime();
		}
		else {
			councilSessionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			councilSessionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			councilSessionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		councilSessionCacheModel.status = getStatus();

		councilSessionCacheModel.statusByUserId = getStatusByUserId();

		councilSessionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = councilSessionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			councilSessionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			councilSessionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			councilSessionCacheModel.statusDate = Long.MIN_VALUE;
		}

		councilSessionCacheModel.title = getTitle();

		String title = councilSessionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			councilSessionCacheModel.title = null;
		}

		Date date = getDate();

		if (date != null) {
			councilSessionCacheModel.date = date.getTime();
		}
		else {
			councilSessionCacheModel.date = Long.MIN_VALUE;
		}

		councilSessionCacheModel.lastDelibProcessed = getLastDelibProcessed();

		councilSessionCacheModel.officialLeaderId = getOfficialLeaderId();

		councilSessionCacheModel.typeId = getTypeId();

		return councilSessionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CouncilSession, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CouncilSession, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CouncilSession, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CouncilSession)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CouncilSession>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CouncilSession.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _councilSessionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private Date _date;
	private long _lastDelibProcessed;
	private long _officialLeaderId;
	private long _typeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CouncilSession, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CouncilSession)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("councilSessionId", _councilSessionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("date_", _date);
		_columnOriginalValues.put("lastDelibProcessed", _lastDelibProcessed);
		_columnOriginalValues.put("officialLeaderId", _officialLeaderId);
		_columnOriginalValues.put("typeId", _typeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("date_", "date");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("councilSessionId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("title", 4096L);

		columnBitmasks.put("date_", 8192L);

		columnBitmasks.put("lastDelibProcessed", 16384L);

		columnBitmasks.put("officialLeaderId", 32768L);

		columnBitmasks.put("typeId", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CouncilSession _escapedModel;

}