/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.council.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import eu.strasbourg.service.council.model.OfficialTypeCouncil;
import eu.strasbourg.service.council.model.OfficialTypeCouncilModel;
import eu.strasbourg.service.council.service.persistence.OfficialTypeCouncilPK;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OfficialTypeCouncil service. Represents a row in the &quot;council_OfficialTypeCouncil&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OfficialTypeCouncilModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfficialTypeCouncilImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OfficialTypeCouncilImpl
 * @generated
 */
public class OfficialTypeCouncilModelImpl
	extends BaseModelImpl<OfficialTypeCouncil>
	implements OfficialTypeCouncilModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a official type council model instance should use the <code>OfficialTypeCouncil</code> interface instead.
	 */
	public static final String TABLE_NAME = "council_OfficialTypeCouncil";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"officialId", Types.BIGINT},
		{"typeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"result", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("officialId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("result", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table council_OfficialTypeCouncil (uuid_ VARCHAR(75) null,officialId LONG not null,typeId LONG not null,groupId LONG,companyId LONG,createDate DATE null,result VARCHAR(75) null,primary key (officialId, typeId))";

	public static final String TABLE_SQL_DROP =
		"drop table council_OfficialTypeCouncil";

	public static final String ORDER_BY_JPQL =
		" ORDER BY officialTypeCouncil.id.officialId ASC, officialTypeCouncil.id.typeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY council_OfficialTypeCouncil.officialId ASC, council_OfficialTypeCouncil.typeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OFFICIALID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.council.service.util.ServiceProps.get(
			"lock.expiration.time.eu.strasbourg.service.council.model.OfficialTypeCouncil"));

	public OfficialTypeCouncilModelImpl() {
	}

	@Override
	public OfficialTypeCouncilPK getPrimaryKey() {
		return new OfficialTypeCouncilPK(_officialId, _typeId);
	}

	@Override
	public void setPrimaryKey(OfficialTypeCouncilPK primaryKey) {
		setOfficialId(primaryKey.officialId);
		setTypeId(primaryKey.typeId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new OfficialTypeCouncilPK(_officialId, _typeId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((OfficialTypeCouncilPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return OfficialTypeCouncil.class;
	}

	@Override
	public String getModelClassName() {
		return OfficialTypeCouncil.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OfficialTypeCouncil, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OfficialTypeCouncil, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfficialTypeCouncil, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OfficialTypeCouncil)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OfficialTypeCouncil, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OfficialTypeCouncil, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OfficialTypeCouncil)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OfficialTypeCouncil, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OfficialTypeCouncil, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OfficialTypeCouncil, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OfficialTypeCouncil, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OfficialTypeCouncil, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<OfficialTypeCouncil, Object>>();
		Map<String, BiConsumer<OfficialTypeCouncil, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<OfficialTypeCouncil, ?>>();

		attributeGetterFunctions.put("uuid", OfficialTypeCouncil::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<OfficialTypeCouncil, String>)
				OfficialTypeCouncil::setUuid);
		attributeGetterFunctions.put(
			"officialId", OfficialTypeCouncil::getOfficialId);
		attributeSetterBiConsumers.put(
			"officialId",
			(BiConsumer<OfficialTypeCouncil, Long>)
				OfficialTypeCouncil::setOfficialId);
		attributeGetterFunctions.put("typeId", OfficialTypeCouncil::getTypeId);
		attributeSetterBiConsumers.put(
			"typeId",
			(BiConsumer<OfficialTypeCouncil, Long>)
				OfficialTypeCouncil::setTypeId);
		attributeGetterFunctions.put(
			"groupId", OfficialTypeCouncil::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<OfficialTypeCouncil, Long>)
				OfficialTypeCouncil::setGroupId);
		attributeGetterFunctions.put(
			"companyId", OfficialTypeCouncil::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<OfficialTypeCouncil, Long>)
				OfficialTypeCouncil::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", OfficialTypeCouncil::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<OfficialTypeCouncil, Date>)
				OfficialTypeCouncil::setCreateDate);
		attributeGetterFunctions.put("result", OfficialTypeCouncil::getResult);
		attributeSetterBiConsumers.put(
			"result",
			(BiConsumer<OfficialTypeCouncil, String>)
				OfficialTypeCouncil::setResult);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getOfficialId() {
		return _officialId;
	}

	@Override
	public void setOfficialId(long officialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_officialId = officialId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOfficialId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("officialId"));
	}

	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeId = typeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTypeId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("typeId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getResult() {
		if (_result == null) {
			return "";
		}
		else {
			return _result;
		}
	}

	@Override
	public void setResult(String result) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_result = result;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public OfficialTypeCouncil toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OfficialTypeCouncil>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfficialTypeCouncilImpl officialTypeCouncilImpl =
			new OfficialTypeCouncilImpl();

		officialTypeCouncilImpl.setUuid(getUuid());
		officialTypeCouncilImpl.setOfficialId(getOfficialId());
		officialTypeCouncilImpl.setTypeId(getTypeId());
		officialTypeCouncilImpl.setGroupId(getGroupId());
		officialTypeCouncilImpl.setCompanyId(getCompanyId());
		officialTypeCouncilImpl.setCreateDate(getCreateDate());
		officialTypeCouncilImpl.setResult(getResult());

		officialTypeCouncilImpl.resetOriginalValues();

		return officialTypeCouncilImpl;
	}

	@Override
	public OfficialTypeCouncil cloneWithOriginalValues() {
		OfficialTypeCouncilImpl officialTypeCouncilImpl =
			new OfficialTypeCouncilImpl();

		officialTypeCouncilImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		officialTypeCouncilImpl.setOfficialId(
			this.<Long>getColumnOriginalValue("officialId"));
		officialTypeCouncilImpl.setTypeId(
			this.<Long>getColumnOriginalValue("typeId"));
		officialTypeCouncilImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		officialTypeCouncilImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		officialTypeCouncilImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		officialTypeCouncilImpl.setResult(
			this.<String>getColumnOriginalValue("result"));

		return officialTypeCouncilImpl;
	}

	@Override
	public int compareTo(OfficialTypeCouncil officialTypeCouncil) {
		OfficialTypeCouncilPK primaryKey = officialTypeCouncil.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OfficialTypeCouncil)) {
			return false;
		}

		OfficialTypeCouncil officialTypeCouncil = (OfficialTypeCouncil)object;

		OfficialTypeCouncilPK primaryKey = officialTypeCouncil.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OfficialTypeCouncil> toCacheModel() {
		OfficialTypeCouncilCacheModel officialTypeCouncilCacheModel =
			new OfficialTypeCouncilCacheModel();

		officialTypeCouncilCacheModel.officialTypeCouncilPK = getPrimaryKey();

		officialTypeCouncilCacheModel.uuid = getUuid();

		String uuid = officialTypeCouncilCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			officialTypeCouncilCacheModel.uuid = null;
		}

		officialTypeCouncilCacheModel.officialId = getOfficialId();

		officialTypeCouncilCacheModel.typeId = getTypeId();

		officialTypeCouncilCacheModel.groupId = getGroupId();

		officialTypeCouncilCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			officialTypeCouncilCacheModel.createDate = createDate.getTime();
		}
		else {
			officialTypeCouncilCacheModel.createDate = Long.MIN_VALUE;
		}

		officialTypeCouncilCacheModel.result = getResult();

		String result = officialTypeCouncilCacheModel.result;

		if ((result != null) && (result.length() == 0)) {
			officialTypeCouncilCacheModel.result = null;
		}

		return officialTypeCouncilCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OfficialTypeCouncil, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OfficialTypeCouncil, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfficialTypeCouncil, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(OfficialTypeCouncil)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OfficialTypeCouncil>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OfficialTypeCouncil.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _officialId;
	private long _typeId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private String _result;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<OfficialTypeCouncil, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OfficialTypeCouncil)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("officialId", _officialId);
		_columnOriginalValues.put("typeId", _typeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("result", _result);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("officialId", 2L);

		columnBitmasks.put("typeId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("result", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OfficialTypeCouncil _escapedModel;

}