/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.gtfs.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.gtfs.model.Ligne;
import eu.strasbourg.service.gtfs.model.LigneModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Ligne service. Represents a row in the &quot;gtfs_Ligne&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LigneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LigneImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see LigneImpl
 * @generated
 */
@JSON(strict = true)
public class LigneModelImpl extends BaseModelImpl<Ligne> implements LigneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ligne model instance should use the <code>Ligne</code> interface instead.
	 */
	public static final String TABLE_NAME = "gtfs_Ligne";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ligneId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"routeId", Types.VARCHAR}, {"shortName", Types.VARCHAR},
		{"title", Types.VARCHAR}, {"type_", Types.INTEGER},
		{"backgroundColor", Types.VARCHAR}, {"textColor", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ligneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("routeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("shortName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("backgroundColor", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("textColor", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table gtfs_Ligne (uuid_ VARCHAR(75) null,ligneId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,routeId VARCHAR(75) null,shortName VARCHAR(75) null,title VARCHAR(75) null,type_ INTEGER,backgroundColor VARCHAR(75) null,textColor VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table gtfs_Ligne";

	public static final String ORDER_BY_JPQL = " ORDER BY ligne.ligneId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY gtfs_Ligne.ligneId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROUTEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SHORTNAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LIGNEID_COLUMN_BITMASK = 64L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.gtfs.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.gtfs.model.Ligne"));

	public LigneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ligneId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLigneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ligneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Ligne.class;
	}

	@Override
	public String getModelClassName() {
		return Ligne.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ligne, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ligne, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ligne, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ligne)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ligne, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ligne, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Ligne)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ligne, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ligne, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Ligne, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ligne, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ligne, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ligne, Object>>();
		Map<String, BiConsumer<Ligne, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ligne, ?>>();

		attributeGetterFunctions.put("uuid", Ligne::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Ligne, String>)Ligne::setUuid);
		attributeGetterFunctions.put("ligneId", Ligne::getLigneId);
		attributeSetterBiConsumers.put(
			"ligneId", (BiConsumer<Ligne, Long>)Ligne::setLigneId);
		attributeGetterFunctions.put("groupId", Ligne::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Ligne, Long>)Ligne::setGroupId);
		attributeGetterFunctions.put("companyId", Ligne::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Ligne, Long>)Ligne::setCompanyId);
		attributeGetterFunctions.put("userId", Ligne::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Ligne, Long>)Ligne::setUserId);
		attributeGetterFunctions.put("userName", Ligne::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Ligne, String>)Ligne::setUserName);
		attributeGetterFunctions.put("createDate", Ligne::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Ligne, Date>)Ligne::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Ligne::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Ligne, Date>)Ligne::setModifiedDate);
		attributeGetterFunctions.put("status", Ligne::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Ligne, Integer>)Ligne::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Ligne::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Ligne, Long>)Ligne::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Ligne::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Ligne, String>)Ligne::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Ligne::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Ligne, Date>)Ligne::setStatusDate);
		attributeGetterFunctions.put("routeId", Ligne::getRouteId);
		attributeSetterBiConsumers.put(
			"routeId", (BiConsumer<Ligne, String>)Ligne::setRouteId);
		attributeGetterFunctions.put("shortName", Ligne::getShortName);
		attributeSetterBiConsumers.put(
			"shortName", (BiConsumer<Ligne, String>)Ligne::setShortName);
		attributeGetterFunctions.put("title", Ligne::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Ligne, String>)Ligne::setTitle);
		attributeGetterFunctions.put("type", Ligne::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<Ligne, Integer>)Ligne::setType);
		attributeGetterFunctions.put(
			"backgroundColor", Ligne::getBackgroundColor);
		attributeSetterBiConsumers.put(
			"backgroundColor",
			(BiConsumer<Ligne, String>)Ligne::setBackgroundColor);
		attributeGetterFunctions.put("textColor", Ligne::getTextColor);
		attributeSetterBiConsumers.put(
			"textColor", (BiConsumer<Ligne, String>)Ligne::setTextColor);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLigneId() {
		return _ligneId;
	}

	@Override
	public void setLigneId(long ligneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ligneId = ligneId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getRouteId() {
		if (_routeId == null) {
			return "";
		}
		else {
			return _routeId;
		}
	}

	@Override
	public void setRouteId(String routeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_routeId = routeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRouteId() {
		return getColumnOriginalValue("routeId");
	}

	@JSON
	@Override
	public String getShortName() {
		if (_shortName == null) {
			return "";
		}
		else {
			return _shortName;
		}
	}

	@Override
	public void setShortName(String shortName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_shortName = shortName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalShortName() {
		return getColumnOriginalValue("shortName");
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@JSON
	@Override
	public String getBackgroundColor() {
		if (_backgroundColor == null) {
			return "";
		}
		else {
			return _backgroundColor;
		}
	}

	@Override
	public void setBackgroundColor(String backgroundColor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_backgroundColor = backgroundColor;
	}

	@JSON
	@Override
	public String getTextColor() {
		if (_textColor == null) {
			return "";
		}
		else {
			return _textColor;
		}
	}

	@Override
	public void setTextColor(String textColor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_textColor = textColor;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Ligne.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Ligne.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Ligne toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ligne>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LigneImpl ligneImpl = new LigneImpl();

		ligneImpl.setUuid(getUuid());
		ligneImpl.setLigneId(getLigneId());
		ligneImpl.setGroupId(getGroupId());
		ligneImpl.setCompanyId(getCompanyId());
		ligneImpl.setUserId(getUserId());
		ligneImpl.setUserName(getUserName());
		ligneImpl.setCreateDate(getCreateDate());
		ligneImpl.setModifiedDate(getModifiedDate());
		ligneImpl.setStatus(getStatus());
		ligneImpl.setStatusByUserId(getStatusByUserId());
		ligneImpl.setStatusByUserName(getStatusByUserName());
		ligneImpl.setStatusDate(getStatusDate());
		ligneImpl.setRouteId(getRouteId());
		ligneImpl.setShortName(getShortName());
		ligneImpl.setTitle(getTitle());
		ligneImpl.setType(getType());
		ligneImpl.setBackgroundColor(getBackgroundColor());
		ligneImpl.setTextColor(getTextColor());

		ligneImpl.resetOriginalValues();

		return ligneImpl;
	}

	@Override
	public Ligne cloneWithOriginalValues() {
		LigneImpl ligneImpl = new LigneImpl();

		ligneImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		ligneImpl.setLigneId(this.<Long>getColumnOriginalValue("ligneId"));
		ligneImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		ligneImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		ligneImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		ligneImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		ligneImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		ligneImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		ligneImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		ligneImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		ligneImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		ligneImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		ligneImpl.setRouteId(this.<String>getColumnOriginalValue("routeId"));
		ligneImpl.setShortName(
			this.<String>getColumnOriginalValue("shortName"));
		ligneImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		ligneImpl.setType(this.<Integer>getColumnOriginalValue("type_"));
		ligneImpl.setBackgroundColor(
			this.<String>getColumnOriginalValue("backgroundColor"));
		ligneImpl.setTextColor(
			this.<String>getColumnOriginalValue("textColor"));

		return ligneImpl;
	}

	@Override
	public int compareTo(Ligne ligne) {
		int value = 0;

		if (getLigneId() < ligne.getLigneId()) {
			value = -1;
		}
		else if (getLigneId() > ligne.getLigneId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Ligne)) {
			return false;
		}

		Ligne ligne = (Ligne)object;

		long primaryKey = ligne.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Ligne> toCacheModel() {
		LigneCacheModel ligneCacheModel = new LigneCacheModel();

		ligneCacheModel.uuid = getUuid();

		String uuid = ligneCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ligneCacheModel.uuid = null;
		}

		ligneCacheModel.ligneId = getLigneId();

		ligneCacheModel.groupId = getGroupId();

		ligneCacheModel.companyId = getCompanyId();

		ligneCacheModel.userId = getUserId();

		ligneCacheModel.userName = getUserName();

		String userName = ligneCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ligneCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ligneCacheModel.createDate = createDate.getTime();
		}
		else {
			ligneCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ligneCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ligneCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ligneCacheModel.status = getStatus();

		ligneCacheModel.statusByUserId = getStatusByUserId();

		ligneCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = ligneCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			ligneCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			ligneCacheModel.statusDate = statusDate.getTime();
		}
		else {
			ligneCacheModel.statusDate = Long.MIN_VALUE;
		}

		ligneCacheModel.routeId = getRouteId();

		String routeId = ligneCacheModel.routeId;

		if ((routeId != null) && (routeId.length() == 0)) {
			ligneCacheModel.routeId = null;
		}

		ligneCacheModel.shortName = getShortName();

		String shortName = ligneCacheModel.shortName;

		if ((shortName != null) && (shortName.length() == 0)) {
			ligneCacheModel.shortName = null;
		}

		ligneCacheModel.title = getTitle();

		String title = ligneCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			ligneCacheModel.title = null;
		}

		ligneCacheModel.type = getType();

		ligneCacheModel.backgroundColor = getBackgroundColor();

		String backgroundColor = ligneCacheModel.backgroundColor;

		if ((backgroundColor != null) && (backgroundColor.length() == 0)) {
			ligneCacheModel.backgroundColor = null;
		}

		ligneCacheModel.textColor = getTextColor();

		String textColor = ligneCacheModel.textColor;

		if ((textColor != null) && (textColor.length() == 0)) {
			ligneCacheModel.textColor = null;
		}

		return ligneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ligne, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ligne, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ligne, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Ligne)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ligne>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Ligne.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ligneId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _routeId;
	private String _shortName;
	private String _title;
	private int _type;
	private String _backgroundColor;
	private String _textColor;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Ligne, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Ligne)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ligneId", _ligneId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("routeId", _routeId);
		_columnOriginalValues.put("shortName", _shortName);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("backgroundColor", _backgroundColor);
		_columnOriginalValues.put("textColor", _textColor);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ligneId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("status", 256L);

		columnBitmasks.put("statusByUserId", 512L);

		columnBitmasks.put("statusByUserName", 1024L);

		columnBitmasks.put("statusDate", 2048L);

		columnBitmasks.put("routeId", 4096L);

		columnBitmasks.put("shortName", 8192L);

		columnBitmasks.put("title", 16384L);

		columnBitmasks.put("type_", 32768L);

		columnBitmasks.put("backgroundColor", 65536L);

		columnBitmasks.put("textColor", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Ligne _escapedModel;

}