/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.activity.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.activity.model.Association;
import eu.strasbourg.service.activity.model.AssociationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Association service. Represents a row in the &quot;activity_Association&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssociationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssociationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssociationImpl
 * @generated
 */
@JSON(strict = true)
public class AssociationModelImpl
	extends BaseModelImpl<Association> implements AssociationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a association model instance should use the <code>Association</code> interface instead.
	 */
	public static final String TABLE_NAME = "activity_Association";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"associationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"presentation", Types.CLOB},
		{"phone", Types.VARCHAR}, {"siteURL", Types.VARCHAR},
		{"mail", Types.VARCHAR}, {"facebookURL", Types.VARCHAR},
		{"othersInformations", Types.CLOB}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("associationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("presentation", Types.CLOB);
		TABLE_COLUMNS_MAP.put("phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("siteURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facebookURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("othersInformations", Types.CLOB);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table activity_Association (uuid_ VARCHAR(75) null,associationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name STRING null,presentation TEXT null,phone VARCHAR(75) null,siteURL STRING null,mail VARCHAR(75) null,facebookURL STRING null,othersInformations TEXT null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table activity_Association";

	public static final String ORDER_BY_JPQL =
		" ORDER BY association.associationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY activity_Association.associationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSOCIATIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.activity.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.activity.model.Association"));

	public AssociationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _associationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssociationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _associationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Association.class;
	}

	@Override
	public String getModelClassName() {
		return Association.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Association, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Association, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Association, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Association)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Association, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Association, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Association)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Association, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Association, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Association, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Association, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Association, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Association, Object>>();
		Map<String, BiConsumer<Association, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Association, ?>>();

		attributeGetterFunctions.put("uuid", Association::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Association, String>)Association::setUuid);
		attributeGetterFunctions.put(
			"associationId", Association::getAssociationId);
		attributeSetterBiConsumers.put(
			"associationId",
			(BiConsumer<Association, Long>)Association::setAssociationId);
		attributeGetterFunctions.put("groupId", Association::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Association, Long>)Association::setGroupId);
		attributeGetterFunctions.put("companyId", Association::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Association, Long>)Association::setCompanyId);
		attributeGetterFunctions.put("userId", Association::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Association, Long>)Association::setUserId);
		attributeGetterFunctions.put("userName", Association::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Association, String>)Association::setUserName);
		attributeGetterFunctions.put("createDate", Association::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Association, Date>)Association::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Association::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Association, Date>)Association::setModifiedDate);
		attributeGetterFunctions.put("name", Association::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Association, String>)Association::setName);
		attributeGetterFunctions.put(
			"presentation", Association::getPresentation);
		attributeSetterBiConsumers.put(
			"presentation",
			(BiConsumer<Association, String>)Association::setPresentation);
		attributeGetterFunctions.put("phone", Association::getPhone);
		attributeSetterBiConsumers.put(
			"phone", (BiConsumer<Association, String>)Association::setPhone);
		attributeGetterFunctions.put("siteURL", Association::getSiteURL);
		attributeSetterBiConsumers.put(
			"siteURL",
			(BiConsumer<Association, String>)Association::setSiteURL);
		attributeGetterFunctions.put("mail", Association::getMail);
		attributeSetterBiConsumers.put(
			"mail", (BiConsumer<Association, String>)Association::setMail);
		attributeGetterFunctions.put(
			"facebookURL", Association::getFacebookURL);
		attributeSetterBiConsumers.put(
			"facebookURL",
			(BiConsumer<Association, String>)Association::setFacebookURL);
		attributeGetterFunctions.put(
			"othersInformations", Association::getOthersInformations);
		attributeSetterBiConsumers.put(
			"othersInformations",
			(BiConsumer<Association, String>)
				Association::setOthersInformations);
		attributeGetterFunctions.put("status", Association::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Association, Integer>)Association::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Association::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Association, Long>)Association::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Association::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Association, String>)Association::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Association::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<Association, Date>)Association::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAssociationId() {
		return _associationId;
	}

	@Override
	public void setAssociationId(long associationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_associationId = associationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getPresentation() {
		if (_presentation == null) {
			return "";
		}
		else {
			return _presentation;
		}
	}

	@Override
	public String getPresentation(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPresentation(languageId);
	}

	@Override
	public String getPresentation(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPresentation(languageId, useDefault);
	}

	@Override
	public String getPresentation(String languageId) {
		return LocalizationUtil.getLocalization(getPresentation(), languageId);
	}

	@Override
	public String getPresentation(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getPresentation(), languageId, useDefault);
	}

	@Override
	public String getPresentationCurrentLanguageId() {
		return _presentationCurrentLanguageId;
	}

	@JSON
	@Override
	public String getPresentationCurrentValue() {
		Locale locale = getLocale(_presentationCurrentLanguageId);

		return getPresentation(locale);
	}

	@Override
	public Map<Locale, String> getPresentationMap() {
		return LocalizationUtil.getLocalizationMap(getPresentation());
	}

	@Override
	public void setPresentation(String presentation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_presentation = presentation;
	}

	@Override
	public void setPresentation(String presentation, Locale locale) {
		setPresentation(presentation, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPresentation(
		String presentation, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(presentation)) {
			setPresentation(
				LocalizationUtil.updateLocalization(
					getPresentation(), "Presentation", presentation, languageId,
					defaultLanguageId));
		}
		else {
			setPresentation(
				LocalizationUtil.removeLocalization(
					getPresentation(), "Presentation", languageId));
		}
	}

	@Override
	public void setPresentationCurrentLanguageId(String languageId) {
		_presentationCurrentLanguageId = languageId;
	}

	@Override
	public void setPresentationMap(Map<Locale, String> presentationMap) {
		setPresentationMap(presentationMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPresentationMap(
		Map<Locale, String> presentationMap, Locale defaultLocale) {

		if (presentationMap == null) {
			return;
		}

		setPresentation(
			LocalizationUtil.updateLocalization(
				presentationMap, getPresentation(), "Presentation",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getPhone() {
		if (_phone == null) {
			return "";
		}
		else {
			return _phone;
		}
	}

	@Override
	public void setPhone(String phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phone = phone;
	}

	@JSON
	@Override
	public String getSiteURL() {
		if (_siteURL == null) {
			return "";
		}
		else {
			return _siteURL;
		}
	}

	@Override
	public String getSiteURL(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSiteURL(languageId);
	}

	@Override
	public String getSiteURL(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSiteURL(languageId, useDefault);
	}

	@Override
	public String getSiteURL(String languageId) {
		return LocalizationUtil.getLocalization(getSiteURL(), languageId);
	}

	@Override
	public String getSiteURL(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getSiteURL(), languageId, useDefault);
	}

	@Override
	public String getSiteURLCurrentLanguageId() {
		return _siteURLCurrentLanguageId;
	}

	@JSON
	@Override
	public String getSiteURLCurrentValue() {
		Locale locale = getLocale(_siteURLCurrentLanguageId);

		return getSiteURL(locale);
	}

	@Override
	public Map<Locale, String> getSiteURLMap() {
		return LocalizationUtil.getLocalizationMap(getSiteURL());
	}

	@Override
	public void setSiteURL(String siteURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_siteURL = siteURL;
	}

	@Override
	public void setSiteURL(String siteURL, Locale locale) {
		setSiteURL(siteURL, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSiteURL(
		String siteURL, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(siteURL)) {
			setSiteURL(
				LocalizationUtil.updateLocalization(
					getSiteURL(), "SiteURL", siteURL, languageId,
					defaultLanguageId));
		}
		else {
			setSiteURL(
				LocalizationUtil.removeLocalization(
					getSiteURL(), "SiteURL", languageId));
		}
	}

	@Override
	public void setSiteURLCurrentLanguageId(String languageId) {
		_siteURLCurrentLanguageId = languageId;
	}

	@Override
	public void setSiteURLMap(Map<Locale, String> siteURLMap) {
		setSiteURLMap(siteURLMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSiteURLMap(
		Map<Locale, String> siteURLMap, Locale defaultLocale) {

		if (siteURLMap == null) {
			return;
		}

		setSiteURL(
			LocalizationUtil.updateLocalization(
				siteURLMap, getSiteURL(), "SiteURL",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getMail() {
		if (_mail == null) {
			return "";
		}
		else {
			return _mail;
		}
	}

	@Override
	public void setMail(String mail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mail = mail;
	}

	@JSON
	@Override
	public String getFacebookURL() {
		if (_facebookURL == null) {
			return "";
		}
		else {
			return _facebookURL;
		}
	}

	@Override
	public String getFacebookURL(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFacebookURL(languageId);
	}

	@Override
	public String getFacebookURL(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFacebookURL(languageId, useDefault);
	}

	@Override
	public String getFacebookURL(String languageId) {
		return LocalizationUtil.getLocalization(getFacebookURL(), languageId);
	}

	@Override
	public String getFacebookURL(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getFacebookURL(), languageId, useDefault);
	}

	@Override
	public String getFacebookURLCurrentLanguageId() {
		return _facebookURLCurrentLanguageId;
	}

	@JSON
	@Override
	public String getFacebookURLCurrentValue() {
		Locale locale = getLocale(_facebookURLCurrentLanguageId);

		return getFacebookURL(locale);
	}

	@Override
	public Map<Locale, String> getFacebookURLMap() {
		return LocalizationUtil.getLocalizationMap(getFacebookURL());
	}

	@Override
	public void setFacebookURL(String facebookURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facebookURL = facebookURL;
	}

	@Override
	public void setFacebookURL(String facebookURL, Locale locale) {
		setFacebookURL(facebookURL, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setFacebookURL(
		String facebookURL, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(facebookURL)) {
			setFacebookURL(
				LocalizationUtil.updateLocalization(
					getFacebookURL(), "FacebookURL", facebookURL, languageId,
					defaultLanguageId));
		}
		else {
			setFacebookURL(
				LocalizationUtil.removeLocalization(
					getFacebookURL(), "FacebookURL", languageId));
		}
	}

	@Override
	public void setFacebookURLCurrentLanguageId(String languageId) {
		_facebookURLCurrentLanguageId = languageId;
	}

	@Override
	public void setFacebookURLMap(Map<Locale, String> facebookURLMap) {
		setFacebookURLMap(facebookURLMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setFacebookURLMap(
		Map<Locale, String> facebookURLMap, Locale defaultLocale) {

		if (facebookURLMap == null) {
			return;
		}

		setFacebookURL(
			LocalizationUtil.updateLocalization(
				facebookURLMap, getFacebookURL(), "FacebookURL",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getOthersInformations() {
		if (_othersInformations == null) {
			return "";
		}
		else {
			return _othersInformations;
		}
	}

	@Override
	public String getOthersInformations(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOthersInformations(languageId);
	}

	@Override
	public String getOthersInformations(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOthersInformations(languageId, useDefault);
	}

	@Override
	public String getOthersInformations(String languageId) {
		return LocalizationUtil.getLocalization(
			getOthersInformations(), languageId);
	}

	@Override
	public String getOthersInformations(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getOthersInformations(), languageId, useDefault);
	}

	@Override
	public String getOthersInformationsCurrentLanguageId() {
		return _othersInformationsCurrentLanguageId;
	}

	@JSON
	@Override
	public String getOthersInformationsCurrentValue() {
		Locale locale = getLocale(_othersInformationsCurrentLanguageId);

		return getOthersInformations(locale);
	}

	@Override
	public Map<Locale, String> getOthersInformationsMap() {
		return LocalizationUtil.getLocalizationMap(getOthersInformations());
	}

	@Override
	public void setOthersInformations(String othersInformations) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_othersInformations = othersInformations;
	}

	@Override
	public void setOthersInformations(
		String othersInformations, Locale locale) {

		setOthersInformations(
			othersInformations, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOthersInformations(
		String othersInformations, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(othersInformations)) {
			setOthersInformations(
				LocalizationUtil.updateLocalization(
					getOthersInformations(), "OthersInformations",
					othersInformations, languageId, defaultLanguageId));
		}
		else {
			setOthersInformations(
				LocalizationUtil.removeLocalization(
					getOthersInformations(), "OthersInformations", languageId));
		}
	}

	@Override
	public void setOthersInformationsCurrentLanguageId(String languageId) {
		_othersInformationsCurrentLanguageId = languageId;
	}

	@Override
	public void setOthersInformationsMap(
		Map<Locale, String> othersInformationsMap) {

		setOthersInformationsMap(
			othersInformationsMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOthersInformationsMap(
		Map<Locale, String> othersInformationsMap, Locale defaultLocale) {

		if (othersInformationsMap == null) {
			return;
		}

		setOthersInformations(
			LocalizationUtil.updateLocalization(
				othersInformationsMap, getOthersInformations(),
				"OthersInformations", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Association.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Association.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> presentationMap = getPresentationMap();

		for (Map.Entry<Locale, String> entry : presentationMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> siteURLMap = getSiteURLMap();

		for (Map.Entry<Locale, String> entry : siteURLMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> facebookURLMap = getFacebookURLMap();

		for (Map.Entry<Locale, String> entry : facebookURLMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> othersInformationsMap = getOthersInformationsMap();

		for (Map.Entry<Locale, String> entry :
				othersInformationsMap.entrySet()) {

			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Association.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String presentation = getPresentation(defaultLocale);

		if (Validator.isNull(presentation)) {
			setPresentation(
				getPresentation(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setPresentation(
				getPresentation(defaultLocale), defaultLocale, defaultLocale);
		}

		String siteURL = getSiteURL(defaultLocale);

		if (Validator.isNull(siteURL)) {
			setSiteURL(getSiteURL(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setSiteURL(getSiteURL(defaultLocale), defaultLocale, defaultLocale);
		}

		String facebookURL = getFacebookURL(defaultLocale);

		if (Validator.isNull(facebookURL)) {
			setFacebookURL(
				getFacebookURL(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setFacebookURL(
				getFacebookURL(defaultLocale), defaultLocale, defaultLocale);
		}

		String othersInformations = getOthersInformations(defaultLocale);

		if (Validator.isNull(othersInformations)) {
			setOthersInformations(
				getOthersInformations(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setOthersInformations(
				getOthersInformations(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public Association toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Association>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssociationImpl associationImpl = new AssociationImpl();

		associationImpl.setUuid(getUuid());
		associationImpl.setAssociationId(getAssociationId());
		associationImpl.setGroupId(getGroupId());
		associationImpl.setCompanyId(getCompanyId());
		associationImpl.setUserId(getUserId());
		associationImpl.setUserName(getUserName());
		associationImpl.setCreateDate(getCreateDate());
		associationImpl.setModifiedDate(getModifiedDate());
		associationImpl.setName(getName());
		associationImpl.setPresentation(getPresentation());
		associationImpl.setPhone(getPhone());
		associationImpl.setSiteURL(getSiteURL());
		associationImpl.setMail(getMail());
		associationImpl.setFacebookURL(getFacebookURL());
		associationImpl.setOthersInformations(getOthersInformations());
		associationImpl.setStatus(getStatus());
		associationImpl.setStatusByUserId(getStatusByUserId());
		associationImpl.setStatusByUserName(getStatusByUserName());
		associationImpl.setStatusDate(getStatusDate());

		associationImpl.resetOriginalValues();

		return associationImpl;
	}

	@Override
	public Association cloneWithOriginalValues() {
		AssociationImpl associationImpl = new AssociationImpl();

		associationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		associationImpl.setAssociationId(
			this.<Long>getColumnOriginalValue("associationId"));
		associationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		associationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		associationImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		associationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		associationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		associationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		associationImpl.setName(this.<String>getColumnOriginalValue("name"));
		associationImpl.setPresentation(
			this.<String>getColumnOriginalValue("presentation"));
		associationImpl.setPhone(this.<String>getColumnOriginalValue("phone"));
		associationImpl.setSiteURL(
			this.<String>getColumnOriginalValue("siteURL"));
		associationImpl.setMail(this.<String>getColumnOriginalValue("mail"));
		associationImpl.setFacebookURL(
			this.<String>getColumnOriginalValue("facebookURL"));
		associationImpl.setOthersInformations(
			this.<String>getColumnOriginalValue("othersInformations"));
		associationImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		associationImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		associationImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		associationImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return associationImpl;
	}

	@Override
	public int compareTo(Association association) {
		long primaryKey = association.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Association)) {
			return false;
		}

		Association association = (Association)object;

		long primaryKey = association.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Association> toCacheModel() {
		AssociationCacheModel associationCacheModel =
			new AssociationCacheModel();

		associationCacheModel.uuid = getUuid();

		String uuid = associationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			associationCacheModel.uuid = null;
		}

		associationCacheModel.associationId = getAssociationId();

		associationCacheModel.groupId = getGroupId();

		associationCacheModel.companyId = getCompanyId();

		associationCacheModel.userId = getUserId();

		associationCacheModel.userName = getUserName();

		String userName = associationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			associationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			associationCacheModel.createDate = createDate.getTime();
		}
		else {
			associationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			associationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			associationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		associationCacheModel.name = getName();

		String name = associationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			associationCacheModel.name = null;
		}

		associationCacheModel.presentation = getPresentation();

		String presentation = associationCacheModel.presentation;

		if ((presentation != null) && (presentation.length() == 0)) {
			associationCacheModel.presentation = null;
		}

		associationCacheModel.phone = getPhone();

		String phone = associationCacheModel.phone;

		if ((phone != null) && (phone.length() == 0)) {
			associationCacheModel.phone = null;
		}

		associationCacheModel.siteURL = getSiteURL();

		String siteURL = associationCacheModel.siteURL;

		if ((siteURL != null) && (siteURL.length() == 0)) {
			associationCacheModel.siteURL = null;
		}

		associationCacheModel.mail = getMail();

		String mail = associationCacheModel.mail;

		if ((mail != null) && (mail.length() == 0)) {
			associationCacheModel.mail = null;
		}

		associationCacheModel.facebookURL = getFacebookURL();

		String facebookURL = associationCacheModel.facebookURL;

		if ((facebookURL != null) && (facebookURL.length() == 0)) {
			associationCacheModel.facebookURL = null;
		}

		associationCacheModel.othersInformations = getOthersInformations();

		String othersInformations = associationCacheModel.othersInformations;

		if ((othersInformations != null) &&
			(othersInformations.length() == 0)) {

			associationCacheModel.othersInformations = null;
		}

		associationCacheModel.status = getStatus();

		associationCacheModel.statusByUserId = getStatusByUserId();

		associationCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = associationCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			associationCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			associationCacheModel.statusDate = statusDate.getTime();
		}
		else {
			associationCacheModel.statusDate = Long.MIN_VALUE;
		}

		return associationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Association, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Association, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Association, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Association)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Association>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Association.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _associationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _presentation;
	private String _presentationCurrentLanguageId;
	private String _phone;
	private String _siteURL;
	private String _siteURLCurrentLanguageId;
	private String _mail;
	private String _facebookURL;
	private String _facebookURLCurrentLanguageId;
	private String _othersInformations;
	private String _othersInformationsCurrentLanguageId;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Association, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Association)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("associationId", _associationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("presentation", _presentation);
		_columnOriginalValues.put("phone", _phone);
		_columnOriginalValues.put("siteURL", _siteURL);
		_columnOriginalValues.put("mail", _mail);
		_columnOriginalValues.put("facebookURL", _facebookURL);
		_columnOriginalValues.put("othersInformations", _othersInformations);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("associationId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("presentation", 512L);

		columnBitmasks.put("phone", 1024L);

		columnBitmasks.put("siteURL", 2048L);

		columnBitmasks.put("mail", 4096L);

		columnBitmasks.put("facebookURL", 8192L);

		columnBitmasks.put("othersInformations", 16384L);

		columnBitmasks.put("status", 32768L);

		columnBitmasks.put("statusByUserId", 65536L);

		columnBitmasks.put("statusByUserName", 131072L);

		columnBitmasks.put("statusDate", 262144L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Association _escapedModel;

}