/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.agenda.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import eu.strasbourg.service.agenda.model.AgendaExportPeriod;
import eu.strasbourg.service.agenda.model.AgendaExportPeriodModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AgendaExportPeriod service. Represents a row in the &quot;agenda_AgendaExportPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AgendaExportPeriodModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgendaExportPeriodImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see AgendaExportPeriodImpl
 * @generated
 */
@JSON(strict = true)
public class AgendaExportPeriodModelImpl
	extends BaseModelImpl<AgendaExportPeriod>
	implements AgendaExportPeriodModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agenda export period model instance should use the <code>AgendaExportPeriod</code> interface instead.
	 */
	public static final String TABLE_NAME = "agenda_AgendaExportPeriod";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"agendaExportPeriodId", Types.BIGINT},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"agendaExportId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agendaExportPeriodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("agendaExportId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agenda_AgendaExportPeriod (uuid_ VARCHAR(75) null,agendaExportPeriodId LONG not null primary key,startDate DATE null,endDate DATE null,agendaExportId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table agenda_AgendaExportPeriod";

	public static final String ORDER_BY_JPQL =
		" ORDER BY agendaExportPeriod.agendaExportPeriodId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agenda_AgendaExportPeriod.agendaExportPeriodId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGENDAEXPORTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGENDAEXPORTPERIODID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.agenda.model.AgendaExportPeriod"));

	public AgendaExportPeriodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _agendaExportPeriodId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAgendaExportPeriodId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _agendaExportPeriodId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AgendaExportPeriod.class;
	}

	@Override
	public String getModelClassName() {
		return AgendaExportPeriod.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AgendaExportPeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AgendaExportPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AgendaExportPeriod, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AgendaExportPeriod)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AgendaExportPeriod, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AgendaExportPeriod, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AgendaExportPeriod)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AgendaExportPeriod, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AgendaExportPeriod, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AgendaExportPeriod, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AgendaExportPeriod, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AgendaExportPeriod, Object>>();

			attributeGetterFunctions.put("uuid", AgendaExportPeriod::getUuid);
			attributeGetterFunctions.put(
				"agendaExportPeriodId",
				AgendaExportPeriod::getAgendaExportPeriodId);
			attributeGetterFunctions.put(
				"startDate", AgendaExportPeriod::getStartDate);
			attributeGetterFunctions.put(
				"endDate", AgendaExportPeriod::getEndDate);
			attributeGetterFunctions.put(
				"agendaExportId", AgendaExportPeriod::getAgendaExportId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AgendaExportPeriod, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AgendaExportPeriod, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AgendaExportPeriod, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AgendaExportPeriod, String>)
					AgendaExportPeriod::setUuid);
			attributeSetterBiConsumers.put(
				"agendaExportPeriodId",
				(BiConsumer<AgendaExportPeriod, Long>)
					AgendaExportPeriod::setAgendaExportPeriodId);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<AgendaExportPeriod, Date>)
					AgendaExportPeriod::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<AgendaExportPeriod, Date>)
					AgendaExportPeriod::setEndDate);
			attributeSetterBiConsumers.put(
				"agendaExportId",
				(BiConsumer<AgendaExportPeriod, Long>)
					AgendaExportPeriod::setAgendaExportId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAgendaExportPeriodId() {
		return _agendaExportPeriodId;
	}

	@Override
	public void setAgendaExportPeriodId(long agendaExportPeriodId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agendaExportPeriodId = agendaExportPeriodId;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public long getAgendaExportId() {
		return _agendaExportId;
	}

	@Override
	public void setAgendaExportId(long agendaExportId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agendaExportId = agendaExportId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAgendaExportId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("agendaExportId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AgendaExportPeriod.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AgendaExportPeriod toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AgendaExportPeriod>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AgendaExportPeriodImpl agendaExportPeriodImpl =
			new AgendaExportPeriodImpl();

		agendaExportPeriodImpl.setUuid(getUuid());
		agendaExportPeriodImpl.setAgendaExportPeriodId(
			getAgendaExportPeriodId());
		agendaExportPeriodImpl.setStartDate(getStartDate());
		agendaExportPeriodImpl.setEndDate(getEndDate());
		agendaExportPeriodImpl.setAgendaExportId(getAgendaExportId());

		agendaExportPeriodImpl.resetOriginalValues();

		return agendaExportPeriodImpl;
	}

	@Override
	public AgendaExportPeriod cloneWithOriginalValues() {
		AgendaExportPeriodImpl agendaExportPeriodImpl =
			new AgendaExportPeriodImpl();

		agendaExportPeriodImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		agendaExportPeriodImpl.setAgendaExportPeriodId(
			this.<Long>getColumnOriginalValue("agendaExportPeriodId"));
		agendaExportPeriodImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		agendaExportPeriodImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		agendaExportPeriodImpl.setAgendaExportId(
			this.<Long>getColumnOriginalValue("agendaExportId"));

		return agendaExportPeriodImpl;
	}

	@Override
	public int compareTo(AgendaExportPeriod agendaExportPeriod) {
		long primaryKey = agendaExportPeriod.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AgendaExportPeriod)) {
			return false;
		}

		AgendaExportPeriod agendaExportPeriod = (AgendaExportPeriod)object;

		long primaryKey = agendaExportPeriod.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AgendaExportPeriod> toCacheModel() {
		AgendaExportPeriodCacheModel agendaExportPeriodCacheModel =
			new AgendaExportPeriodCacheModel();

		agendaExportPeriodCacheModel.uuid = getUuid();

		String uuid = agendaExportPeriodCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			agendaExportPeriodCacheModel.uuid = null;
		}

		agendaExportPeriodCacheModel.agendaExportPeriodId =
			getAgendaExportPeriodId();

		Date startDate = getStartDate();

		if (startDate != null) {
			agendaExportPeriodCacheModel.startDate = startDate.getTime();
		}
		else {
			agendaExportPeriodCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			agendaExportPeriodCacheModel.endDate = endDate.getTime();
		}
		else {
			agendaExportPeriodCacheModel.endDate = Long.MIN_VALUE;
		}

		agendaExportPeriodCacheModel.agendaExportId = getAgendaExportId();

		return agendaExportPeriodCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AgendaExportPeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AgendaExportPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AgendaExportPeriod, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AgendaExportPeriod)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AgendaExportPeriod>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AgendaExportPeriod.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _agendaExportPeriodId;
	private Date _startDate;
	private Date _endDate;
	private long _agendaExportId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AgendaExportPeriod, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AgendaExportPeriod)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"agendaExportPeriodId", _agendaExportPeriodId);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("agendaExportId", _agendaExportId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("agendaExportPeriodId", 2L);

		columnBitmasks.put("startDate", 4L);

		columnBitmasks.put("endDate", 8L);

		columnBitmasks.put("agendaExportId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AgendaExportPeriod _escapedModel;

}