/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.agenda.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import eu.strasbourg.service.agenda.model.CampaignEvent;
import eu.strasbourg.service.agenda.model.CampaignEventModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CampaignEvent service. Represents a row in the &quot;agenda_CampaignEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CampaignEventModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CampaignEventImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see CampaignEventImpl
 * @generated
 */
public class CampaignEventModelImpl
	extends BaseModelImpl<CampaignEvent> implements CampaignEventModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a campaign event model instance should use the <code>CampaignEvent</code> interface instead.
	 */
	public static final String TABLE_NAME = "agenda_CampaignEvent";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"campaignEventId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"phone", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"serviceId", Types.BIGINT}, {"service", Types.VARCHAR},
		{"onSiteFirstName", Types.VARCHAR}, {"onSiteLastName", Types.VARCHAR},
		{"onSitePhone", Types.VARCHAR}, {"title", Types.VARCHAR},
		{"subtitle", Types.VARCHAR}, {"description", Types.CLOB},
		{"imageId", Types.BIGINT}, {"webImageId", Types.BIGINT},
		{"imageOwner", Types.VARCHAR}, {"manifestationsIds", Types.VARCHAR},
		{"placeSIGId", Types.VARCHAR}, {"placeName", Types.VARCHAR},
		{"placeStreetNumber", Types.VARCHAR},
		{"placeStreetName", Types.VARCHAR}, {"placeZipCode", Types.VARCHAR},
		{"placeCityId", Types.BIGINT}, {"placeCountry", Types.VARCHAR},
		{"promoter", Types.VARCHAR}, {"publicPhone", Types.VARCHAR},
		{"publicEmail", Types.VARCHAR}, {"websiteURL", Types.VARCHAR},
		{"websiteName", Types.VARCHAR}, {"free", Types.INTEGER},
		{"price", Types.CLOB}, {"campaignId", Types.BIGINT},
		{"themesIds", Types.VARCHAR}, {"typesIds", Types.VARCHAR},
		{"publicsIds", Types.VARCHAR}, {"tagsNames", Types.VARCHAR},
		{"bookingDescription", Types.CLOB}, {"bookingURL", Types.VARCHAR},
		{"registration", Types.BOOLEAN},
		{"registrationStartDate", Types.TIMESTAMP},
		{"registrationEndDate", Types.TIMESTAMP}, {"maxGauge", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("campaignEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serviceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("service", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("onSiteFirstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("onSiteLastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("onSitePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subtitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("webImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imageOwner", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manifestationsIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeSIGId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeStreetNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeStreetName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeZipCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("placeCityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("placeCountry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoter", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("websiteURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("websiteName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("free", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("price", Types.CLOB);
		TABLE_COLUMNS_MAP.put("campaignId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("themesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicsIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tagsNames", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bookingDescription", Types.CLOB);
		TABLE_COLUMNS_MAP.put("bookingURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("registration", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("registrationStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("registrationEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("maxGauge", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agenda_CampaignEvent (uuid_ VARCHAR(75) null,campaignEventId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,firstName VARCHAR(75) null,lastName VARCHAR(75) null,phone VARCHAR(75) null,email VARCHAR(75) null,serviceId LONG,service VARCHAR(75) null,onSiteFirstName VARCHAR(75) null,onSiteLastName VARCHAR(75) null,onSitePhone VARCHAR(75) null,title STRING null,subtitle STRING null,description TEXT null,imageId LONG,webImageId LONG,imageOwner VARCHAR(75) null,manifestationsIds VARCHAR(75) null,placeSIGId VARCHAR(75) null,placeName STRING null,placeStreetNumber VARCHAR(75) null,placeStreetName VARCHAR(75) null,placeZipCode VARCHAR(75) null,placeCityId LONG,placeCountry VARCHAR(75) null,promoter VARCHAR(75) null,publicPhone VARCHAR(75) null,publicEmail VARCHAR(75) null,websiteURL STRING null,websiteName STRING null,free INTEGER,price TEXT null,campaignId LONG,themesIds VARCHAR(75) null,typesIds VARCHAR(75) null,publicsIds VARCHAR(75) null,tagsNames VARCHAR(75) null,bookingDescription TEXT null,bookingURL VARCHAR(400) null,registration BOOLEAN,registrationStartDate DATE null,registrationEndDate DATE null,maxGauge LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table agenda_CampaignEvent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY campaignEvent.campaignEventId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agenda_CampaignEvent.campaignEventId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CAMPAIGNID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CAMPAIGNEVENTID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.agenda.model.CampaignEvent"));

	public CampaignEventModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _campaignEventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCampaignEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _campaignEventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CampaignEvent.class;
	}

	@Override
	public String getModelClassName() {
		return CampaignEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CampaignEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CampaignEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CampaignEvent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CampaignEvent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CampaignEvent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CampaignEvent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CampaignEvent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CampaignEvent, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CampaignEvent, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CampaignEvent, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CampaignEvent, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CampaignEvent, Object>>();

			attributeGetterFunctions.put("uuid", CampaignEvent::getUuid);
			attributeGetterFunctions.put(
				"campaignEventId", CampaignEvent::getCampaignEventId);
			attributeGetterFunctions.put("groupId", CampaignEvent::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CampaignEvent::getCompanyId);
			attributeGetterFunctions.put("userId", CampaignEvent::getUserId);
			attributeGetterFunctions.put(
				"userName", CampaignEvent::getUserName);
			attributeGetterFunctions.put(
				"createDate", CampaignEvent::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CampaignEvent::getModifiedDate);
			attributeGetterFunctions.put(
				"lastPublishDate", CampaignEvent::getLastPublishDate);
			attributeGetterFunctions.put("status", CampaignEvent::getStatus);
			attributeGetterFunctions.put(
				"firstName", CampaignEvent::getFirstName);
			attributeGetterFunctions.put(
				"lastName", CampaignEvent::getLastName);
			attributeGetterFunctions.put("phone", CampaignEvent::getPhone);
			attributeGetterFunctions.put("email", CampaignEvent::getEmail);
			attributeGetterFunctions.put(
				"serviceId", CampaignEvent::getServiceId);
			attributeGetterFunctions.put("service", CampaignEvent::getService);
			attributeGetterFunctions.put(
				"onSiteFirstName", CampaignEvent::getOnSiteFirstName);
			attributeGetterFunctions.put(
				"onSiteLastName", CampaignEvent::getOnSiteLastName);
			attributeGetterFunctions.put(
				"onSitePhone", CampaignEvent::getOnSitePhone);
			attributeGetterFunctions.put("title", CampaignEvent::getTitle);
			attributeGetterFunctions.put(
				"subtitle", CampaignEvent::getSubtitle);
			attributeGetterFunctions.put(
				"description", CampaignEvent::getDescription);
			attributeGetterFunctions.put("imageId", CampaignEvent::getImageId);
			attributeGetterFunctions.put(
				"webImageId", CampaignEvent::getWebImageId);
			attributeGetterFunctions.put(
				"imageOwner", CampaignEvent::getImageOwner);
			attributeGetterFunctions.put(
				"manifestationsIds", CampaignEvent::getManifestationsIds);
			attributeGetterFunctions.put(
				"placeSIGId", CampaignEvent::getPlaceSIGId);
			attributeGetterFunctions.put(
				"placeName", CampaignEvent::getPlaceName);
			attributeGetterFunctions.put(
				"placeStreetNumber", CampaignEvent::getPlaceStreetNumber);
			attributeGetterFunctions.put(
				"placeStreetName", CampaignEvent::getPlaceStreetName);
			attributeGetterFunctions.put(
				"placeZipCode", CampaignEvent::getPlaceZipCode);
			attributeGetterFunctions.put(
				"placeCityId", CampaignEvent::getPlaceCityId);
			attributeGetterFunctions.put(
				"placeCountry", CampaignEvent::getPlaceCountry);
			attributeGetterFunctions.put(
				"promoter", CampaignEvent::getPromoter);
			attributeGetterFunctions.put(
				"publicPhone", CampaignEvent::getPublicPhone);
			attributeGetterFunctions.put(
				"publicEmail", CampaignEvent::getPublicEmail);
			attributeGetterFunctions.put(
				"websiteURL", CampaignEvent::getWebsiteURL);
			attributeGetterFunctions.put(
				"websiteName", CampaignEvent::getWebsiteName);
			attributeGetterFunctions.put("free", CampaignEvent::getFree);
			attributeGetterFunctions.put("price", CampaignEvent::getPrice);
			attributeGetterFunctions.put(
				"campaignId", CampaignEvent::getCampaignId);
			attributeGetterFunctions.put(
				"themesIds", CampaignEvent::getThemesIds);
			attributeGetterFunctions.put(
				"typesIds", CampaignEvent::getTypesIds);
			attributeGetterFunctions.put(
				"publicsIds", CampaignEvent::getPublicsIds);
			attributeGetterFunctions.put(
				"tagsNames", CampaignEvent::getTagsNames);
			attributeGetterFunctions.put(
				"bookingDescription", CampaignEvent::getBookingDescription);
			attributeGetterFunctions.put(
				"bookingURL", CampaignEvent::getBookingURL);
			attributeGetterFunctions.put(
				"registration", CampaignEvent::getRegistration);
			attributeGetterFunctions.put(
				"registrationStartDate",
				CampaignEvent::getRegistrationStartDate);
			attributeGetterFunctions.put(
				"registrationEndDate", CampaignEvent::getRegistrationEndDate);
			attributeGetterFunctions.put(
				"maxGauge", CampaignEvent::getMaxGauge);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CampaignEvent, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CampaignEvent, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<CampaignEvent, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setUuid);
			attributeSetterBiConsumers.put(
				"campaignEventId",
				(BiConsumer<CampaignEvent, Long>)
					CampaignEvent::setCampaignEventId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CampaignEvent, Date>)CampaignEvent::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CampaignEvent, Date>)
					CampaignEvent::setModifiedDate);
			attributeSetterBiConsumers.put(
				"lastPublishDate",
				(BiConsumer<CampaignEvent, Date>)
					CampaignEvent::setLastPublishDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<CampaignEvent, Integer>)CampaignEvent::setStatus);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setFirstName);
			attributeSetterBiConsumers.put(
				"lastName",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setLastName);
			attributeSetterBiConsumers.put(
				"phone",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setPhone);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setEmail);
			attributeSetterBiConsumers.put(
				"serviceId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setServiceId);
			attributeSetterBiConsumers.put(
				"service",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setService);
			attributeSetterBiConsumers.put(
				"onSiteFirstName",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setOnSiteFirstName);
			attributeSetterBiConsumers.put(
				"onSiteLastName",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setOnSiteLastName);
			attributeSetterBiConsumers.put(
				"onSitePhone",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setOnSitePhone);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setTitle);
			attributeSetterBiConsumers.put(
				"subtitle",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setSubtitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setDescription);
			attributeSetterBiConsumers.put(
				"imageId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setImageId);
			attributeSetterBiConsumers.put(
				"webImageId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setWebImageId);
			attributeSetterBiConsumers.put(
				"imageOwner",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setImageOwner);
			attributeSetterBiConsumers.put(
				"manifestationsIds",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setManifestationsIds);
			attributeSetterBiConsumers.put(
				"placeSIGId",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPlaceSIGId);
			attributeSetterBiConsumers.put(
				"placeName",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setPlaceName);
			attributeSetterBiConsumers.put(
				"placeStreetNumber",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPlaceStreetNumber);
			attributeSetterBiConsumers.put(
				"placeStreetName",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPlaceStreetName);
			attributeSetterBiConsumers.put(
				"placeZipCode",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPlaceZipCode);
			attributeSetterBiConsumers.put(
				"placeCityId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setPlaceCityId);
			attributeSetterBiConsumers.put(
				"placeCountry",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPlaceCountry);
			attributeSetterBiConsumers.put(
				"promoter",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setPromoter);
			attributeSetterBiConsumers.put(
				"publicPhone",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPublicPhone);
			attributeSetterBiConsumers.put(
				"publicEmail",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPublicEmail);
			attributeSetterBiConsumers.put(
				"websiteURL",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setWebsiteURL);
			attributeSetterBiConsumers.put(
				"websiteName",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setWebsiteName);
			attributeSetterBiConsumers.put(
				"free",
				(BiConsumer<CampaignEvent, Integer>)CampaignEvent::setFree);
			attributeSetterBiConsumers.put(
				"price",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setPrice);
			attributeSetterBiConsumers.put(
				"campaignId",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setCampaignId);
			attributeSetterBiConsumers.put(
				"themesIds",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setThemesIds);
			attributeSetterBiConsumers.put(
				"typesIds",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setTypesIds);
			attributeSetterBiConsumers.put(
				"publicsIds",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setPublicsIds);
			attributeSetterBiConsumers.put(
				"tagsNames",
				(BiConsumer<CampaignEvent, String>)CampaignEvent::setTagsNames);
			attributeSetterBiConsumers.put(
				"bookingDescription",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setBookingDescription);
			attributeSetterBiConsumers.put(
				"bookingURL",
				(BiConsumer<CampaignEvent, String>)
					CampaignEvent::setBookingURL);
			attributeSetterBiConsumers.put(
				"registration",
				(BiConsumer<CampaignEvent, Boolean>)
					CampaignEvent::setRegistration);
			attributeSetterBiConsumers.put(
				"registrationStartDate",
				(BiConsumer<CampaignEvent, Date>)
					CampaignEvent::setRegistrationStartDate);
			attributeSetterBiConsumers.put(
				"registrationEndDate",
				(BiConsumer<CampaignEvent, Date>)
					CampaignEvent::setRegistrationEndDate);
			attributeSetterBiConsumers.put(
				"maxGauge",
				(BiConsumer<CampaignEvent, Long>)CampaignEvent::setMaxGauge);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getCampaignEventId() {
		return _campaignEventId;
	}

	@Override
	public void setCampaignEventId(long campaignEventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_campaignEventId = campaignEventId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@Override
	public String getPhone() {
		if (_phone == null) {
			return "";
		}
		else {
			return _phone;
		}
	}

	@Override
	public void setPhone(String phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phone = phone;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public Long getServiceId() {
		return _serviceId;
	}

	@Override
	public void setServiceId(Long serviceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_serviceId = serviceId;
	}

	@Override
	public String getService() {
		if (_service == null) {
			return "";
		}
		else {
			return _service;
		}
	}

	@Override
	public void setService(String service) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_service = service;
	}

	@Override
	public String getOnSiteFirstName() {
		if (_onSiteFirstName == null) {
			return "";
		}
		else {
			return _onSiteFirstName;
		}
	}

	@Override
	public void setOnSiteFirstName(String onSiteFirstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_onSiteFirstName = onSiteFirstName;
	}

	@Override
	public String getOnSiteLastName() {
		if (_onSiteLastName == null) {
			return "";
		}
		else {
			return _onSiteLastName;
		}
	}

	@Override
	public void setOnSiteLastName(String onSiteLastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_onSiteLastName = onSiteLastName;
	}

	@Override
	public String getOnSitePhone() {
		if (_onSitePhone == null) {
			return "";
		}
		else {
			return _onSitePhone;
		}
	}

	@Override
	public void setOnSitePhone(String onSitePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_onSitePhone = onSitePhone;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getSubtitle() {
		if (_subtitle == null) {
			return "";
		}
		else {
			return _subtitle;
		}
	}

	@Override
	public String getSubtitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSubtitle(languageId);
	}

	@Override
	public String getSubtitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSubtitle(languageId, useDefault);
	}

	@Override
	public String getSubtitle(String languageId) {
		return LocalizationUtil.getLocalization(getSubtitle(), languageId);
	}

	@Override
	public String getSubtitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getSubtitle(), languageId, useDefault);
	}

	@Override
	public String getSubtitleCurrentLanguageId() {
		return _subtitleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getSubtitleCurrentValue() {
		Locale locale = getLocale(_subtitleCurrentLanguageId);

		return getSubtitle(locale);
	}

	@Override
	public Map<Locale, String> getSubtitleMap() {
		return LocalizationUtil.getLocalizationMap(getSubtitle());
	}

	@Override
	public void setSubtitle(String subtitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subtitle = subtitle;
	}

	@Override
	public void setSubtitle(String subtitle, Locale locale) {
		setSubtitle(subtitle, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSubtitle(
		String subtitle, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(subtitle)) {
			setSubtitle(
				LocalizationUtil.updateLocalization(
					getSubtitle(), "Subtitle", subtitle, languageId,
					defaultLanguageId));
		}
		else {
			setSubtitle(
				LocalizationUtil.removeLocalization(
					getSubtitle(), "Subtitle", languageId));
		}
	}

	@Override
	public void setSubtitleCurrentLanguageId(String languageId) {
		_subtitleCurrentLanguageId = languageId;
	}

	@Override
	public void setSubtitleMap(Map<Locale, String> subtitleMap) {
		setSubtitleMap(subtitleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSubtitleMap(
		Map<Locale, String> subtitleMap, Locale defaultLocale) {

		if (subtitleMap == null) {
			return;
		}

		setSubtitle(
			LocalizationUtil.updateLocalization(
				subtitleMap, getSubtitle(), "Subtitle",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(Long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@Override
	public Long getWebImageId() {
		return _webImageId;
	}

	@Override
	public void setWebImageId(Long webImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webImageId = webImageId;
	}

	@Override
	public String getImageOwner() {
		if (_imageOwner == null) {
			return "";
		}
		else {
			return _imageOwner;
		}
	}

	@Override
	public void setImageOwner(String imageOwner) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageOwner = imageOwner;
	}

	@Override
	public String getManifestationsIds() {
		if (_manifestationsIds == null) {
			return "";
		}
		else {
			return _manifestationsIds;
		}
	}

	@Override
	public void setManifestationsIds(String manifestationsIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manifestationsIds = manifestationsIds;
	}

	@Override
	public String getPlaceSIGId() {
		if (_placeSIGId == null) {
			return "";
		}
		else {
			return _placeSIGId;
		}
	}

	@Override
	public void setPlaceSIGId(String placeSIGId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeSIGId = placeSIGId;
	}

	@Override
	public String getPlaceName() {
		if (_placeName == null) {
			return "";
		}
		else {
			return _placeName;
		}
	}

	@Override
	public String getPlaceName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPlaceName(languageId);
	}

	@Override
	public String getPlaceName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPlaceName(languageId, useDefault);
	}

	@Override
	public String getPlaceName(String languageId) {
		return LocalizationUtil.getLocalization(getPlaceName(), languageId);
	}

	@Override
	public String getPlaceName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getPlaceName(), languageId, useDefault);
	}

	@Override
	public String getPlaceNameCurrentLanguageId() {
		return _placeNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getPlaceNameCurrentValue() {
		Locale locale = getLocale(_placeNameCurrentLanguageId);

		return getPlaceName(locale);
	}

	@Override
	public Map<Locale, String> getPlaceNameMap() {
		return LocalizationUtil.getLocalizationMap(getPlaceName());
	}

	@Override
	public void setPlaceName(String placeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeName = placeName;
	}

	@Override
	public void setPlaceName(String placeName, Locale locale) {
		setPlaceName(placeName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPlaceName(
		String placeName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(placeName)) {
			setPlaceName(
				LocalizationUtil.updateLocalization(
					getPlaceName(), "PlaceName", placeName, languageId,
					defaultLanguageId));
		}
		else {
			setPlaceName(
				LocalizationUtil.removeLocalization(
					getPlaceName(), "PlaceName", languageId));
		}
	}

	@Override
	public void setPlaceNameCurrentLanguageId(String languageId) {
		_placeNameCurrentLanguageId = languageId;
	}

	@Override
	public void setPlaceNameMap(Map<Locale, String> placeNameMap) {
		setPlaceNameMap(placeNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPlaceNameMap(
		Map<Locale, String> placeNameMap, Locale defaultLocale) {

		if (placeNameMap == null) {
			return;
		}

		setPlaceName(
			LocalizationUtil.updateLocalization(
				placeNameMap, getPlaceName(), "PlaceName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getPlaceStreetNumber() {
		if (_placeStreetNumber == null) {
			return "";
		}
		else {
			return _placeStreetNumber;
		}
	}

	@Override
	public void setPlaceStreetNumber(String placeStreetNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeStreetNumber = placeStreetNumber;
	}

	@Override
	public String getPlaceStreetName() {
		if (_placeStreetName == null) {
			return "";
		}
		else {
			return _placeStreetName;
		}
	}

	@Override
	public void setPlaceStreetName(String placeStreetName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeStreetName = placeStreetName;
	}

	@Override
	public String getPlaceZipCode() {
		if (_placeZipCode == null) {
			return "";
		}
		else {
			return _placeZipCode;
		}
	}

	@Override
	public void setPlaceZipCode(String placeZipCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeZipCode = placeZipCode;
	}

	@Override
	public Long getPlaceCityId() {
		return _placeCityId;
	}

	@Override
	public void setPlaceCityId(Long placeCityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeCityId = placeCityId;
	}

	@Override
	public String getPlaceCountry() {
		if (_placeCountry == null) {
			return "";
		}
		else {
			return _placeCountry;
		}
	}

	@Override
	public void setPlaceCountry(String placeCountry) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_placeCountry = placeCountry;
	}

	@Override
	public String getPromoter() {
		if (_promoter == null) {
			return "";
		}
		else {
			return _promoter;
		}
	}

	@Override
	public void setPromoter(String promoter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoter = promoter;
	}

	@Override
	public String getPublicPhone() {
		if (_publicPhone == null) {
			return "";
		}
		else {
			return _publicPhone;
		}
	}

	@Override
	public void setPublicPhone(String publicPhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicPhone = publicPhone;
	}

	@Override
	public String getPublicEmail() {
		if (_publicEmail == null) {
			return "";
		}
		else {
			return _publicEmail;
		}
	}

	@Override
	public void setPublicEmail(String publicEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicEmail = publicEmail;
	}

	@Override
	public String getWebsiteURL() {
		if (_websiteURL == null) {
			return "";
		}
		else {
			return _websiteURL;
		}
	}

	@Override
	public String getWebsiteURL(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getWebsiteURL(languageId);
	}

	@Override
	public String getWebsiteURL(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getWebsiteURL(languageId, useDefault);
	}

	@Override
	public String getWebsiteURL(String languageId) {
		return LocalizationUtil.getLocalization(getWebsiteURL(), languageId);
	}

	@Override
	public String getWebsiteURL(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getWebsiteURL(), languageId, useDefault);
	}

	@Override
	public String getWebsiteURLCurrentLanguageId() {
		return _websiteURLCurrentLanguageId;
	}

	@JSON
	@Override
	public String getWebsiteURLCurrentValue() {
		Locale locale = getLocale(_websiteURLCurrentLanguageId);

		return getWebsiteURL(locale);
	}

	@Override
	public Map<Locale, String> getWebsiteURLMap() {
		return LocalizationUtil.getLocalizationMap(getWebsiteURL());
	}

	@Override
	public void setWebsiteURL(String websiteURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_websiteURL = websiteURL;
	}

	@Override
	public void setWebsiteURL(String websiteURL, Locale locale) {
		setWebsiteURL(websiteURL, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setWebsiteURL(
		String websiteURL, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(websiteURL)) {
			setWebsiteURL(
				LocalizationUtil.updateLocalization(
					getWebsiteURL(), "WebsiteURL", websiteURL, languageId,
					defaultLanguageId));
		}
		else {
			setWebsiteURL(
				LocalizationUtil.removeLocalization(
					getWebsiteURL(), "WebsiteURL", languageId));
		}
	}

	@Override
	public void setWebsiteURLCurrentLanguageId(String languageId) {
		_websiteURLCurrentLanguageId = languageId;
	}

	@Override
	public void setWebsiteURLMap(Map<Locale, String> websiteURLMap) {
		setWebsiteURLMap(websiteURLMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setWebsiteURLMap(
		Map<Locale, String> websiteURLMap, Locale defaultLocale) {

		if (websiteURLMap == null) {
			return;
		}

		setWebsiteURL(
			LocalizationUtil.updateLocalization(
				websiteURLMap, getWebsiteURL(), "WebsiteURL",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getWebsiteName() {
		if (_websiteName == null) {
			return "";
		}
		else {
			return _websiteName;
		}
	}

	@Override
	public String getWebsiteName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getWebsiteName(languageId);
	}

	@Override
	public String getWebsiteName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getWebsiteName(languageId, useDefault);
	}

	@Override
	public String getWebsiteName(String languageId) {
		return LocalizationUtil.getLocalization(getWebsiteName(), languageId);
	}

	@Override
	public String getWebsiteName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getWebsiteName(), languageId, useDefault);
	}

	@Override
	public String getWebsiteNameCurrentLanguageId() {
		return _websiteNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getWebsiteNameCurrentValue() {
		Locale locale = getLocale(_websiteNameCurrentLanguageId);

		return getWebsiteName(locale);
	}

	@Override
	public Map<Locale, String> getWebsiteNameMap() {
		return LocalizationUtil.getLocalizationMap(getWebsiteName());
	}

	@Override
	public void setWebsiteName(String websiteName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_websiteName = websiteName;
	}

	@Override
	public void setWebsiteName(String websiteName, Locale locale) {
		setWebsiteName(websiteName, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setWebsiteName(
		String websiteName, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(websiteName)) {
			setWebsiteName(
				LocalizationUtil.updateLocalization(
					getWebsiteName(), "WebsiteName", websiteName, languageId,
					defaultLanguageId));
		}
		else {
			setWebsiteName(
				LocalizationUtil.removeLocalization(
					getWebsiteName(), "WebsiteName", languageId));
		}
	}

	@Override
	public void setWebsiteNameCurrentLanguageId(String languageId) {
		_websiteNameCurrentLanguageId = languageId;
	}

	@Override
	public void setWebsiteNameMap(Map<Locale, String> websiteNameMap) {
		setWebsiteNameMap(websiteNameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setWebsiteNameMap(
		Map<Locale, String> websiteNameMap, Locale defaultLocale) {

		if (websiteNameMap == null) {
			return;
		}

		setWebsiteName(
			LocalizationUtil.updateLocalization(
				websiteNameMap, getWebsiteName(), "WebsiteName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Integer getFree() {
		return _free;
	}

	@Override
	public void setFree(Integer free) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_free = free;
	}

	@Override
	public String getPrice() {
		if (_price == null) {
			return "";
		}
		else {
			return _price;
		}
	}

	@Override
	public String getPrice(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPrice(languageId);
	}

	@Override
	public String getPrice(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getPrice(languageId, useDefault);
	}

	@Override
	public String getPrice(String languageId) {
		return LocalizationUtil.getLocalization(getPrice(), languageId);
	}

	@Override
	public String getPrice(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getPrice(), languageId, useDefault);
	}

	@Override
	public String getPriceCurrentLanguageId() {
		return _priceCurrentLanguageId;
	}

	@JSON
	@Override
	public String getPriceCurrentValue() {
		Locale locale = getLocale(_priceCurrentLanguageId);

		return getPrice(locale);
	}

	@Override
	public Map<Locale, String> getPriceMap() {
		return LocalizationUtil.getLocalizationMap(getPrice());
	}

	@Override
	public void setPrice(String price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	@Override
	public void setPrice(String price, Locale locale) {
		setPrice(price, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPrice(String price, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(price)) {
			setPrice(
				LocalizationUtil.updateLocalization(
					getPrice(), "Price", price, languageId, defaultLanguageId));
		}
		else {
			setPrice(
				LocalizationUtil.removeLocalization(
					getPrice(), "Price", languageId));
		}
	}

	@Override
	public void setPriceCurrentLanguageId(String languageId) {
		_priceCurrentLanguageId = languageId;
	}

	@Override
	public void setPriceMap(Map<Locale, String> priceMap) {
		setPriceMap(priceMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setPriceMap(
		Map<Locale, String> priceMap, Locale defaultLocale) {

		if (priceMap == null) {
			return;
		}

		setPrice(
			LocalizationUtil.updateLocalization(
				priceMap, getPrice(), "Price",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Long getCampaignId() {
		return _campaignId;
	}

	@Override
	public void setCampaignId(Long campaignId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_campaignId = campaignId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Long getOriginalCampaignId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("campaignId"));
	}

	@Override
	public String getThemesIds() {
		if (_themesIds == null) {
			return "";
		}
		else {
			return _themesIds;
		}
	}

	@Override
	public void setThemesIds(String themesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_themesIds = themesIds;
	}

	@Override
	public String getTypesIds() {
		if (_typesIds == null) {
			return "";
		}
		else {
			return _typesIds;
		}
	}

	@Override
	public void setTypesIds(String typesIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typesIds = typesIds;
	}

	@Override
	public String getPublicsIds() {
		if (_publicsIds == null) {
			return "";
		}
		else {
			return _publicsIds;
		}
	}

	@Override
	public void setPublicsIds(String publicsIds) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicsIds = publicsIds;
	}

	@Override
	public String getTagsNames() {
		if (_tagsNames == null) {
			return "";
		}
		else {
			return _tagsNames;
		}
	}

	@Override
	public void setTagsNames(String tagsNames) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tagsNames = tagsNames;
	}

	@Override
	public String getBookingDescription() {
		if (_bookingDescription == null) {
			return "";
		}
		else {
			return _bookingDescription;
		}
	}

	@Override
	public String getBookingDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBookingDescription(languageId);
	}

	@Override
	public String getBookingDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBookingDescription(languageId, useDefault);
	}

	@Override
	public String getBookingDescription(String languageId) {
		return LocalizationUtil.getLocalization(
			getBookingDescription(), languageId);
	}

	@Override
	public String getBookingDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getBookingDescription(), languageId, useDefault);
	}

	@Override
	public String getBookingDescriptionCurrentLanguageId() {
		return _bookingDescriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getBookingDescriptionCurrentValue() {
		Locale locale = getLocale(_bookingDescriptionCurrentLanguageId);

		return getBookingDescription(locale);
	}

	@Override
	public Map<Locale, String> getBookingDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getBookingDescription());
	}

	@Override
	public void setBookingDescription(String bookingDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingDescription = bookingDescription;
	}

	@Override
	public void setBookingDescription(
		String bookingDescription, Locale locale) {

		setBookingDescription(
			bookingDescription, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setBookingDescription(
		String bookingDescription, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(bookingDescription)) {
			setBookingDescription(
				LocalizationUtil.updateLocalization(
					getBookingDescription(), "BookingDescription",
					bookingDescription, languageId, defaultLanguageId));
		}
		else {
			setBookingDescription(
				LocalizationUtil.removeLocalization(
					getBookingDescription(), "BookingDescription", languageId));
		}
	}

	@Override
	public void setBookingDescriptionCurrentLanguageId(String languageId) {
		_bookingDescriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setBookingDescriptionMap(
		Map<Locale, String> bookingDescriptionMap) {

		setBookingDescriptionMap(
			bookingDescriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setBookingDescriptionMap(
		Map<Locale, String> bookingDescriptionMap, Locale defaultLocale) {

		if (bookingDescriptionMap == null) {
			return;
		}

		setBookingDescription(
			LocalizationUtil.updateLocalization(
				bookingDescriptionMap, getBookingDescription(),
				"BookingDescription", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getBookingURL() {
		if (_bookingURL == null) {
			return "";
		}
		else {
			return _bookingURL;
		}
	}

	@Override
	public void setBookingURL(String bookingURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingURL = bookingURL;
	}

	@Override
	public boolean getRegistration() {
		return _registration;
	}

	@Override
	public boolean isRegistration() {
		return _registration;
	}

	@Override
	public void setRegistration(boolean registration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registration = registration;
	}

	@Override
	public Date getRegistrationStartDate() {
		return _registrationStartDate;
	}

	@Override
	public void setRegistrationStartDate(Date registrationStartDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationStartDate = registrationStartDate;
	}

	@Override
	public Date getRegistrationEndDate() {
		return _registrationEndDate;
	}

	@Override
	public void setRegistrationEndDate(Date registrationEndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationEndDate = registrationEndDate;
	}

	@Override
	public long getMaxGauge() {
		return _maxGauge;
	}

	@Override
	public void setMaxGauge(long maxGauge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maxGauge = maxGauge;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CampaignEvent.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CampaignEvent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> subtitleMap = getSubtitleMap();

		for (Map.Entry<Locale, String> entry : subtitleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> placeNameMap = getPlaceNameMap();

		for (Map.Entry<Locale, String> entry : placeNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> websiteURLMap = getWebsiteURLMap();

		for (Map.Entry<Locale, String> entry : websiteURLMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> websiteNameMap = getWebsiteNameMap();

		for (Map.Entry<Locale, String> entry : websiteNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> priceMap = getPriceMap();

		for (Map.Entry<Locale, String> entry : priceMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> bookingDescriptionMap = getBookingDescriptionMap();

		for (Map.Entry<Locale, String> entry :
				bookingDescriptionMap.entrySet()) {

			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			CampaignEvent.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String subtitle = getSubtitle(defaultLocale);

		if (Validator.isNull(subtitle)) {
			setSubtitle(getSubtitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setSubtitle(
				getSubtitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}

		String placeName = getPlaceName(defaultLocale);

		if (Validator.isNull(placeName)) {
			setPlaceName(getPlaceName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setPlaceName(
				getPlaceName(defaultLocale), defaultLocale, defaultLocale);
		}

		String websiteURL = getWebsiteURL(defaultLocale);

		if (Validator.isNull(websiteURL)) {
			setWebsiteURL(getWebsiteURL(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setWebsiteURL(
				getWebsiteURL(defaultLocale), defaultLocale, defaultLocale);
		}

		String websiteName = getWebsiteName(defaultLocale);

		if (Validator.isNull(websiteName)) {
			setWebsiteName(
				getWebsiteName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setWebsiteName(
				getWebsiteName(defaultLocale), defaultLocale, defaultLocale);
		}

		String price = getPrice(defaultLocale);

		if (Validator.isNull(price)) {
			setPrice(getPrice(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setPrice(getPrice(defaultLocale), defaultLocale, defaultLocale);
		}

		String bookingDescription = getBookingDescription(defaultLocale);

		if (Validator.isNull(bookingDescription)) {
			setBookingDescription(
				getBookingDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setBookingDescription(
				getBookingDescription(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public CampaignEvent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CampaignEvent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CampaignEventImpl campaignEventImpl = new CampaignEventImpl();

		campaignEventImpl.setUuid(getUuid());
		campaignEventImpl.setCampaignEventId(getCampaignEventId());
		campaignEventImpl.setGroupId(getGroupId());
		campaignEventImpl.setCompanyId(getCompanyId());
		campaignEventImpl.setUserId(getUserId());
		campaignEventImpl.setUserName(getUserName());
		campaignEventImpl.setCreateDate(getCreateDate());
		campaignEventImpl.setModifiedDate(getModifiedDate());
		campaignEventImpl.setLastPublishDate(getLastPublishDate());
		campaignEventImpl.setStatus(getStatus());
		campaignEventImpl.setFirstName(getFirstName());
		campaignEventImpl.setLastName(getLastName());
		campaignEventImpl.setPhone(getPhone());
		campaignEventImpl.setEmail(getEmail());
		campaignEventImpl.setServiceId(getServiceId());
		campaignEventImpl.setService(getService());
		campaignEventImpl.setOnSiteFirstName(getOnSiteFirstName());
		campaignEventImpl.setOnSiteLastName(getOnSiteLastName());
		campaignEventImpl.setOnSitePhone(getOnSitePhone());
		campaignEventImpl.setTitle(getTitle());
		campaignEventImpl.setSubtitle(getSubtitle());
		campaignEventImpl.setDescription(getDescription());
		campaignEventImpl.setImageId(getImageId());
		campaignEventImpl.setWebImageId(getWebImageId());
		campaignEventImpl.setImageOwner(getImageOwner());
		campaignEventImpl.setManifestationsIds(getManifestationsIds());
		campaignEventImpl.setPlaceSIGId(getPlaceSIGId());
		campaignEventImpl.setPlaceName(getPlaceName());
		campaignEventImpl.setPlaceStreetNumber(getPlaceStreetNumber());
		campaignEventImpl.setPlaceStreetName(getPlaceStreetName());
		campaignEventImpl.setPlaceZipCode(getPlaceZipCode());
		campaignEventImpl.setPlaceCityId(getPlaceCityId());
		campaignEventImpl.setPlaceCountry(getPlaceCountry());
		campaignEventImpl.setPromoter(getPromoter());
		campaignEventImpl.setPublicPhone(getPublicPhone());
		campaignEventImpl.setPublicEmail(getPublicEmail());
		campaignEventImpl.setWebsiteURL(getWebsiteURL());
		campaignEventImpl.setWebsiteName(getWebsiteName());
		campaignEventImpl.setFree(getFree());
		campaignEventImpl.setPrice(getPrice());
		campaignEventImpl.setCampaignId(getCampaignId());
		campaignEventImpl.setThemesIds(getThemesIds());
		campaignEventImpl.setTypesIds(getTypesIds());
		campaignEventImpl.setPublicsIds(getPublicsIds());
		campaignEventImpl.setTagsNames(getTagsNames());
		campaignEventImpl.setBookingDescription(getBookingDescription());
		campaignEventImpl.setBookingURL(getBookingURL());
		campaignEventImpl.setRegistration(isRegistration());
		campaignEventImpl.setRegistrationStartDate(getRegistrationStartDate());
		campaignEventImpl.setRegistrationEndDate(getRegistrationEndDate());
		campaignEventImpl.setMaxGauge(getMaxGauge());

		campaignEventImpl.resetOriginalValues();

		return campaignEventImpl;
	}

	@Override
	public CampaignEvent cloneWithOriginalValues() {
		CampaignEventImpl campaignEventImpl = new CampaignEventImpl();

		campaignEventImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		campaignEventImpl.setCampaignEventId(
			this.<Long>getColumnOriginalValue("campaignEventId"));
		campaignEventImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		campaignEventImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		campaignEventImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		campaignEventImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		campaignEventImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		campaignEventImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		campaignEventImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		campaignEventImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		campaignEventImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		campaignEventImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		campaignEventImpl.setPhone(
			this.<String>getColumnOriginalValue("phone"));
		campaignEventImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		campaignEventImpl.setServiceId(
			this.<Long>getColumnOriginalValue("serviceId"));
		campaignEventImpl.setService(
			this.<String>getColumnOriginalValue("service"));
		campaignEventImpl.setOnSiteFirstName(
			this.<String>getColumnOriginalValue("onSiteFirstName"));
		campaignEventImpl.setOnSiteLastName(
			this.<String>getColumnOriginalValue("onSiteLastName"));
		campaignEventImpl.setOnSitePhone(
			this.<String>getColumnOriginalValue("onSitePhone"));
		campaignEventImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		campaignEventImpl.setSubtitle(
			this.<String>getColumnOriginalValue("subtitle"));
		campaignEventImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		campaignEventImpl.setImageId(
			this.<Long>getColumnOriginalValue("imageId"));
		campaignEventImpl.setWebImageId(
			this.<Long>getColumnOriginalValue("webImageId"));
		campaignEventImpl.setImageOwner(
			this.<String>getColumnOriginalValue("imageOwner"));
		campaignEventImpl.setManifestationsIds(
			this.<String>getColumnOriginalValue("manifestationsIds"));
		campaignEventImpl.setPlaceSIGId(
			this.<String>getColumnOriginalValue("placeSIGId"));
		campaignEventImpl.setPlaceName(
			this.<String>getColumnOriginalValue("placeName"));
		campaignEventImpl.setPlaceStreetNumber(
			this.<String>getColumnOriginalValue("placeStreetNumber"));
		campaignEventImpl.setPlaceStreetName(
			this.<String>getColumnOriginalValue("placeStreetName"));
		campaignEventImpl.setPlaceZipCode(
			this.<String>getColumnOriginalValue("placeZipCode"));
		campaignEventImpl.setPlaceCityId(
			this.<Long>getColumnOriginalValue("placeCityId"));
		campaignEventImpl.setPlaceCountry(
			this.<String>getColumnOriginalValue("placeCountry"));
		campaignEventImpl.setPromoter(
			this.<String>getColumnOriginalValue("promoter"));
		campaignEventImpl.setPublicPhone(
			this.<String>getColumnOriginalValue("publicPhone"));
		campaignEventImpl.setPublicEmail(
			this.<String>getColumnOriginalValue("publicEmail"));
		campaignEventImpl.setWebsiteURL(
			this.<String>getColumnOriginalValue("websiteURL"));
		campaignEventImpl.setWebsiteName(
			this.<String>getColumnOriginalValue("websiteName"));
		campaignEventImpl.setFree(this.<Integer>getColumnOriginalValue("free"));
		campaignEventImpl.setPrice(
			this.<String>getColumnOriginalValue("price"));
		campaignEventImpl.setCampaignId(
			this.<Long>getColumnOriginalValue("campaignId"));
		campaignEventImpl.setThemesIds(
			this.<String>getColumnOriginalValue("themesIds"));
		campaignEventImpl.setTypesIds(
			this.<String>getColumnOriginalValue("typesIds"));
		campaignEventImpl.setPublicsIds(
			this.<String>getColumnOriginalValue("publicsIds"));
		campaignEventImpl.setTagsNames(
			this.<String>getColumnOriginalValue("tagsNames"));
		campaignEventImpl.setBookingDescription(
			this.<String>getColumnOriginalValue("bookingDescription"));
		campaignEventImpl.setBookingURL(
			this.<String>getColumnOriginalValue("bookingURL"));
		campaignEventImpl.setRegistration(
			this.<Boolean>getColumnOriginalValue("registration"));
		campaignEventImpl.setRegistrationStartDate(
			this.<Date>getColumnOriginalValue("registrationStartDate"));
		campaignEventImpl.setRegistrationEndDate(
			this.<Date>getColumnOriginalValue("registrationEndDate"));
		campaignEventImpl.setMaxGauge(
			this.<Long>getColumnOriginalValue("maxGauge"));

		return campaignEventImpl;
	}

	@Override
	public int compareTo(CampaignEvent campaignEvent) {
		long primaryKey = campaignEvent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CampaignEvent)) {
			return false;
		}

		CampaignEvent campaignEvent = (CampaignEvent)object;

		long primaryKey = campaignEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CampaignEvent> toCacheModel() {
		CampaignEventCacheModel campaignEventCacheModel =
			new CampaignEventCacheModel();

		campaignEventCacheModel.uuid = getUuid();

		String uuid = campaignEventCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			campaignEventCacheModel.uuid = null;
		}

		campaignEventCacheModel.campaignEventId = getCampaignEventId();

		campaignEventCacheModel.groupId = getGroupId();

		campaignEventCacheModel.companyId = getCompanyId();

		campaignEventCacheModel.userId = getUserId();

		campaignEventCacheModel.userName = getUserName();

		String userName = campaignEventCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			campaignEventCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			campaignEventCacheModel.createDate = createDate.getTime();
		}
		else {
			campaignEventCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			campaignEventCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			campaignEventCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			campaignEventCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			campaignEventCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		campaignEventCacheModel.status = getStatus();

		campaignEventCacheModel.firstName = getFirstName();

		String firstName = campaignEventCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			campaignEventCacheModel.firstName = null;
		}

		campaignEventCacheModel.lastName = getLastName();

		String lastName = campaignEventCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			campaignEventCacheModel.lastName = null;
		}

		campaignEventCacheModel.phone = getPhone();

		String phone = campaignEventCacheModel.phone;

		if ((phone != null) && (phone.length() == 0)) {
			campaignEventCacheModel.phone = null;
		}

		campaignEventCacheModel.email = getEmail();

		String email = campaignEventCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			campaignEventCacheModel.email = null;
		}

		Long serviceId = getServiceId();

		if (serviceId != null) {
			campaignEventCacheModel.serviceId = serviceId;
		}

		campaignEventCacheModel.service = getService();

		String service = campaignEventCacheModel.service;

		if ((service != null) && (service.length() == 0)) {
			campaignEventCacheModel.service = null;
		}

		campaignEventCacheModel.onSiteFirstName = getOnSiteFirstName();

		String onSiteFirstName = campaignEventCacheModel.onSiteFirstName;

		if ((onSiteFirstName != null) && (onSiteFirstName.length() == 0)) {
			campaignEventCacheModel.onSiteFirstName = null;
		}

		campaignEventCacheModel.onSiteLastName = getOnSiteLastName();

		String onSiteLastName = campaignEventCacheModel.onSiteLastName;

		if ((onSiteLastName != null) && (onSiteLastName.length() == 0)) {
			campaignEventCacheModel.onSiteLastName = null;
		}

		campaignEventCacheModel.onSitePhone = getOnSitePhone();

		String onSitePhone = campaignEventCacheModel.onSitePhone;

		if ((onSitePhone != null) && (onSitePhone.length() == 0)) {
			campaignEventCacheModel.onSitePhone = null;
		}

		campaignEventCacheModel.title = getTitle();

		String title = campaignEventCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			campaignEventCacheModel.title = null;
		}

		campaignEventCacheModel.subtitle = getSubtitle();

		String subtitle = campaignEventCacheModel.subtitle;

		if ((subtitle != null) && (subtitle.length() == 0)) {
			campaignEventCacheModel.subtitle = null;
		}

		campaignEventCacheModel.description = getDescription();

		String description = campaignEventCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			campaignEventCacheModel.description = null;
		}

		Long imageId = getImageId();

		if (imageId != null) {
			campaignEventCacheModel.imageId = imageId;
		}

		Long webImageId = getWebImageId();

		if (webImageId != null) {
			campaignEventCacheModel.webImageId = webImageId;
		}

		campaignEventCacheModel.imageOwner = getImageOwner();

		String imageOwner = campaignEventCacheModel.imageOwner;

		if ((imageOwner != null) && (imageOwner.length() == 0)) {
			campaignEventCacheModel.imageOwner = null;
		}

		campaignEventCacheModel.manifestationsIds = getManifestationsIds();

		String manifestationsIds = campaignEventCacheModel.manifestationsIds;

		if ((manifestationsIds != null) && (manifestationsIds.length() == 0)) {
			campaignEventCacheModel.manifestationsIds = null;
		}

		campaignEventCacheModel.placeSIGId = getPlaceSIGId();

		String placeSIGId = campaignEventCacheModel.placeSIGId;

		if ((placeSIGId != null) && (placeSIGId.length() == 0)) {
			campaignEventCacheModel.placeSIGId = null;
		}

		campaignEventCacheModel.placeName = getPlaceName();

		String placeName = campaignEventCacheModel.placeName;

		if ((placeName != null) && (placeName.length() == 0)) {
			campaignEventCacheModel.placeName = null;
		}

		campaignEventCacheModel.placeStreetNumber = getPlaceStreetNumber();

		String placeStreetNumber = campaignEventCacheModel.placeStreetNumber;

		if ((placeStreetNumber != null) && (placeStreetNumber.length() == 0)) {
			campaignEventCacheModel.placeStreetNumber = null;
		}

		campaignEventCacheModel.placeStreetName = getPlaceStreetName();

		String placeStreetName = campaignEventCacheModel.placeStreetName;

		if ((placeStreetName != null) && (placeStreetName.length() == 0)) {
			campaignEventCacheModel.placeStreetName = null;
		}

		campaignEventCacheModel.placeZipCode = getPlaceZipCode();

		String placeZipCode = campaignEventCacheModel.placeZipCode;

		if ((placeZipCode != null) && (placeZipCode.length() == 0)) {
			campaignEventCacheModel.placeZipCode = null;
		}

		Long placeCityId = getPlaceCityId();

		if (placeCityId != null) {
			campaignEventCacheModel.placeCityId = placeCityId;
		}

		campaignEventCacheModel.placeCountry = getPlaceCountry();

		String placeCountry = campaignEventCacheModel.placeCountry;

		if ((placeCountry != null) && (placeCountry.length() == 0)) {
			campaignEventCacheModel.placeCountry = null;
		}

		campaignEventCacheModel.promoter = getPromoter();

		String promoter = campaignEventCacheModel.promoter;

		if ((promoter != null) && (promoter.length() == 0)) {
			campaignEventCacheModel.promoter = null;
		}

		campaignEventCacheModel.publicPhone = getPublicPhone();

		String publicPhone = campaignEventCacheModel.publicPhone;

		if ((publicPhone != null) && (publicPhone.length() == 0)) {
			campaignEventCacheModel.publicPhone = null;
		}

		campaignEventCacheModel.publicEmail = getPublicEmail();

		String publicEmail = campaignEventCacheModel.publicEmail;

		if ((publicEmail != null) && (publicEmail.length() == 0)) {
			campaignEventCacheModel.publicEmail = null;
		}

		campaignEventCacheModel.websiteURL = getWebsiteURL();

		String websiteURL = campaignEventCacheModel.websiteURL;

		if ((websiteURL != null) && (websiteURL.length() == 0)) {
			campaignEventCacheModel.websiteURL = null;
		}

		campaignEventCacheModel.websiteName = getWebsiteName();

		String websiteName = campaignEventCacheModel.websiteName;

		if ((websiteName != null) && (websiteName.length() == 0)) {
			campaignEventCacheModel.websiteName = null;
		}

		Integer free = getFree();

		if (free != null) {
			campaignEventCacheModel.free = free;
		}

		campaignEventCacheModel.price = getPrice();

		String price = campaignEventCacheModel.price;

		if ((price != null) && (price.length() == 0)) {
			campaignEventCacheModel.price = null;
		}

		Long campaignId = getCampaignId();

		if (campaignId != null) {
			campaignEventCacheModel.campaignId = campaignId;
		}

		campaignEventCacheModel.themesIds = getThemesIds();

		String themesIds = campaignEventCacheModel.themesIds;

		if ((themesIds != null) && (themesIds.length() == 0)) {
			campaignEventCacheModel.themesIds = null;
		}

		campaignEventCacheModel.typesIds = getTypesIds();

		String typesIds = campaignEventCacheModel.typesIds;

		if ((typesIds != null) && (typesIds.length() == 0)) {
			campaignEventCacheModel.typesIds = null;
		}

		campaignEventCacheModel.publicsIds = getPublicsIds();

		String publicsIds = campaignEventCacheModel.publicsIds;

		if ((publicsIds != null) && (publicsIds.length() == 0)) {
			campaignEventCacheModel.publicsIds = null;
		}

		campaignEventCacheModel.tagsNames = getTagsNames();

		String tagsNames = campaignEventCacheModel.tagsNames;

		if ((tagsNames != null) && (tagsNames.length() == 0)) {
			campaignEventCacheModel.tagsNames = null;
		}

		campaignEventCacheModel.bookingDescription = getBookingDescription();

		String bookingDescription = campaignEventCacheModel.bookingDescription;

		if ((bookingDescription != null) &&
			(bookingDescription.length() == 0)) {

			campaignEventCacheModel.bookingDescription = null;
		}

		campaignEventCacheModel.bookingURL = getBookingURL();

		String bookingURL = campaignEventCacheModel.bookingURL;

		if ((bookingURL != null) && (bookingURL.length() == 0)) {
			campaignEventCacheModel.bookingURL = null;
		}

		campaignEventCacheModel.registration = isRegistration();

		Date registrationStartDate = getRegistrationStartDate();

		if (registrationStartDate != null) {
			campaignEventCacheModel.registrationStartDate =
				registrationStartDate.getTime();
		}
		else {
			campaignEventCacheModel.registrationStartDate = Long.MIN_VALUE;
		}

		Date registrationEndDate = getRegistrationEndDate();

		if (registrationEndDate != null) {
			campaignEventCacheModel.registrationEndDate =
				registrationEndDate.getTime();
		}
		else {
			campaignEventCacheModel.registrationEndDate = Long.MIN_VALUE;
		}

		campaignEventCacheModel.maxGauge = getMaxGauge();

		return campaignEventCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CampaignEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CampaignEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CampaignEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CampaignEvent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CampaignEvent>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CampaignEvent.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _campaignEventId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private String _firstName;
	private String _lastName;
	private String _phone;
	private String _email;
	private Long _serviceId;
	private String _service;
	private String _onSiteFirstName;
	private String _onSiteLastName;
	private String _onSitePhone;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _subtitle;
	private String _subtitleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private Long _imageId;
	private Long _webImageId;
	private String _imageOwner;
	private String _manifestationsIds;
	private String _placeSIGId;
	private String _placeName;
	private String _placeNameCurrentLanguageId;
	private String _placeStreetNumber;
	private String _placeStreetName;
	private String _placeZipCode;
	private Long _placeCityId;
	private String _placeCountry;
	private String _promoter;
	private String _publicPhone;
	private String _publicEmail;
	private String _websiteURL;
	private String _websiteURLCurrentLanguageId;
	private String _websiteName;
	private String _websiteNameCurrentLanguageId;
	private Integer _free;
	private String _price;
	private String _priceCurrentLanguageId;
	private Long _campaignId;
	private String _themesIds;
	private String _typesIds;
	private String _publicsIds;
	private String _tagsNames;
	private String _bookingDescription;
	private String _bookingDescriptionCurrentLanguageId;
	private String _bookingURL;
	private boolean _registration;
	private Date _registrationStartDate;
	private Date _registrationEndDate;
	private long _maxGauge;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CampaignEvent, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CampaignEvent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("campaignEventId", _campaignEventId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("phone", _phone);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("serviceId", _serviceId);
		_columnOriginalValues.put("service", _service);
		_columnOriginalValues.put("onSiteFirstName", _onSiteFirstName);
		_columnOriginalValues.put("onSiteLastName", _onSiteLastName);
		_columnOriginalValues.put("onSitePhone", _onSitePhone);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("subtitle", _subtitle);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("webImageId", _webImageId);
		_columnOriginalValues.put("imageOwner", _imageOwner);
		_columnOriginalValues.put("manifestationsIds", _manifestationsIds);
		_columnOriginalValues.put("placeSIGId", _placeSIGId);
		_columnOriginalValues.put("placeName", _placeName);
		_columnOriginalValues.put("placeStreetNumber", _placeStreetNumber);
		_columnOriginalValues.put("placeStreetName", _placeStreetName);
		_columnOriginalValues.put("placeZipCode", _placeZipCode);
		_columnOriginalValues.put("placeCityId", _placeCityId);
		_columnOriginalValues.put("placeCountry", _placeCountry);
		_columnOriginalValues.put("promoter", _promoter);
		_columnOriginalValues.put("publicPhone", _publicPhone);
		_columnOriginalValues.put("publicEmail", _publicEmail);
		_columnOriginalValues.put("websiteURL", _websiteURL);
		_columnOriginalValues.put("websiteName", _websiteName);
		_columnOriginalValues.put("free", _free);
		_columnOriginalValues.put("price", _price);
		_columnOriginalValues.put("campaignId", _campaignId);
		_columnOriginalValues.put("themesIds", _themesIds);
		_columnOriginalValues.put("typesIds", _typesIds);
		_columnOriginalValues.put("publicsIds", _publicsIds);
		_columnOriginalValues.put("tagsNames", _tagsNames);
		_columnOriginalValues.put("bookingDescription", _bookingDescription);
		_columnOriginalValues.put("bookingURL", _bookingURL);
		_columnOriginalValues.put("registration", _registration);
		_columnOriginalValues.put(
			"registrationStartDate", _registrationStartDate);
		_columnOriginalValues.put("registrationEndDate", _registrationEndDate);
		_columnOriginalValues.put("maxGauge", _maxGauge);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("campaignEventId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("lastPublishDate", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("firstName", 1024L);

		columnBitmasks.put("lastName", 2048L);

		columnBitmasks.put("phone", 4096L);

		columnBitmasks.put("email", 8192L);

		columnBitmasks.put("serviceId", 16384L);

		columnBitmasks.put("service", 32768L);

		columnBitmasks.put("onSiteFirstName", 65536L);

		columnBitmasks.put("onSiteLastName", 131072L);

		columnBitmasks.put("onSitePhone", 262144L);

		columnBitmasks.put("title", 524288L);

		columnBitmasks.put("subtitle", 1048576L);

		columnBitmasks.put("description", 2097152L);

		columnBitmasks.put("imageId", 4194304L);

		columnBitmasks.put("webImageId", 8388608L);

		columnBitmasks.put("imageOwner", 16777216L);

		columnBitmasks.put("manifestationsIds", 33554432L);

		columnBitmasks.put("placeSIGId", 67108864L);

		columnBitmasks.put("placeName", 134217728L);

		columnBitmasks.put("placeStreetNumber", 268435456L);

		columnBitmasks.put("placeStreetName", 536870912L);

		columnBitmasks.put("placeZipCode", 1073741824L);

		columnBitmasks.put("placeCityId", 2147483648L);

		columnBitmasks.put("placeCountry", 4294967296L);

		columnBitmasks.put("promoter", 8589934592L);

		columnBitmasks.put("publicPhone", 17179869184L);

		columnBitmasks.put("publicEmail", 34359738368L);

		columnBitmasks.put("websiteURL", 68719476736L);

		columnBitmasks.put("websiteName", 137438953472L);

		columnBitmasks.put("free", 274877906944L);

		columnBitmasks.put("price", 549755813888L);

		columnBitmasks.put("campaignId", 1099511627776L);

		columnBitmasks.put("themesIds", 2199023255552L);

		columnBitmasks.put("typesIds", 4398046511104L);

		columnBitmasks.put("publicsIds", 8796093022208L);

		columnBitmasks.put("tagsNames", 17592186044416L);

		columnBitmasks.put("bookingDescription", 35184372088832L);

		columnBitmasks.put("bookingURL", 70368744177664L);

		columnBitmasks.put("registration", 140737488355328L);

		columnBitmasks.put("registrationStartDate", 281474976710656L);

		columnBitmasks.put("registrationEndDate", 562949953421312L);

		columnBitmasks.put("maxGauge", 1125899906842624L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CampaignEvent _escapedModel;

}