/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.agenda.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import eu.strasbourg.service.agenda.model.EventParticipation;
import eu.strasbourg.service.agenda.model.EventParticipationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EventParticipation service. Represents a row in the &quot;agenda_EventParticipation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EventParticipationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventParticipationImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see EventParticipationImpl
 * @generated
 */
@JSON(strict = true)
public class EventParticipationModelImpl
	extends BaseModelImpl<EventParticipation>
	implements EventParticipationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event participation model instance should use the <code>EventParticipation</code> interface instead.
	 */
	public static final String TABLE_NAME = "agenda_EventParticipation";

	public static final Object[][] TABLE_COLUMNS = {
		{"eventParticipationId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"publikUserId", Types.VARCHAR}, {"eventId", Types.BIGINT},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("eventParticipationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publikUserId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agenda_EventParticipation (eventParticipationId LONG not null primary key,createDate DATE null,publikUserId VARCHAR(75) null,eventId LONG,groupId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table agenda_EventParticipation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eventParticipation.eventParticipationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agenda_EventParticipation.eventParticipationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLIKUSERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVENTPARTICIPATIONID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.agenda.model.EventParticipation"));

	public EventParticipationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eventParticipationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEventParticipationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eventParticipationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventParticipation.class;
	}

	@Override
	public String getModelClassName() {
		return EventParticipation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EventParticipation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EventParticipation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventParticipation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EventParticipation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EventParticipation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EventParticipation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EventParticipation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EventParticipation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EventParticipation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EventParticipation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EventParticipation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EventParticipation, Object>>();

			attributeGetterFunctions.put(
				"eventParticipationId",
				EventParticipation::getEventParticipationId);
			attributeGetterFunctions.put(
				"createDate", EventParticipation::getCreateDate);
			attributeGetterFunctions.put(
				"publikUserId", EventParticipation::getPublikUserId);
			attributeGetterFunctions.put(
				"eventId", EventParticipation::getEventId);
			attributeGetterFunctions.put(
				"groupId", EventParticipation::getGroupId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EventParticipation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EventParticipation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EventParticipation, ?>>();

			attributeSetterBiConsumers.put(
				"eventParticipationId",
				(BiConsumer<EventParticipation, Long>)
					EventParticipation::setEventParticipationId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EventParticipation, Date>)
					EventParticipation::setCreateDate);
			attributeSetterBiConsumers.put(
				"publikUserId",
				(BiConsumer<EventParticipation, String>)
					EventParticipation::setPublikUserId);
			attributeSetterBiConsumers.put(
				"eventId",
				(BiConsumer<EventParticipation, Long>)
					EventParticipation::setEventId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EventParticipation, Long>)
					EventParticipation::setGroupId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getEventParticipationId() {
		return _eventParticipationId;
	}

	@Override
	public void setEventParticipationId(long eventParticipationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventParticipationId = eventParticipationId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public String getPublikUserId() {
		if (_publikUserId == null) {
			return "";
		}
		else {
			return _publikUserId;
		}
	}

	@Override
	public void setPublikUserId(String publikUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publikUserId = publikUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPublikUserId() {
		return getColumnOriginalValue("publikUserId");
	}

	@JSON
	@Override
	public long getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(long eventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventId = eventId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEventId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("eventId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, EventParticipation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventParticipation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EventParticipation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventParticipationImpl eventParticipationImpl =
			new EventParticipationImpl();

		eventParticipationImpl.setEventParticipationId(
			getEventParticipationId());
		eventParticipationImpl.setCreateDate(getCreateDate());
		eventParticipationImpl.setPublikUserId(getPublikUserId());
		eventParticipationImpl.setEventId(getEventId());
		eventParticipationImpl.setGroupId(getGroupId());

		eventParticipationImpl.resetOriginalValues();

		return eventParticipationImpl;
	}

	@Override
	public EventParticipation cloneWithOriginalValues() {
		EventParticipationImpl eventParticipationImpl =
			new EventParticipationImpl();

		eventParticipationImpl.setEventParticipationId(
			this.<Long>getColumnOriginalValue("eventParticipationId"));
		eventParticipationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		eventParticipationImpl.setPublikUserId(
			this.<String>getColumnOriginalValue("publikUserId"));
		eventParticipationImpl.setEventId(
			this.<Long>getColumnOriginalValue("eventId"));
		eventParticipationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));

		return eventParticipationImpl;
	}

	@Override
	public int compareTo(EventParticipation eventParticipation) {
		long primaryKey = eventParticipation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EventParticipation)) {
			return false;
		}

		EventParticipation eventParticipation = (EventParticipation)object;

		long primaryKey = eventParticipation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EventParticipation> toCacheModel() {
		EventParticipationCacheModel eventParticipationCacheModel =
			new EventParticipationCacheModel();

		eventParticipationCacheModel.eventParticipationId =
			getEventParticipationId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			eventParticipationCacheModel.createDate = createDate.getTime();
		}
		else {
			eventParticipationCacheModel.createDate = Long.MIN_VALUE;
		}

		eventParticipationCacheModel.publikUserId = getPublikUserId();

		String publikUserId = eventParticipationCacheModel.publikUserId;

		if ((publikUserId != null) && (publikUserId.length() == 0)) {
			eventParticipationCacheModel.publikUserId = null;
		}

		eventParticipationCacheModel.eventId = getEventId();

		eventParticipationCacheModel.groupId = getGroupId();

		return eventParticipationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EventParticipation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EventParticipation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EventParticipation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EventParticipation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EventParticipation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EventParticipation.class, ModelWrapper.class);

	}

	private long _eventParticipationId;
	private Date _createDate;
	private String _publikUserId;
	private long _eventId;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		Function<EventParticipation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EventParticipation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"eventParticipationId", _eventParticipationId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("publikUserId", _publikUserId);
		_columnOriginalValues.put("eventId", _eventId);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("eventParticipationId", 1L);

		columnBitmasks.put("createDate", 2L);

		columnBitmasks.put("publikUserId", 4L);

		columnBitmasks.put("eventId", 8L);

		columnBitmasks.put("groupId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EventParticipation _escapedModel;

}