/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.agenda.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.agenda.model.Manifestation;
import eu.strasbourg.service.agenda.model.ManifestationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Manifestation service. Represents a row in the &quot;agenda_Manifestation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ManifestationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ManifestationImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see ManifestationImpl
 * @generated
 */
@JSON(strict = true)
public class ManifestationModelImpl
	extends BaseModelImpl<Manifestation> implements ManifestationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a manifestation model instance should use the <code>Manifestation</code> interface instead.
	 */
	public static final String TABLE_NAME = "agenda_Manifestation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"manifestationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"imageId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"description", Types.CLOB},
		{"externalImageURL", Types.VARCHAR},
		{"externalImageThumbnailURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"publicationDate", Types.TIMESTAMP}, {"source", Types.VARCHAR},
		{"idSource", Types.VARCHAR}, {"externalURL", Types.VARCHAR},
		{"createDateSource", Types.TIMESTAMP},
		{"modifiedDateSource", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manifestationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageThumbnailURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("publicationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("source", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idSource", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDateSource", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDateSource", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agenda_Manifestation (uuid_ VARCHAR(75) null,manifestationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,imageId LONG,title STRING null,description TEXT null,externalImageURL VARCHAR(75) null,externalImageThumbnailURL VARCHAR(255) null,externalImageCopyright VARCHAR(75) null,startDate DATE null,endDate DATE null,publicationDate DATE null,source VARCHAR(75) null,idSource VARCHAR(75) null,externalURL VARCHAR(500) null,createDateSource DATE null,modifiedDateSource DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table agenda_Manifestation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY manifestation.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agenda_Manifestation.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENDDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDSOURCE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLICATIONDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOURCE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUSDATE_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 512L;

	public static final String MAPPING_TABLE_AGENDA_EVENTTOMANIFESTATION_NAME =
		"agenda_EventToManifestation";

	public static final Object[][]
		MAPPING_TABLE_AGENDA_EVENTTOMANIFESTATION_COLUMNS = {
			{"companyId", Types.BIGINT}, {"eventId", Types.BIGINT},
			{"manifestationId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_AGENDA_EVENTTOMANIFESTATION_SQL_CREATE =
			"create table agenda_EventToManifestation (companyId LONG not null,eventId LONG not null,manifestationId LONG not null,primary key (eventId, manifestationId))";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean
		FINDER_CACHE_ENABLED_AGENDA_EVENTTOMANIFESTATION = true;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.agenda.model.Manifestation"));

	public ManifestationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _manifestationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setManifestationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _manifestationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Manifestation.class;
	}

	@Override
	public String getModelClassName() {
		return Manifestation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Manifestation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Manifestation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Manifestation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Manifestation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Manifestation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Manifestation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Manifestation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Manifestation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Manifestation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Manifestation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Manifestation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<Manifestation, Object>>();

			attributeGetterFunctions.put("uuid", Manifestation::getUuid);
			attributeGetterFunctions.put(
				"manifestationId", Manifestation::getManifestationId);
			attributeGetterFunctions.put("groupId", Manifestation::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Manifestation::getCompanyId);
			attributeGetterFunctions.put("userId", Manifestation::getUserId);
			attributeGetterFunctions.put(
				"userName", Manifestation::getUserName);
			attributeGetterFunctions.put(
				"createDate", Manifestation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Manifestation::getModifiedDate);
			attributeGetterFunctions.put(
				"lastPublishDate", Manifestation::getLastPublishDate);
			attributeGetterFunctions.put("status", Manifestation::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Manifestation::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Manifestation::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", Manifestation::getStatusDate);
			attributeGetterFunctions.put("imageId", Manifestation::getImageId);
			attributeGetterFunctions.put("title", Manifestation::getTitle);
			attributeGetterFunctions.put(
				"description", Manifestation::getDescription);
			attributeGetterFunctions.put(
				"externalImageURL", Manifestation::getExternalImageURL);
			attributeGetterFunctions.put(
				"externalImageThumbnailURL",
				Manifestation::getExternalImageThumbnailURL);
			attributeGetterFunctions.put(
				"externalImageCopyright",
				Manifestation::getExternalImageCopyright);
			attributeGetterFunctions.put(
				"startDate", Manifestation::getStartDate);
			attributeGetterFunctions.put("endDate", Manifestation::getEndDate);
			attributeGetterFunctions.put(
				"publicationDate", Manifestation::getPublicationDate);
			attributeGetterFunctions.put("source", Manifestation::getSource);
			attributeGetterFunctions.put(
				"idSource", Manifestation::getIdSource);
			attributeGetterFunctions.put(
				"externalURL", Manifestation::getExternalURL);
			attributeGetterFunctions.put(
				"createDateSource", Manifestation::getCreateDateSource);
			attributeGetterFunctions.put(
				"modifiedDateSource", Manifestation::getModifiedDateSource);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Manifestation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Manifestation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Manifestation, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Manifestation, String>)Manifestation::setUuid);
			attributeSetterBiConsumers.put(
				"manifestationId",
				(BiConsumer<Manifestation, Long>)
					Manifestation::setManifestationId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Manifestation, Long>)Manifestation::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Manifestation, Long>)Manifestation::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Manifestation, Long>)Manifestation::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Manifestation, String>)Manifestation::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Manifestation, Date>)Manifestation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Manifestation, Date>)
					Manifestation::setModifiedDate);
			attributeSetterBiConsumers.put(
				"lastPublishDate",
				(BiConsumer<Manifestation, Date>)
					Manifestation::setLastPublishDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<Manifestation, Integer>)Manifestation::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Manifestation, Long>)
					Manifestation::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Manifestation, String>)
					Manifestation::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<Manifestation, Date>)Manifestation::setStatusDate);
			attributeSetterBiConsumers.put(
				"imageId",
				(BiConsumer<Manifestation, Long>)Manifestation::setImageId);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<Manifestation, String>)Manifestation::setTitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<Manifestation, String>)
					Manifestation::setDescription);
			attributeSetterBiConsumers.put(
				"externalImageURL",
				(BiConsumer<Manifestation, String>)
					Manifestation::setExternalImageURL);
			attributeSetterBiConsumers.put(
				"externalImageThumbnailURL",
				(BiConsumer<Manifestation, String>)
					Manifestation::setExternalImageThumbnailURL);
			attributeSetterBiConsumers.put(
				"externalImageCopyright",
				(BiConsumer<Manifestation, String>)
					Manifestation::setExternalImageCopyright);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<Manifestation, Date>)Manifestation::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<Manifestation, Date>)Manifestation::setEndDate);
			attributeSetterBiConsumers.put(
				"publicationDate",
				(BiConsumer<Manifestation, Date>)
					Manifestation::setPublicationDate);
			attributeSetterBiConsumers.put(
				"source",
				(BiConsumer<Manifestation, String>)Manifestation::setSource);
			attributeSetterBiConsumers.put(
				"idSource",
				(BiConsumer<Manifestation, String>)Manifestation::setIdSource);
			attributeSetterBiConsumers.put(
				"externalURL",
				(BiConsumer<Manifestation, String>)
					Manifestation::setExternalURL);
			attributeSetterBiConsumers.put(
				"createDateSource",
				(BiConsumer<Manifestation, Date>)
					Manifestation::setCreateDateSource);
			attributeSetterBiConsumers.put(
				"modifiedDateSource",
				(BiConsumer<Manifestation, Date>)
					Manifestation::setModifiedDateSource);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getManifestationId() {
		return _manifestationId;
	}

	@Override
	public void setManifestationId(long manifestationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manifestationId = manifestationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalStatusDate() {
		return getColumnOriginalValue("statusDate");
	}

	@JSON
	@Override
	public Long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(Long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTitle() {
		return getColumnOriginalValue("title");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageThumbnailURL() {
		if (_externalImageThumbnailURL == null) {
			return "";
		}
		else {
			return _externalImageThumbnailURL;
		}
	}

	@Override
	public void setExternalImageThumbnailURL(String externalImageThumbnailURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageThumbnailURL = externalImageThumbnailURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalEndDate() {
		return getColumnOriginalValue("endDate");
	}

	@JSON
	@Override
	public Date getPublicationDate() {
		return _publicationDate;
	}

	@Override
	public void setPublicationDate(Date publicationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicationDate = publicationDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalPublicationDate() {
		return getColumnOriginalValue("publicationDate");
	}

	@JSON
	@Override
	public String getSource() {
		if (_source == null) {
			return "";
		}
		else {
			return _source;
		}
	}

	@Override
	public void setSource(String source) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_source = source;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSource() {
		return getColumnOriginalValue("source");
	}

	@JSON
	@Override
	public String getIdSource() {
		if (_idSource == null) {
			return "";
		}
		else {
			return _idSource;
		}
	}

	@Override
	public void setIdSource(String idSource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idSource = idSource;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalIdSource() {
		return getColumnOriginalValue("idSource");
	}

	@JSON
	@Override
	public String getExternalURL() {
		if (_externalURL == null) {
			return "";
		}
		else {
			return _externalURL;
		}
	}

	@Override
	public void setExternalURL(String externalURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalURL = externalURL;
	}

	@JSON
	@Override
	public Date getCreateDateSource() {
		return _createDateSource;
	}

	@Override
	public void setCreateDateSource(Date createDateSource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDateSource = createDateSource;
	}

	@JSON
	@Override
	public Date getModifiedDateSource() {
		return _modifiedDateSource;
	}

	@Override
	public void setModifiedDateSource(Date modifiedDateSource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDateSource = modifiedDateSource;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Manifestation.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Manifestation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Manifestation.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Manifestation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Manifestation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ManifestationImpl manifestationImpl = new ManifestationImpl();

		manifestationImpl.setUuid(getUuid());
		manifestationImpl.setManifestationId(getManifestationId());
		manifestationImpl.setGroupId(getGroupId());
		manifestationImpl.setCompanyId(getCompanyId());
		manifestationImpl.setUserId(getUserId());
		manifestationImpl.setUserName(getUserName());
		manifestationImpl.setCreateDate(getCreateDate());
		manifestationImpl.setModifiedDate(getModifiedDate());
		manifestationImpl.setLastPublishDate(getLastPublishDate());
		manifestationImpl.setStatus(getStatus());
		manifestationImpl.setStatusByUserId(getStatusByUserId());
		manifestationImpl.setStatusByUserName(getStatusByUserName());
		manifestationImpl.setStatusDate(getStatusDate());
		manifestationImpl.setImageId(getImageId());
		manifestationImpl.setTitle(getTitle());
		manifestationImpl.setDescription(getDescription());
		manifestationImpl.setExternalImageURL(getExternalImageURL());
		manifestationImpl.setExternalImageThumbnailURL(
			getExternalImageThumbnailURL());
		manifestationImpl.setExternalImageCopyright(
			getExternalImageCopyright());
		manifestationImpl.setStartDate(getStartDate());
		manifestationImpl.setEndDate(getEndDate());
		manifestationImpl.setPublicationDate(getPublicationDate());
		manifestationImpl.setSource(getSource());
		manifestationImpl.setIdSource(getIdSource());
		manifestationImpl.setExternalURL(getExternalURL());
		manifestationImpl.setCreateDateSource(getCreateDateSource());
		manifestationImpl.setModifiedDateSource(getModifiedDateSource());

		manifestationImpl.resetOriginalValues();

		return manifestationImpl;
	}

	@Override
	public Manifestation cloneWithOriginalValues() {
		ManifestationImpl manifestationImpl = new ManifestationImpl();

		manifestationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		manifestationImpl.setManifestationId(
			this.<Long>getColumnOriginalValue("manifestationId"));
		manifestationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		manifestationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		manifestationImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		manifestationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		manifestationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		manifestationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		manifestationImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		manifestationImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		manifestationImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		manifestationImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		manifestationImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		manifestationImpl.setImageId(
			this.<Long>getColumnOriginalValue("imageId"));
		manifestationImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		manifestationImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		manifestationImpl.setExternalImageURL(
			this.<String>getColumnOriginalValue("externalImageURL"));
		manifestationImpl.setExternalImageThumbnailURL(
			this.<String>getColumnOriginalValue("externalImageThumbnailURL"));
		manifestationImpl.setExternalImageCopyright(
			this.<String>getColumnOriginalValue("externalImageCopyright"));
		manifestationImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		manifestationImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		manifestationImpl.setPublicationDate(
			this.<Date>getColumnOriginalValue("publicationDate"));
		manifestationImpl.setSource(
			this.<String>getColumnOriginalValue("source"));
		manifestationImpl.setIdSource(
			this.<String>getColumnOriginalValue("idSource"));
		manifestationImpl.setExternalURL(
			this.<String>getColumnOriginalValue("externalURL"));
		manifestationImpl.setCreateDateSource(
			this.<Date>getColumnOriginalValue("createDateSource"));
		manifestationImpl.setModifiedDateSource(
			this.<Date>getColumnOriginalValue("modifiedDateSource"));

		return manifestationImpl;
	}

	@Override
	public int compareTo(Manifestation manifestation) {
		int value = 0;

		value = getTitle().compareTo(manifestation.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Manifestation)) {
			return false;
		}

		Manifestation manifestation = (Manifestation)object;

		long primaryKey = manifestation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Manifestation> toCacheModel() {
		ManifestationCacheModel manifestationCacheModel =
			new ManifestationCacheModel();

		manifestationCacheModel.uuid = getUuid();

		String uuid = manifestationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			manifestationCacheModel.uuid = null;
		}

		manifestationCacheModel.manifestationId = getManifestationId();

		manifestationCacheModel.groupId = getGroupId();

		manifestationCacheModel.companyId = getCompanyId();

		manifestationCacheModel.userId = getUserId();

		manifestationCacheModel.userName = getUserName();

		String userName = manifestationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			manifestationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			manifestationCacheModel.createDate = createDate.getTime();
		}
		else {
			manifestationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			manifestationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			manifestationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			manifestationCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			manifestationCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		manifestationCacheModel.status = getStatus();

		manifestationCacheModel.statusByUserId = getStatusByUserId();

		manifestationCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = manifestationCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			manifestationCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			manifestationCacheModel.statusDate = statusDate.getTime();
		}
		else {
			manifestationCacheModel.statusDate = Long.MIN_VALUE;
		}

		Long imageId = getImageId();

		if (imageId != null) {
			manifestationCacheModel.imageId = imageId;
		}

		manifestationCacheModel.title = getTitle();

		String title = manifestationCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			manifestationCacheModel.title = null;
		}

		manifestationCacheModel.description = getDescription();

		String description = manifestationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			manifestationCacheModel.description = null;
		}

		manifestationCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL = manifestationCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			manifestationCacheModel.externalImageURL = null;
		}

		manifestationCacheModel.externalImageThumbnailURL =
			getExternalImageThumbnailURL();

		String externalImageThumbnailURL =
			manifestationCacheModel.externalImageThumbnailURL;

		if ((externalImageThumbnailURL != null) &&
			(externalImageThumbnailURL.length() == 0)) {

			manifestationCacheModel.externalImageThumbnailURL = null;
		}

		manifestationCacheModel.externalImageCopyright =
			getExternalImageCopyright();

		String externalImageCopyright =
			manifestationCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			manifestationCacheModel.externalImageCopyright = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			manifestationCacheModel.startDate = startDate.getTime();
		}
		else {
			manifestationCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			manifestationCacheModel.endDate = endDate.getTime();
		}
		else {
			manifestationCacheModel.endDate = Long.MIN_VALUE;
		}

		Date publicationDate = getPublicationDate();

		if (publicationDate != null) {
			manifestationCacheModel.publicationDate = publicationDate.getTime();
		}
		else {
			manifestationCacheModel.publicationDate = Long.MIN_VALUE;
		}

		manifestationCacheModel.source = getSource();

		String source = manifestationCacheModel.source;

		if ((source != null) && (source.length() == 0)) {
			manifestationCacheModel.source = null;
		}

		manifestationCacheModel.idSource = getIdSource();

		String idSource = manifestationCacheModel.idSource;

		if ((idSource != null) && (idSource.length() == 0)) {
			manifestationCacheModel.idSource = null;
		}

		manifestationCacheModel.externalURL = getExternalURL();

		String externalURL = manifestationCacheModel.externalURL;

		if ((externalURL != null) && (externalURL.length() == 0)) {
			manifestationCacheModel.externalURL = null;
		}

		Date createDateSource = getCreateDateSource();

		if (createDateSource != null) {
			manifestationCacheModel.createDateSource =
				createDateSource.getTime();
		}
		else {
			manifestationCacheModel.createDateSource = Long.MIN_VALUE;
		}

		Date modifiedDateSource = getModifiedDateSource();

		if (modifiedDateSource != null) {
			manifestationCacheModel.modifiedDateSource =
				modifiedDateSource.getTime();
		}
		else {
			manifestationCacheModel.modifiedDateSource = Long.MIN_VALUE;
		}

		return manifestationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Manifestation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Manifestation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Manifestation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Manifestation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Manifestation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Manifestation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _manifestationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Long _imageId;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _externalImageURL;
	private String _externalImageThumbnailURL;
	private String _externalImageCopyright;
	private Date _startDate;
	private Date _endDate;
	private Date _publicationDate;
	private String _source;
	private String _idSource;
	private String _externalURL;
	private Date _createDateSource;
	private Date _modifiedDateSource;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Manifestation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Manifestation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("manifestationId", _manifestationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("externalImageURL", _externalImageURL);
		_columnOriginalValues.put(
			"externalImageThumbnailURL", _externalImageThumbnailURL);
		_columnOriginalValues.put(
			"externalImageCopyright", _externalImageCopyright);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("publicationDate", _publicationDate);
		_columnOriginalValues.put("source", _source);
		_columnOriginalValues.put("idSource", _idSource);
		_columnOriginalValues.put("externalURL", _externalURL);
		_columnOriginalValues.put("createDateSource", _createDateSource);
		_columnOriginalValues.put("modifiedDateSource", _modifiedDateSource);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("manifestationId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("lastPublishDate", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("statusByUserId", 1024L);

		columnBitmasks.put("statusByUserName", 2048L);

		columnBitmasks.put("statusDate", 4096L);

		columnBitmasks.put("imageId", 8192L);

		columnBitmasks.put("title", 16384L);

		columnBitmasks.put("description", 32768L);

		columnBitmasks.put("externalImageURL", 65536L);

		columnBitmasks.put("externalImageThumbnailURL", 131072L);

		columnBitmasks.put("externalImageCopyright", 262144L);

		columnBitmasks.put("startDate", 524288L);

		columnBitmasks.put("endDate", 1048576L);

		columnBitmasks.put("publicationDate", 2097152L);

		columnBitmasks.put("source", 4194304L);

		columnBitmasks.put("idSource", 8388608L);

		columnBitmasks.put("externalURL", 16777216L);

		columnBitmasks.put("createDateSource", 33554432L);

		columnBitmasks.put("modifiedDateSource", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Manifestation _escapedModel;

}