/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package eu.strasbourg.service.link.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.link.model.Link;
import eu.strasbourg.service.link.model.LinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Link service. Represents a row in the &quot;link_Link&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinkImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see LinkImpl
 * @generated
 */
@JSON(strict = true)
public class LinkModelImpl extends BaseModelImpl<Link> implements LinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a link model instance should use the <code>Link</code> interface instead.
	 */
	public static final String TABLE_NAME = "link_Link";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"linkId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"URL", Types.VARCHAR}, {"hoverText", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("URL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoverText", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table link_Link (uuid_ VARCHAR(75) null,linkId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title STRING null,URL STRING null,hoverText STRING null)";

	public static final String TABLE_SQL_DROP = "drop table link_Link";

	public static final String ORDER_BY_JPQL =
		" ORDER BY link.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY link_Link.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.link.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.link.model.Link"));

	public LinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _linkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _linkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Link.class;
	}

	@Override
	public String getModelClassName() {
		return Link.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Link, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Link, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Link, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Link)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Link, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Link, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Link)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Link, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Link, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Link, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Link, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Link, Object>>();

			attributeGetterFunctions.put("uuid", Link::getUuid);
			attributeGetterFunctions.put("linkId", Link::getLinkId);
			attributeGetterFunctions.put("groupId", Link::getGroupId);
			attributeGetterFunctions.put("companyId", Link::getCompanyId);
			attributeGetterFunctions.put("userId", Link::getUserId);
			attributeGetterFunctions.put("userName", Link::getUserName);
			attributeGetterFunctions.put("createDate", Link::getCreateDate);
			attributeGetterFunctions.put("modifiedDate", Link::getModifiedDate);
			attributeGetterFunctions.put(
				"lastPublishDate", Link::getLastPublishDate);
			attributeGetterFunctions.put("status", Link::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", Link::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", Link::getStatusByUserName);
			attributeGetterFunctions.put("statusDate", Link::getStatusDate);
			attributeGetterFunctions.put("title", Link::getTitle);
			attributeGetterFunctions.put("URL", Link::getURL);
			attributeGetterFunctions.put("hoverText", Link::getHoverText);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Link, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Link, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Link, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Link, String>)Link::setUuid);
			attributeSetterBiConsumers.put(
				"linkId", (BiConsumer<Link, Long>)Link::setLinkId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Link, Long>)Link::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Link, Long>)Link::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Link, Long>)Link::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Link, String>)Link::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Link, Date>)Link::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate", (BiConsumer<Link, Date>)Link::setModifiedDate);
			attributeSetterBiConsumers.put(
				"lastPublishDate",
				(BiConsumer<Link, Date>)Link::setLastPublishDate);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Link, Integer>)Link::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<Link, Long>)Link::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<Link, String>)Link::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate", (BiConsumer<Link, Date>)Link::setStatusDate);
			attributeSetterBiConsumers.put(
				"title", (BiConsumer<Link, String>)Link::setTitle);
			attributeSetterBiConsumers.put(
				"URL", (BiConsumer<Link, String>)Link::setURL);
			attributeSetterBiConsumers.put(
				"hoverText", (BiConsumer<Link, String>)Link::setHoverText);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLinkId() {
		return _linkId;
	}

	@Override
	public void setLinkId(long linkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkId = linkId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getURL() {
		if (_URL == null) {
			return "";
		}
		else {
			return _URL;
		}
	}

	@Override
	public String getURL(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getURL(languageId);
	}

	@Override
	public String getURL(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getURL(languageId, useDefault);
	}

	@Override
	public String getURL(String languageId) {
		return LocalizationUtil.getLocalization(getURL(), languageId);
	}

	@Override
	public String getURL(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getURL(), languageId, useDefault);
	}

	@Override
	public String getURLCurrentLanguageId() {
		return _URLCurrentLanguageId;
	}

	@JSON
	@Override
	public String getURLCurrentValue() {
		Locale locale = getLocale(_URLCurrentLanguageId);

		return getURL(locale);
	}

	@Override
	public Map<Locale, String> getURLMap() {
		return LocalizationUtil.getLocalizationMap(getURL());
	}

	@Override
	public void setURL(String URL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_URL = URL;
	}

	@Override
	public void setURL(String URL, Locale locale) {
		setURL(URL, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setURL(String URL, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(URL)) {
			setURL(
				LocalizationUtil.updateLocalization(
					getURL(), "URL", URL, languageId, defaultLanguageId));
		}
		else {
			setURL(
				LocalizationUtil.removeLocalization(
					getURL(), "URL", languageId));
		}
	}

	@Override
	public void setURLCurrentLanguageId(String languageId) {
		_URLCurrentLanguageId = languageId;
	}

	@Override
	public void setURLMap(Map<Locale, String> URLMap) {
		setURLMap(URLMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setURLMap(Map<Locale, String> URLMap, Locale defaultLocale) {
		if (URLMap == null) {
			return;
		}

		setURL(
			LocalizationUtil.updateLocalization(
				URLMap, getURL(), "URL",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getHoverText() {
		if (_hoverText == null) {
			return "";
		}
		else {
			return _hoverText;
		}
	}

	@Override
	public String getHoverText(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getHoverText(languageId);
	}

	@Override
	public String getHoverText(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getHoverText(languageId, useDefault);
	}

	@Override
	public String getHoverText(String languageId) {
		return LocalizationUtil.getLocalization(getHoverText(), languageId);
	}

	@Override
	public String getHoverText(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getHoverText(), languageId, useDefault);
	}

	@Override
	public String getHoverTextCurrentLanguageId() {
		return _hoverTextCurrentLanguageId;
	}

	@JSON
	@Override
	public String getHoverTextCurrentValue() {
		Locale locale = getLocale(_hoverTextCurrentLanguageId);

		return getHoverText(locale);
	}

	@Override
	public Map<Locale, String> getHoverTextMap() {
		return LocalizationUtil.getLocalizationMap(getHoverText());
	}

	@Override
	public void setHoverText(String hoverText) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hoverText = hoverText;
	}

	@Override
	public void setHoverText(String hoverText, Locale locale) {
		setHoverText(hoverText, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setHoverText(
		String hoverText, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(hoverText)) {
			setHoverText(
				LocalizationUtil.updateLocalization(
					getHoverText(), "HoverText", hoverText, languageId,
					defaultLanguageId));
		}
		else {
			setHoverText(
				LocalizationUtil.removeLocalization(
					getHoverText(), "HoverText", languageId));
		}
	}

	@Override
	public void setHoverTextCurrentLanguageId(String languageId) {
		_hoverTextCurrentLanguageId = languageId;
	}

	@Override
	public void setHoverTextMap(Map<Locale, String> hoverTextMap) {
		setHoverTextMap(hoverTextMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setHoverTextMap(
		Map<Locale, String> hoverTextMap, Locale defaultLocale) {

		if (hoverTextMap == null) {
			return;
		}

		setHoverText(
			LocalizationUtil.updateLocalization(
				hoverTextMap, getHoverText(), "HoverText",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Link.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Link.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> URLMap = getURLMap();

		for (Map.Entry<Locale, String> entry : URLMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> hoverTextMap = getHoverTextMap();

		for (Map.Entry<Locale, String> entry : hoverTextMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Link.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String URL = getURL(defaultLocale);

		if (Validator.isNull(URL)) {
			setURL(getURL(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setURL(getURL(defaultLocale), defaultLocale, defaultLocale);
		}

		String hoverText = getHoverText(defaultLocale);

		if (Validator.isNull(hoverText)) {
			setHoverText(getHoverText(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setHoverText(
				getHoverText(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Link toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Link>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LinkImpl linkImpl = new LinkImpl();

		linkImpl.setUuid(getUuid());
		linkImpl.setLinkId(getLinkId());
		linkImpl.setGroupId(getGroupId());
		linkImpl.setCompanyId(getCompanyId());
		linkImpl.setUserId(getUserId());
		linkImpl.setUserName(getUserName());
		linkImpl.setCreateDate(getCreateDate());
		linkImpl.setModifiedDate(getModifiedDate());
		linkImpl.setLastPublishDate(getLastPublishDate());
		linkImpl.setStatus(getStatus());
		linkImpl.setStatusByUserId(getStatusByUserId());
		linkImpl.setStatusByUserName(getStatusByUserName());
		linkImpl.setStatusDate(getStatusDate());
		linkImpl.setTitle(getTitle());
		linkImpl.setURL(getURL());
		linkImpl.setHoverText(getHoverText());

		linkImpl.resetOriginalValues();

		return linkImpl;
	}

	@Override
	public Link cloneWithOriginalValues() {
		LinkImpl linkImpl = new LinkImpl();

		linkImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		linkImpl.setLinkId(this.<Long>getColumnOriginalValue("linkId"));
		linkImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		linkImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		linkImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		linkImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		linkImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		linkImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		linkImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		linkImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		linkImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		linkImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		linkImpl.setStatusDate(this.<Date>getColumnOriginalValue("statusDate"));
		linkImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		linkImpl.setURL(this.<String>getColumnOriginalValue("URL"));
		linkImpl.setHoverText(this.<String>getColumnOriginalValue("hoverText"));

		return linkImpl;
	}

	@Override
	public int compareTo(Link link) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(), link.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Link)) {
			return false;
		}

		Link link = (Link)object;

		long primaryKey = link.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Link> toCacheModel() {
		LinkCacheModel linkCacheModel = new LinkCacheModel();

		linkCacheModel.uuid = getUuid();

		String uuid = linkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			linkCacheModel.uuid = null;
		}

		linkCacheModel.linkId = getLinkId();

		linkCacheModel.groupId = getGroupId();

		linkCacheModel.companyId = getCompanyId();

		linkCacheModel.userId = getUserId();

		linkCacheModel.userName = getUserName();

		String userName = linkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			linkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			linkCacheModel.createDate = createDate.getTime();
		}
		else {
			linkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			linkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			linkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			linkCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			linkCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		linkCacheModel.status = getStatus();

		linkCacheModel.statusByUserId = getStatusByUserId();

		linkCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = linkCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			linkCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			linkCacheModel.statusDate = statusDate.getTime();
		}
		else {
			linkCacheModel.statusDate = Long.MIN_VALUE;
		}

		linkCacheModel.title = getTitle();

		String title = linkCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			linkCacheModel.title = null;
		}

		linkCacheModel.URL = getURL();

		String URL = linkCacheModel.URL;

		if ((URL != null) && (URL.length() == 0)) {
			linkCacheModel.URL = null;
		}

		linkCacheModel.hoverText = getHoverText();

		String hoverText = linkCacheModel.hoverText;

		if ((hoverText != null) && (hoverText.length() == 0)) {
			linkCacheModel.hoverText = null;
		}

		return linkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Link, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Link, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Link, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Link)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Link>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Link.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _linkId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _titleCurrentLanguageId;

	private String _URL;

	private String _URLCurrentLanguageId;
	private String _hoverText;
	private String _hoverTextCurrentLanguageId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Link, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Link)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("linkId", _linkId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("URL", _URL);
		_columnOriginalValues.put("hoverText", _hoverText);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("linkId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("lastPublishDate", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("statusByUserId", 1024L);

		columnBitmasks.put("statusByUserName", 2048L);

		columnBitmasks.put("statusDate", 4096L);

		columnBitmasks.put("title", 8192L);

		columnBitmasks.put("URL", 16384L);

		columnBitmasks.put("hoverText", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Link _escapedModel;

}