/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.video.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.video.model.Video;
import eu.strasbourg.service.video.model.VideoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Video service. Represents a row in the &quot;video_Video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VideoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see VideoImpl
 * @generated
 */
@JSON(strict = true)
public class VideoModelImpl extends BaseModelImpl<Video> implements VideoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video model instance should use the <code>Video</code> interface instead.
	 */
	public static final String TABLE_NAME = "video_Video";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"videoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"description", Types.CLOB}, {"copyright", Types.VARCHAR},
		{"source", Types.VARCHAR}, {"publicationDate", Types.TIMESTAMP},
		{"imageId", Types.BIGINT}, {"transcriptionFileId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("videoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("copyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("source", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("transcriptionFileId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table video_Video (uuid_ VARCHAR(75) null,videoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title STRING null,description TEXT null,copyright STRING null,source STRING null,publicationDate DATE null,imageId LONG,transcriptionFileId LONG)";

	public static final String TABLE_SQL_DROP = "drop table video_Video";

	public static final String ORDER_BY_JPQL =
		" ORDER BY video.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY video_Video.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PUBLICATIONDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	public static final String MAPPING_TABLE_VIDEO_VIDEOTOVIDEOGALLERY_NAME =
		"video_VideoToVideoGallery";

	public static final Object[][]
		MAPPING_TABLE_VIDEO_VIDEOTOVIDEOGALLERY_COLUMNS = {
			{"companyId", Types.BIGINT}, {"videoId", Types.BIGINT},
			{"galleryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_VIDEO_VIDEOTOVIDEOGALLERY_SQL_CREATE =
			"create table video_VideoToVideoGallery (companyId LONG not null,videoId LONG not null,galleryId LONG not null,primary key (videoId, galleryId))";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED_VIDEO_VIDEOTOVIDEOGALLERY =
		true;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.video.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.video.model.Video"));

	public VideoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _videoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVideoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _videoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video.class;
	}

	@Override
	public String getModelClassName() {
		return Video.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Video, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Video, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Video)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Video, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Video, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Video)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Video, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Video, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Video, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Video, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Video, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Video, Object>>();
		Map<String, BiConsumer<Video, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Video, ?>>();

		attributeGetterFunctions.put("uuid", Video::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Video, String>)Video::setUuid);
		attributeGetterFunctions.put("videoId", Video::getVideoId);
		attributeSetterBiConsumers.put(
			"videoId", (BiConsumer<Video, Long>)Video::setVideoId);
		attributeGetterFunctions.put("groupId", Video::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Video, Long>)Video::setGroupId);
		attributeGetterFunctions.put("companyId", Video::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Video, Long>)Video::setCompanyId);
		attributeGetterFunctions.put("userId", Video::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Video, Long>)Video::setUserId);
		attributeGetterFunctions.put("userName", Video::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Video, String>)Video::setUserName);
		attributeGetterFunctions.put("createDate", Video::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Video, Date>)Video::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Video::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Video, Date>)Video::setModifiedDate);
		attributeGetterFunctions.put(
			"lastPublishDate", Video::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<Video, Date>)Video::setLastPublishDate);
		attributeGetterFunctions.put("status", Video::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Video, Integer>)Video::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Video::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Video, Long>)Video::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Video::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Video, String>)Video::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Video::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Video, Date>)Video::setStatusDate);
		attributeGetterFunctions.put("title", Video::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Video, String>)Video::setTitle);
		attributeGetterFunctions.put("description", Video::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Video, String>)Video::setDescription);
		attributeGetterFunctions.put("copyright", Video::getCopyright);
		attributeSetterBiConsumers.put(
			"copyright", (BiConsumer<Video, String>)Video::setCopyright);
		attributeGetterFunctions.put("source", Video::getSource);
		attributeSetterBiConsumers.put(
			"source", (BiConsumer<Video, String>)Video::setSource);
		attributeGetterFunctions.put(
			"publicationDate", Video::getPublicationDate);
		attributeSetterBiConsumers.put(
			"publicationDate",
			(BiConsumer<Video, Date>)Video::setPublicationDate);
		attributeGetterFunctions.put("imageId", Video::getImageId);
		attributeSetterBiConsumers.put(
			"imageId", (BiConsumer<Video, Long>)Video::setImageId);
		attributeGetterFunctions.put(
			"transcriptionFileId", Video::getTranscriptionFileId);
		attributeSetterBiConsumers.put(
			"transcriptionFileId",
			(BiConsumer<Video, Long>)Video::setTranscriptionFileId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getVideoId() {
		return _videoId;
	}

	@Override
	public void setVideoId(long videoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_videoId = videoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getCopyright() {
		if (_copyright == null) {
			return "";
		}
		else {
			return _copyright;
		}
	}

	@Override
	public String getCopyright(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCopyright(languageId);
	}

	@Override
	public String getCopyright(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getCopyright(languageId, useDefault);
	}

	@Override
	public String getCopyright(String languageId) {
		return LocalizationUtil.getLocalization(getCopyright(), languageId);
	}

	@Override
	public String getCopyright(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getCopyright(), languageId, useDefault);
	}

	@Override
	public String getCopyrightCurrentLanguageId() {
		return _copyrightCurrentLanguageId;
	}

	@JSON
	@Override
	public String getCopyrightCurrentValue() {
		Locale locale = getLocale(_copyrightCurrentLanguageId);

		return getCopyright(locale);
	}

	@Override
	public Map<Locale, String> getCopyrightMap() {
		return LocalizationUtil.getLocalizationMap(getCopyright());
	}

	@Override
	public void setCopyright(String copyright) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_copyright = copyright;
	}

	@Override
	public void setCopyright(String copyright, Locale locale) {
		setCopyright(copyright, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCopyright(
		String copyright, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(copyright)) {
			setCopyright(
				LocalizationUtil.updateLocalization(
					getCopyright(), "Copyright", copyright, languageId,
					defaultLanguageId));
		}
		else {
			setCopyright(
				LocalizationUtil.removeLocalization(
					getCopyright(), "Copyright", languageId));
		}
	}

	@Override
	public void setCopyrightCurrentLanguageId(String languageId) {
		_copyrightCurrentLanguageId = languageId;
	}

	@Override
	public void setCopyrightMap(Map<Locale, String> copyrightMap) {
		setCopyrightMap(copyrightMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setCopyrightMap(
		Map<Locale, String> copyrightMap, Locale defaultLocale) {

		if (copyrightMap == null) {
			return;
		}

		setCopyright(
			LocalizationUtil.updateLocalization(
				copyrightMap, getCopyright(), "Copyright",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getSource() {
		if (_source == null) {
			return "";
		}
		else {
			return _source;
		}
	}

	@Override
	public String getSource(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSource(languageId);
	}

	@Override
	public String getSource(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getSource(languageId, useDefault);
	}

	@Override
	public String getSource(String languageId) {
		return LocalizationUtil.getLocalization(getSource(), languageId);
	}

	@Override
	public String getSource(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getSource(), languageId, useDefault);
	}

	@Override
	public String getSourceCurrentLanguageId() {
		return _sourceCurrentLanguageId;
	}

	@JSON
	@Override
	public String getSourceCurrentValue() {
		Locale locale = getLocale(_sourceCurrentLanguageId);

		return getSource(locale);
	}

	@Override
	public Map<Locale, String> getSourceMap() {
		return LocalizationUtil.getLocalizationMap(getSource());
	}

	@Override
	public void setSource(String source) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_source = source;
	}

	@Override
	public void setSource(String source, Locale locale) {
		setSource(source, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSource(String source, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(source)) {
			setSource(
				LocalizationUtil.updateLocalization(
					getSource(), "Source", source, languageId,
					defaultLanguageId));
		}
		else {
			setSource(
				LocalizationUtil.removeLocalization(
					getSource(), "Source", languageId));
		}
	}

	@Override
	public void setSourceCurrentLanguageId(String languageId) {
		_sourceCurrentLanguageId = languageId;
	}

	@Override
	public void setSourceMap(Map<Locale, String> sourceMap) {
		setSourceMap(sourceMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setSourceMap(
		Map<Locale, String> sourceMap, Locale defaultLocale) {

		if (sourceMap == null) {
			return;
		}

		setSource(
			LocalizationUtil.updateLocalization(
				sourceMap, getSource(), "Source",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public Date getPublicationDate() {
		return _publicationDate;
	}

	@Override
	public void setPublicationDate(Date publicationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publicationDate = publicationDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalPublicationDate() {
		return getColumnOriginalValue("publicationDate");
	}

	@JSON
	@Override
	public Long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(Long imageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageId = imageId;
	}

	@JSON
	@Override
	public Long getTranscriptionFileId() {
		return _transcriptionFileId;
	}

	@Override
	public void setTranscriptionFileId(Long transcriptionFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transcriptionFileId = transcriptionFileId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Video.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Video.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> copyrightMap = getCopyrightMap();

		for (Map.Entry<Locale, String> entry : copyrightMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> sourceMap = getSourceMap();

		for (Map.Entry<Locale, String> entry : sourceMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Video.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}

		String copyright = getCopyright(defaultLocale);

		if (Validator.isNull(copyright)) {
			setCopyright(getCopyright(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setCopyright(
				getCopyright(defaultLocale), defaultLocale, defaultLocale);
		}

		String source = getSource(defaultLocale);

		if (Validator.isNull(source)) {
			setSource(getSource(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setSource(getSource(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Video toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Video>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VideoImpl videoImpl = new VideoImpl();

		videoImpl.setUuid(getUuid());
		videoImpl.setVideoId(getVideoId());
		videoImpl.setGroupId(getGroupId());
		videoImpl.setCompanyId(getCompanyId());
		videoImpl.setUserId(getUserId());
		videoImpl.setUserName(getUserName());
		videoImpl.setCreateDate(getCreateDate());
		videoImpl.setModifiedDate(getModifiedDate());
		videoImpl.setLastPublishDate(getLastPublishDate());
		videoImpl.setStatus(getStatus());
		videoImpl.setStatusByUserId(getStatusByUserId());
		videoImpl.setStatusByUserName(getStatusByUserName());
		videoImpl.setStatusDate(getStatusDate());
		videoImpl.setTitle(getTitle());
		videoImpl.setDescription(getDescription());
		videoImpl.setCopyright(getCopyright());
		videoImpl.setSource(getSource());
		videoImpl.setPublicationDate(getPublicationDate());
		videoImpl.setImageId(getImageId());
		videoImpl.setTranscriptionFileId(getTranscriptionFileId());

		videoImpl.resetOriginalValues();

		return videoImpl;
	}

	@Override
	public Video cloneWithOriginalValues() {
		VideoImpl videoImpl = new VideoImpl();

		videoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		videoImpl.setVideoId(this.<Long>getColumnOriginalValue("videoId"));
		videoImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		videoImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		videoImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		videoImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		videoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		videoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		videoImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		videoImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		videoImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		videoImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		videoImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));
		videoImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		videoImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		videoImpl.setCopyright(
			this.<String>getColumnOriginalValue("copyright"));
		videoImpl.setSource(this.<String>getColumnOriginalValue("source"));
		videoImpl.setPublicationDate(
			this.<Date>getColumnOriginalValue("publicationDate"));
		videoImpl.setImageId(this.<Long>getColumnOriginalValue("imageId"));
		videoImpl.setTranscriptionFileId(
			this.<Long>getColumnOriginalValue("transcriptionFileId"));

		return videoImpl;
	}

	@Override
	public int compareTo(Video video) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(), video.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Video)) {
			return false;
		}

		Video video = (Video)object;

		long primaryKey = video.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Video> toCacheModel() {
		VideoCacheModel videoCacheModel = new VideoCacheModel();

		videoCacheModel.uuid = getUuid();

		String uuid = videoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			videoCacheModel.uuid = null;
		}

		videoCacheModel.videoId = getVideoId();

		videoCacheModel.groupId = getGroupId();

		videoCacheModel.companyId = getCompanyId();

		videoCacheModel.userId = getUserId();

		videoCacheModel.userName = getUserName();

		String userName = videoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			videoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			videoCacheModel.createDate = createDate.getTime();
		}
		else {
			videoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			videoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			videoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			videoCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			videoCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		videoCacheModel.status = getStatus();

		videoCacheModel.statusByUserId = getStatusByUserId();

		videoCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = videoCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			videoCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			videoCacheModel.statusDate = statusDate.getTime();
		}
		else {
			videoCacheModel.statusDate = Long.MIN_VALUE;
		}

		videoCacheModel.title = getTitle();

		String title = videoCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			videoCacheModel.title = null;
		}

		videoCacheModel.description = getDescription();

		String description = videoCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			videoCacheModel.description = null;
		}

		videoCacheModel.copyright = getCopyright();

		String copyright = videoCacheModel.copyright;

		if ((copyright != null) && (copyright.length() == 0)) {
			videoCacheModel.copyright = null;
		}

		videoCacheModel.source = getSource();

		String source = videoCacheModel.source;

		if ((source != null) && (source.length() == 0)) {
			videoCacheModel.source = null;
		}

		Date publicationDate = getPublicationDate();

		if (publicationDate != null) {
			videoCacheModel.publicationDate = publicationDate.getTime();
		}
		else {
			videoCacheModel.publicationDate = Long.MIN_VALUE;
		}

		Long imageId = getImageId();

		if (imageId != null) {
			videoCacheModel.imageId = imageId;
		}

		Long transcriptionFileId = getTranscriptionFileId();

		if (transcriptionFileId != null) {
			videoCacheModel.transcriptionFileId = transcriptionFileId;
		}

		return videoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Video, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Video, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Video)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Video>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Video.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _videoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _copyright;
	private String _copyrightCurrentLanguageId;
	private String _source;
	private String _sourceCurrentLanguageId;
	private Date _publicationDate;
	private Long _imageId;
	private Long _transcriptionFileId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Video, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Video)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("videoId", _videoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("copyright", _copyright);
		_columnOriginalValues.put("source", _source);
		_columnOriginalValues.put("publicationDate", _publicationDate);
		_columnOriginalValues.put("imageId", _imageId);
		_columnOriginalValues.put("transcriptionFileId", _transcriptionFileId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("videoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("lastPublishDate", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("statusByUserId", 1024L);

		columnBitmasks.put("statusByUserName", 2048L);

		columnBitmasks.put("statusDate", 4096L);

		columnBitmasks.put("title", 8192L);

		columnBitmasks.put("description", 16384L);

		columnBitmasks.put("copyright", 32768L);

		columnBitmasks.put("source", 65536L);

		columnBitmasks.put("publicationDate", 131072L);

		columnBitmasks.put("imageId", 262144L);

		columnBitmasks.put("transcriptionFileId", 524288L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Video _escapedModel;

}